### ISSUE TITLE
Saving category when adding post isn't refreshing list.

### ISSUE THREAD

**Issue by galuszkak** [nephila/djangocms-blog#101]
When I click Save to create new category in dialog It doesn't refresh in parent window. 

In js console there is error `Uncaught ReferenceError: SelectBox is not defined ` . There isn't anywhere included SelectBox.js so seems to me that there is error somewhere.

**Comment by galuszkak** [comment]
![screen shot 2015-02-24 at 16 01 51](https://cloud.githubusercontent.com/assets/759579/6351768/85ae313c-bc3e-11e4-8113-372e0152549a.png)

**Comment by galuszkak** [comment]
Failing project is here: https://github.com/galuszkak/djangocmslink_bug

**Comment by galuszkak** [comment]
I found what is problem. Actually code is fine, with extension AngularJS Batarang in Chrome this is failing. Sorry for wasting your time on this bug @yakky .

**Comment by yakky** [comment]
No worries, closing this then
