### ISSUE TITLE
Req.: New PyPi Packages...

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#103]
I need https://github.com/nephila/djangocms-blog/commit/58373c1586394615ec4bebf2d97524059b0b82a8 in my project.

@yakky can you submit a new release to PyPi, please?

**Comment by yakky** [comment]
I plan to release a 0.4.b1 version this weekend

**Comment by jedie** [comment]
Great :+1:

**Comment by yakky** [comment]
Version 0.4.0.b1 released!
