### ISSUE TITLE
Migration dependency issue

### ISSUE THREAD

**Issue by tomassommar** [nephila/djangocms-blog#105]
When running migrations (as documented in README.rst) on djangocms-blog on Django 1.7.4 and django-cms 3.0.10, the migrations fails on django/db/migrations/graph.py", line 46 in add_dependency
with the following error: 
```
"Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: u"Migration djangocms_blog.0001_initial dependencies reference nonexistent parent node (u'cms', u'0003_auto_20140926_2347')"
```

Any ideas on how to resolve this issue?

**Comment by jedie** [comment]
You should check your **settings.MIGRATION_MODULES**

**Comment by tomassommar** [comment]
I did, and the settings is as documented in README.rst.

**Comment by jedie** [comment]
Ah. sorry. Is a other problem...

Seems that django doesn't find **cms/migrations/0003_auto_20140926_2347.py**
This file should be exists, check: https://github.com/divio/django-cms/blob/develop/cms/migrations/0003_auto_20140926_2347.py

**Comment by tomassommar** [comment]
It does exist, but not at that location. It exists at cms/migrations_django/0003_auto_20140926_2347.py . Perhaps this is related to it existing under migrations_django rather than migrations?

**Comment by tomassommar** [comment]
However, if I look at the settings in MIGRATION_MODULES it reference the migrations under migrations_django: 

```
MIGRATION_MODULES = {
    'easy_thumbnails': 'easy_thumbnails.south_migrations',
    'cms': 'cms.migrations_django',
    'menus': 'menus.migrations_django',
    'filer': 'filer.migrations_django',
    'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
    'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
    'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
    'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
    'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django',
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
    }
```

**Comment by jedie** [comment]
Sorry, i use the cms **develop** branch... The 3.0.x is here: https://github.com/divio/django-cms/tree/support/3.0.x/cms/migrations_django and yes, there it is under **migrations_django** ;)

Your **MIGRATION_MODULES** looks ok.

Hm....

**Comment by yakky** [comment]
@tomassommar the easy_thumbnails migration does not look right
I tried to reproduce by installing a django CMS project with djangocms-installer and then going through the quickhint section of the readme and all the migration has been applied / recognised correctly

**Comment by jedie** [comment]
> @tomassommar the easy_thumbnails migration does not look right

Ah, yes:

![bildschirmfoto - 27 02 2015 - 07 58 22](https://cloud.githubusercontent.com/assets/71315/6408531/94e60f3e-be56-11e4-89e5-73e18503488b.png)

;)

**Comment by tomassommar** [comment]
You're absolutely right, thanks for pointing this out.

However, I still have the same issue. Tried to reinstall everything on a new virtuanenv and a new database, but still the same error persists. Hmm... I will have to look into this further.

**Comment by tomassommar** [comment]
I found the issue, and it was all on my end. I had extracted the MIGRATION_MODULE settings into it's own file which was then imported into settings (for cleaner settings). However, this must have messed up namespacing. When moving MIGRATION_MODULE back to settings it worked out alright.

Sorry for bothering you with this issue which was obviously an error on my and. Thank you for you help!

**Comment by yakky** [comment]
No worries :)
Closing this as it's solved

**Comment by tlrh314** [comment]
Hi guys! I still have sort of this error when I run `manage syncdb'. My settings does contain the Django 1.7 code regarding the `MIGRATION_MODULES' as given in the Quick Hint section. 

KeyError: u"Migration djangocms_blog.0001_initial dependencies reference nonexistent parent node (u'filer', u'0001_initial')"

Pip freeze yields the following (relevant) versions:
Django==1.7.5
django-cms==3.0.12
djangocms-blog==0.3.1

Would you guys know how to fix it?

**Comment by yakky** [comment]
Apparently MIGRATION_MODULES for  django-filer is not correct. Could you post it?

**Comment by rando305** [comment]
I'm having a similar problem with django-cms migrations.  I am getting the following - but I don't really understand how this was resolved above.  I haven't moved my MIGRATION MODULES.  Do they need to be above the INSTALLED_APPS settings?  What do you need to see?  And what is the best way to post a snippet?  gist?

**Comment by yakky** [comment]
django-filer 0.9.10 moved the migrations to the proper location, so you don't need migration modules anymore.
I updated the readme

**Comment by rando305** [comment]
Thanks yakky.  I'm in a few readmes right now.  Which one did you update?  Thanks

**Comment by rando305** [comment]
These are my migration modules.  Which don't i need anymore?
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
    'cms': 'cms.migrations_django',
    'menus': 'menus.migrations_django',
    'filer': 'filer.migrations_django',
    'djangocms_column': 'djangocms_column.migrations_django',
    'djangocms_flash': 'djangocms_flash.migrations_django',
    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
    'djangocms_inherit': 'djangocms_inherit.migrations_django',
    'djangocms_link': 'djangocms_link.migrations_django',
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_file': 'djangocms_file.migrations_django',
    'djangocms_picture': 'djangocms_picture.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django',
    'djangocms_video': 'djangocms_video.migrations_django',

**Comment by rando305** [comment]
I commented them all  out - and it worked!  Thanks!

**Comment by rando305** [comment]
In the browser, I have and edit button / save and close button.  I was used to a live / draft.  But I don't see the structure - content buttons.  Any suggestions?

**Comment by boydjohnson** [comment]
@rando305 The 'filer':'filer.migrations_django' should be removed. Depending on what version of django-cms you have cms:cms.migrations_django and menus: menus.migrations_django should also be removed. For 3.0 it should be there and for 3.1 it shouldn't.

**Comment by jedie** [comment]
Django/South hasn't made a good job here,isn't it?

**Comment by boydjohnson** [comment]
It's just that South migrations needed to be in one place and Django migrations in another and when Django migrations became more prevalent they switched places.
