### ISSUE TITLE
Logo for djangocms-blog

### ISSUE THREAD

**Issue by motleytech** [nephila/djangocms-blog#108]
Do we have a logo for djangocms-blog?

I am in the process of creating my own blog page and I would like to display the django-cms and djangocms-blog logos.

**Comment by yakky** [comment]
djangocms-blog does not have any logo, I think the django CMS logo would be enough :)
But it would be nice to start a reference to existing djangocms-blog websites: please post yours here

**Comment by motleytech** [comment]
Will do as soon as I have something online.
