### ISSUE TITLE
question: post.meta_description text field

### ISSUE THREAD

**Issue by creimers** [nephila/djangocms-blog#122]
I noticed that in ``model.py``, ``meta_description`` and ``meta_keywords`` are of type ``TextField``, but meta description doesn't render as a Text Field. Instead, meta description renders as ordinary input.

Admitting that I haven't scrutinizing as much as I could: do you deliberately overwrite the widget somewhere? Do you want to keep it that way?

I would prefer if meta description also was a text field.

![bildschirmfoto 2015-06-17 um 19 39 34](https://cloud.githubusercontent.com/assets/6090492/8214310/a1b8f96e-1528-11e5-9ff3-2d844283b097.png)

**Comment by yakky** [comment]
Meta description has been changed to a forms.CharField as 160 is roughly the maximum number of characters that search engines really consider while indexing and show to the user
