### ISSUE TITLE
Save does'nt work in detail view

### ISSUE THREAD

**Issue by retailify** [nephila/djangocms-blog#123]
Hi everybody,
if I save a existend blog post in the detail view of the post, the change will not be saved to the database.

config:
BLOG_USE_PLACEHOLDER = False

Regards
Thomas

**Comment by yakky** [comment]
Could you provide more details about your setup?
No field is saved? Are you editing it using frontend editor or from the plain admin?
If you open the browser inspector, does the network tab returns any error 500?

**Comment by retailify** [comment]
Hi Yakky, sorry for the late reply.
There are 3 possible way to change a blog post in django-cms blog.
1. the django administration interface => everything works fine
2. in the list view of the frontend editor => everything works fine
3. in the detail view of the frontend editor => save problem

In 3. only the Text - field will be displayed in editing mode and text changes will not be saved to the database.

There is no 500error in the network browser.

**Comment by yakky** [comment]
@retailify thanks for the clarification
I can reproduce the error, will update soon

**Comment by yakky** [comment]
@retailify could you test the above PR? It should fix the issue

**Comment by retailify** [comment]
@yakky yes, I'll test the fix

**Comment by retailify** [comment]
@yakky It does'nt work. I've configured 'de' as language.
So I have changed your test and replaced 'en' with 'de'. Then I'll get this error:
AssertionError: u'' != 'ehi text'

**Comment by retailify** [comment]
@yakky The fix does'nt work with 'de' as cms default language

**Comment by yakky** [comment]
I can't reproduce the error, even by setting 'de' as the only language
Have you set PARLER_LANGUAGES in the settings?

Il 04 luglio 2015 15:41:59 CEST, Thomas Meitz <notifications@github.com> ha scritto:
>@yakky The fix does'nt work with 'de' as cms default language
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nephila/djangocms-blog/issues/123#issuecomment-118513266

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by retailify** [comment]
@yakky 
I've set this one in my settings:
PARLER_DEFAULT_LANGUAGE_CODE = 'de'

**Comment by retailify** [comment]
@yakky I'll start a debug session to find the problem...

**Comment by yakky** [comment]
If I recall correctly PARLER_LANGUAGES must also be set

Il 04 luglio 2015 17:31:13 CEST, Thomas Meitz <notifications@github.com> ha scritto:
>@yakky 
>I've set this one in my settings:
>PARLER_DEFAULT_LANGUAGE_CODE = 'de'
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nephila/djangocms-blog/issues/123#issuecomment-118523676

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by yakky** [comment]
@retailify any success with the above PR?
