### ISSUE TITLE
Move to third party category system

### ISSUE THREAD

**Issue by yakky** [nephila/djangocms-blog#125]
It requires  support  for:

 * hierachical structure
 * apphooks config 
 * multilingual

**Comment by petrklus** [comment]
With the current system, I can create loops instead of trees when working with the hierarchy - is this intentional/left like this due to imminent move to another system?

**Comment by yakky** [comment]
Current category system is very minimal, and does not take into account a lot of cases.
Currently there is no multilingual category system that I like, thus it remained a simplistic approach to categories. Actually there is no planned effort to drastically improve it or switch to other systems, but I'm open to contribution

**Comment by avoine** [comment]
Need some help with that? aldryn-categories seems a good fit.

**Comment by yakky** [comment]
It's not suitable as it does not provide support for apphooks config

**Comment by yakky** [comment]
I upodate title and description to outline the requirements for the blog category system

**Comment by jedie** [comment]
Currently it's very circuitous to translate a category, isn't it?

e.g.:

- Create a new Blog Article in language X
- Add a new Category with the "+"-Button (The Category will be created also in language X)
- Use **Save and continue editing**
- Switch to language Y via tab
- Write the translated blog content

Now you have the Blog Article in Language X and Y, but the Category only exist in Language X.
You have to go to **/admin/djangocms_blog/blogcategory/** search for the new created category and translate it...

Have i miss a easy way?!?

**Comment by yakky** [comment]
The "easy" way is to create the categories first :)
The interaction between parler and the admin popup changeform needs improvement, but I'm not sure djangocms-blog is the right place to do that

**Comment by yakky** [comment]
#312 is a fix for this issue, at least in short-medium term.
