### ISSUE TITLE
Haystack search_index

### ISSUE THREAD

**Issue by retailify** [nephila/djangocms-blog#128]
The blog has to be searchable (using Haystack functionality). It's a customer requirement (we have to index the complete website).

Do you have any plans for such an integration?

There are two ways to implement that behaviour. 
a) integration into djangocms-blog
or
b) creation of a new plugin djangocms-blog-search

Which way is your preferred one?

**Comment by yakky** [comment]
Yes, definitely there is a plan for this. I think having a ``search_indexes`` in the core application is the way to go

**Comment by retailify** [comment]
Ok. I think, this is the way to go: 
[Haystack Multilingual Content] (https://django-haystack.readthedocs.org/en/latest/multiple_index.html#multi-lingual-content)

**Comment by yakky** [comment]
There already is an half-baked solution in a WiP branch https://github.com/nephila/djangocms-blog/blob/pyconsei/djangocms_blog/search_indexes.py
Have a look if that works for your

**Comment by retailify** [comment]
I'll give it a try. Thx.

**Comment by yakky** [comment]
Fixed in 0.6.0
