### ISSUE TITLE
Addtoblock not loading custom css or js

### ISSUE THREAD

**Issue by scuerda** [nephila/djangocms-blog#136]
I'm working on a custom base template and I am having difficulty getting my stylesheet to load.

My base.html is as follow:

````html
{% extends CMS_TEMPLATE %}

{% load sekizai_tags staticfiles %}
{% addtoblock "css" %}
  <link href='{% static "djangocms_blog/css/djangocms_blog.css" %}' rel="stylesheet" type="text/css">
{% endaddtoblock %}

{% addtoblock 'js' %}
  <script type="text/javascript" src='{% static "js/libs/pym.js" %}'></script>
{% endaddtoblock %}

{% block meta %}
    {%  if meta %}
        {% include "meta_mixin/meta.html" %}
    {% endif %}
{% endblock meta %}

{% block content %}
<div class="container-fluid app app-blog">

    {% block content_blog %}{% endblock %}
</div>
{% endblock content %}
````

The format of the static tags is the same as in other parts of my cms application. However, the assets are not being loaded. I cannot find any documentation that provides clarification on custom static asset loading. Am I missing something obvious?

Thanks.

**Comment by yakky** [comment]
``addtoblock`` must be defined inside a ``block``: see the warning at https://django-sekizai.readthedocs.org/en/latest/
Closing as it's not related to djangocms-blog

**Comment by scuerda** [comment]
Great. Thanks!
