### ISSUE TITLE
Unusual behavior with the TagAutoSuggest widget in the LatestEntriesForm

### ISSUE THREAD

**Issue by furiousdave** [nephila/djangocms-blog#139]
When initially adding a LatestEntriesPlugin, as expected, only the latest_posts field is required. Subsequently trying to edit the plugin, however, results in a standard "Enter a list of values" error on the tags field. Even adding a tag doesn't seem to remove the error. Removing the widget TagAutoSuggest from forms.py and using the default django field works correctly.

![screenshot from 2015-08-13 11 25 53](https://cloud.githubusercontent.com/assets/153047/9255635/4d56f948-41b0-11e5-9d77-536bc5e47183.png)

Using:
djangocms-blog - develop branch
django-cms==3.1.2
django-taggit==0.16.4
django-taggit-autosuggest==0.2.7

**Comment by yakky** [comment]
@furiousdave thanks for reporting this.
Could you test the above PR, especially with regards to datamigration that moves the tags from the old field to the new one
Which version of Django do you have?

**Comment by furiousdave** [comment]
Thanks a lot, @yakky. That branch does look to have fixed it.

Django==1.8.3

**Comment by yakky** [comment]
Thanks. I'll test the data migration (which is the critical part) on 1.6 then, it will be merged
