### ISSUE TITLE
Permalink type

### ISSUE THREAD

**Issue by vnavascues** [nephila/djangocms-blog#146]
Hi,

I see that is not possible config the settings to change the permalink type as aldryn-newsblog does (I don't want display the dates). 
Any hints to remove dates from URL?
Is this feature in your near-future plans?
In my opinion haystack + multilingual tags + permalink would be great.

Thanks

**Comment by yakky** [comment]
If there is a request for configurable permalink types, why not?
Haystack support is already in the works, for multilingual tags see #109

**Comment by vnavascues** [comment]
Thanks yakky, I'm really looking forward the next version of this plugin.
