### ISSUE TITLE
Unable to config Blog

### ISSUE THREAD

**Issue by vnavascues** [nephila/djangocms-blog#154]
Hi,

I've installed the develop version from the scratch and I'm not able to see the "Edit configuration" tab on the Blog Toolbar. I'm stuck.

Thanks

**Comment by yakky** [comment]
The "edito config" toolbar item is shown when you enter the blog page as it would not be possible to detect the current configuration otherwise.
Alternatively you can use the normal admin to edit the configuration.
Have you created the configuration manually or you used auto configuration?

**Comment by vnavascues** [comment]
Hey! Sorry it was my mistake, you are right, I've been able to create a configuration using both ways.

After that Blog Page crashed and alerted with "bool object isn't in menu_structure" (or something similar, sorry but I'm not able to reproduce it again). Debug points to **menu.py line 28**

if config.menu_structure in (MENU_TYPE_COMPLETE, MENU_TYPE_CATEGORIES):

I don't know if I've restarted the server but it works OK now.

**Comment by yakky** [comment]
@vnavascues this should be solved in 0.6.0 release, right?

**Comment by vnavascues** [comment]
@yakky yes, I don't have it updated to 0.6.1

**Comment by yakky** [comment]
Closing this.
Feel free to reopen if you encounter more issues
