### ISSUE TITLE
Cms plugins not working in 0.6.0 & 0.6.1

### ISSUE THREAD

**Issue by dumbflex** [nephila/djangocms-blog#163]
The cms plugins (archive,categories,tags..) dissapear when upgrading from 0.5.0->0.6.0 or 0.6.1 or with fresh install.

When trying to set the correct appconf for each plugin it reverts always to empty appconf thus always gives an empty plugin.

**Comment by yakky** [comment]
Which django CMS version are you using?

**Comment by dumbflex** [comment]
3.1.3

**Comment by leesolway** [comment]
Replicated on django 1.8.5.

  File "/Users/lee/.virtualenvs/site/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1148, in response_add
    msg_dict = {'name': force_text(opts.verbose_name), 'obj': force_text(obj)}
  File "/Users/lee/.virtualenvs/site/lib/python2.7/site-packages/django/utils/encoding.py", line 92, in force_text
    s = six.text_type(s)
TypeError: coercing to Unicode: need string or buffer, __proxy__ found

**Comment by leesolway** [comment]
Tested and working.. Thanks for the fix.
