### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Orangensaft** [nephila/djangocms-blog#168]
Hi,
since I'm trying to use the newest Version of djangocms-blog, pip spits out an error:

xslt-config: not found

Did I miss something? Do I really have to install Microsoft Visual C++ 10.0 to use djangocms-blog on a Windows machine?

**Comment by yakky** [comment]
xslt-config is required by lxml python package, which -if I recall correctly- is a dependency of htmlib used by django CMS.
Some python packages requires compiler and headers as they contained native code and python code only.
This is not an issues of djangocms-blog per se

**Comment by yakky** [comment]
@Orangensaft have you managed to solve the issue?

**Comment by yakky** [comment]
Closing this to due lack of feedback
@Orangensaft feel free to reopen if you can reproduce this
