### ISSUE TITLE
django-admin-enhancer is not installed as a dependency

### ISSUE THREAD

**Issue by feroda** [nephila/djangocms-blog#174]
I installed djangocms-blog with ```pip install djangocms-blog``` with python2 and then I follow https://github.com/nephila/djangocms-blog/blob/develop/README.rst

**Comment by yakky** [comment]
@feroda ``django-admin-enhancer`` cannot be declared as dependency as it does not work in Django 1.8.
Is the reworded README at above PR more clear on how to use it?
