### ISSUE TITLE
ERROR: fjangocms_blog.LatestPostsPlugin.tags

### ISSUE THREAD

**Issue by AndrewCarre** [nephila/djangocms-blog#176]
Hi,

I am having issues installing django-cms plugin on django 1.8.7/python 3.4.3/django-cms3.2. I am getting the following error when I attempt to syncdb:

ERRORS:
djangocms_blog.LatestPostsPlugin.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
djangocms_blog.Post.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.

Any ideas?

**Comment by yakky** [comment]
Did you add taggit to INSTALLED_APPS?

**Comment by yakky** [comment]
@AndrewCarre did you tried adding taggit as above?

**Comment by yakky** [comment]
Closing this to due lack of feedback
@AndrewCarre feel free to reopen if you have more details
