### ISSUE TITLE
Ordering admin categories 

### ISSUE THREAD

**Issue by Vesli** [nephila/djangocms-blog#177]
Hi,

I wanted to order categories - with adminsortable - as I do on other pages but once in the admin.py, if I pass the class needed for it I have this error : 

> File "/var/www/webapps/blippar_website/app/djangocms_blog/admin.py", line 368, in <module>
    admin.site.register(BlogCategory, BlogCategoryAdmin)
  File "/var/www/webapps/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 104, in register
    self._registry[model] = admin_class(model, self)
  File "/var/www/webapps/lib/python3.4/site-packages/adminsortable2/admin.py", line 73, in __init__
    self.exclude = [self.default_order_field] + self.exclude
TypeError: can only concatenate list (not "tuple") to list

Is it possible to help me on it or add this functionality ?

many thanks

**Comment by yakky** [comment]
Do you define any exclude attribute in your custom admin?

**Comment by Vesli** [comment]
My apologies for the late answer !

Yes, I excluded the parent :
`exclude = ('parent',)`

**Comment by yakky** [comment]
Use ``exclude = ['parent']`` to match exclude type in ``adminsortable2``

**Comment by Vesli** [comment]
Awesome, it works. 
Many thanks yakky !

**Comment by yakky** [comment]
@Vesli great, thanks for your feedback
