### ISSUE TITLE
Disable categories

### ISSUE THREAD

**Issue by sedrubal** [nephila/djangocms-blog#185]
I think I want to disable categories, as I want to only have one news feed for my website (on the start page). Is it possible to get rid of them so that the menus and the complete logic is constructed without categories? Or is this not a use case of djangocms-blog?

I'm thinking of a tree like this:

```
├─ blog posts list (url: `/`)
│   ├── blog post a (url: `/my-first-blogpost`)
│   ├── blog post b (url: `/my-second-blogpost`)
│   └── ... (url: `/...`)
├─ Site: about us or something like that (url: `/about`)
└─ Site: contact (url: `/contact`)
```

Sorry for asking for support, but I could find a documentation and if this is not possible, I wish this for a feature ;)

Thanks...

**Comment by yakky** [comment]
You can use "Posts only" as menu structure in the apphook config. You still have to assign a category to each post, though

**Comment by yakky** [comment]
@sedrubal how about making categories not required again (added to the comment regarding menu structure)

**Comment by sedrubal** [comment]
Yes, I'd be glad if you make categories not required :+1: 

But sorry, what do you mean with apphook config? Or where can I select "Posts only" ?

I hope I don't steal your time...

**Comment by yakky** [comment]
In ``/admin/djangocms_blog/blogconfig/`` you should see a blog configuration model. In the **Layout** section you see **Menu structure** field  with the "Posts only" option
