### ISSUE TITLE
admin-views 'add post' all fieldsets but SEO missing

### ISSUE THREAD

**Issue by creimers** [nephila/djangocms-blog#186]
Django==1.8.4
djangoCMS==3.2.0
djangocms-blog==0.5.0

I'm experiencing strange behavior:

Only the SEO fieldset is visible in the admin add post view. No error logs in the browser console and on the webserver.

I'm inclined to say that this came out of the blue, i.e. not after a particular update or so.

I cannot reproduce the behavior locally.

Any ideas?

<img width="500" alt="bildschirmfoto 2015-12-28 um 15 11 19" src="https://cloud.githubusercontent.com/assets/6090492/12019856/d0ff4d64-ad75-11e5-8142-eb4a1a276f64.png">

**Comment by yakky** [comment]
@creimers with no code changes this may be due to some data which causes a rendering error in the form, which makes the form disappear
What if you dump live data to local?

**Comment by creimers** [comment]
@yakky With live data dumped to local, it is still the same.

**Comment by yakky** [comment]
@creimers so you cannot reproduce locally with live data?

**Comment by creimers** [comment]
@yakky Right, I cannot reproduce locally with live data.

In the meantime I was thinking that someone maybe was messing with user rights, but I can also rule that out.

**Comment by yakky** [comment]
Nope, I'm 100% sure it's an error when rendering the changeform
What the error is, it's a different matter

**Comment by creimers** [comment]
@yakky I might have news on this. 

I noticed that the latest changes to the blog's page were not published, so I hit 'publish'. I get the following error:

```
IntegrityError: duplicate key value violates unique constraint "cms_page_path_518270318703c18f_uniq"
DETAIL:  Key (path)=(000I) already exists.
```
I know I have this kind of problem with my project, similar to #3274 and #3811.

Do you think that could be related to this issue's phenomenon?

**Comment by creimers** [comment]
@yakky I fixed the above error using `manage.py cms fix-tree`. The (only SEO fieldset) still persists.

**Comment by creimers** [comment]
@yakky The greatest and most innovative of all ideas came to my mind: I renewed the virtualenv on the server and everything seems to be working fine now.

**Comment by yakky** [comment]
@creimers sorry of not being of much use here, AFK until now. Glad to see it's solved now, still a mistery why it appeared in the first place :)
