### ISSUE TITLE
Deleting a blog post while on that same post's page results in 404

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#190]
When I'm on a specific post page, ex:

http://127.0.0.1:8000/new-blog/2016/01/29/hello-world/

And then I choose to delete that post via the CMS Menu, the delete is successful, and the page redirects to http://127.0.0.1:8000/new-blog/2016/01/29/hello-world/, which obviously throws a 404.

Would be nice to instead redirect to the top level blog page if you are were currently on a blog post page that you just deleted.

**Comment by yakky** [comment]
@bxm156 which django CMS version  / djangocms blog are you on?
You're supposed to be redirected to the blog list

**Comment by bxm156** [comment]
djangocms-blog==0.6.3

**Comment by yakky** [comment]
@bxm156 confirmed
Will check why the automatic redirection does not work

**Comment by yakky** [comment]
This is a django CMS issues: see divio/django-cms#4977
Closing here.
Thanks for reporting
