### ISSUE TITLE
Suggestion: improve UX when editing new blog post

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#191]
After creating a new empty blog post, it would be nice if there was a more direct way to edit the post content in Content Mode. 

If I click on Edit Post, an fill out some of the post content, it becomes directly editable in the Content Mode, and I can just click on it for editing. However when you create a new blog post, there is no content, and that option isn't directly editable alone. It would be nice if there was some default content that shows only under the following conditions.

1. The post is empty
2. We are in edit mode.

I sort of imagine creating a new, empty blog post, and then going directly to that page and clicking on some text like "This is the post content. Click here to edit me!"

**Comment by yakky** [comment]
You can use the django CMS default plugins configuration (http://django-cms.readthedocs.org/en/develop/reference/configuration.html#cms-placeholder-conf) to add text (or whatever content you'd want) to the newly created plugins:

    'post_content': {
        'default_plugins':
            {
                'plugin_type': 'TextPlugin',
                'values': {
                    'body':'<p>Lorem ipsum dolor sit amet...</p>',
                },
            },
        ],
    },

**Comment by bxm156** [comment]
Cool, I'll do that!
