### ISSUE TITLE
Blog posts disappear

### ISSUE THREAD

**Issue by Brandl** [nephila/djangocms-blog#197]
I have this really strange bug, where blog posts disappear after I log out.
They come back, when I create a new post, but then disappear again after logout.
![screen shot 2016-02-07 at 20 38 32](https://cloud.githubusercontent.com/assets/3877188/12874751/c6330774-cdda-11e5-95f2-e7d9b0639a0e.png)

Also there is this permanent error preventing me from viewing the posts in django admin:
![screen shot 2016-02-07 at 20 39 41](https://cloud.githubusercontent.com/assets/3877188/12874759/0086bfd8-cddb-11e5-838a-44b5b1056d14.png)
![screen shot 2016-02-07 at 20 41 05](https://cloud.githubusercontent.com/assets/3877188/12874768/3e6a0ba2-cddb-11e5-9de2-f8e63b34f3d3.png)

Pip freeze:
```
Django==1.9.1
Django-Select2==4.3.2
Pillow==3.1.0
URLObject==2.4.0
Unidecode==0.04.19
YURL==0.13
aldryn-apphooks-config==0.2.6
aldryn-boilerplates==0.7.4
aldryn-common==1.0.0
aldryn-search==0.2.10
argparse==1.4.0
cmsplugin-filer==1.0.1
defusedxml==0.4.1
dj-database-url==0.3.0
django-allauth==0.24.1
django-appconf==1.0.1
django-appdata==0.1.5
django-avatar==2.2.1
django-classy-tags==0.7.1
django-cms==3.2.1
django-filer==1.1.1
django-formtools==1.0
django-haystack==2.4.1
django-meta==0.3.1
django-meta-mixin==0.2.1
django-mptt==0.8.0
django-parler==1.6
django-polymorphic==0.8.1
django-reversion==1.10.1
django-sekizai==0.9.0
django-sortedm2m==1.1.1
django-spurl==0.6.4
django-standard-form==1.1.1
django-taggit==0.18.0
django-taggit-autosuggest==0.2.8
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.0
djangocms-admin-style==1.0.9
djangocms-apphook-setup==0.1.2
djangocms-blog==0.6.3
djangocms-column==1.6.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-installer==0.8.5
djangocms-link==1.7.1
djangocms-style==1.6.0
djangocms-text-ckeditor==2.8.1
easy-thumbnails==2.3
html5lib==0.9999999
lxml==3.5.0
oauthlib==1.0.3
python3-openid==3.0.9
pytz==2015.7
requests==2.9.1
requests-oauthlib==0.6.0
six==1.10.0
tzlocal==1.2
```

**Comment by yakky** [comment]
By default posts are not published. Can this be he cause?
WRT the second error, I confirm it. It does not happens in django 1.8, I'll check if it's a blog issue or a parler one

**Comment by yakky** [comment]
parler bug opened for changelist error: https://github.com/edoburu/django-parler/issues/117

**Comment by Brandl** [comment]
Ok, going into edit mode they show again.
But there is no button to publish.

**Comment by Brandl** [comment]
Also they show up in menu and there is no indication that their are not yet pubished, which is counter intuitive.

**Comment by yakky** [comment]
There is the 'publish' flag in the post changeform. As of now it's not possible to publish objects like the django CMS pages

**Comment by yakky** [comment]
djangocms-blog adopts the django CMS behavior: in draft mode,  unpublished content is shown with no specific highlight to match the view they will have once published. In the changelist you can see the publish status

**Comment by yakky** [comment]
Issue with Django 1.9 has been fixed in parler (still not released, but merged)

**Comment by yakky** [comment]
@Brandl parler 1.6.1 which solves issue with Django 1.9 has been released.
Thanks for your feedback!
