### ISSUE TITLE
Category menu item selection when in PostDetail view while menu only shows categories

### ISSUE THREAD

**Issue by skirsdeda** [nephila/djangocms-blog#204]
@yakky Initial menu implementation had a NavigationModifier which selected category menu item according to post's categories which solved this particular use case. After menu redesign it's gone and proper category is only selected if posts are shown in menu as well (which is not a viable option in my case since I have ~1000 blog posts).

**Comment by yakky** [comment]
You can set 'Categories only' as menu type and this only loads categories into the menu

**Comment by skirsdeda** [comment]
@yakky Yes, but when you go into post, no category will be selected in menu. This is because toolbar object is set to Post, not category, also category menu item urls don't match up with the beginning of post urls even if you use category based permalink. So the only way is a NavigationModifier AFAIK.

**Comment by yakky** [comment]
I see. Check if #206 fixes your issue
I reintroduced the menu modifier with changes with respect to the old one

**Comment by skirsdeda** [comment]
@yakky Terrific! Works as expected.

**Comment by yakky** [comment]
Great. Waiting for the tests to pass before merging
