### ISSUE TITLE
Using blog on homepage results in 404 for all other pages.

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#214]
When I'm using the Django CMS blog app on my Homepage (/), all other pages I create result in a 404. If I move the blog application to a page like /blog, then my other pages show up. 

If it matters, I have BLOG_AUTO_SETUP = False, cause I wanted to set it up the blog myself.

djangocms_blog 0.6.3
cms 3.2.1
django 1.8.9

**Comment by yakky** [comment]
What URL layout have you set in the apphooks configuration?

**Comment by bxm156** [comment]
Sorry, i'm relatively new to this, where would i find that? I don't see anything resembling a url layout in the apphooks config. (I'm looking at the "Edit Configuration menu").

So my goal is to have 
/ - Home page and Blog Page
/ 2016/03/ .... - for where my posts are
/ about / - a django cms page
/ contact / - a django cms page
etc.


Perhaps that is not possible though. In the meantime. I have worked around it by create a page called /blog, and removed it from the menu. Then, I put the latests posts plugin on my homepage. Now everything works pretty well.

**Comment by yakky** [comment]
@bxm156 you can achieve the above layout by setting the followin settings in the project ``settings.py``::

    BLOG_PERMALINKS = (
        ('full_date', _('Full date')),
        ('short_date', _('Year /  Month')),
        ('category', _('Category')),
    )
    BLOG_PERMALINKS_URLS = {
        'full_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$',
        'short_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>\w[-\w]*)/$',
        'category': r'^(?P<category>\w[-\w]*)/(?P<slug>\w[-\w]*)/$',
    }

The removed permalink urlconf swallows any page defined as child of the blog page (in your example the root page)
I'll document this case in the readme for easier setup
