### ISSUE TITLE
When django cms page publised filter by category not working in Last entries plugin

### ISSUE THREAD

**Issue by rt-em** [nephila/djangocms-blog#216]
I want to add on the webpage all blog posts related to one specific category. When I'm using the Last entries plugin I can choose categories from the list of available categories. Everything works great until I push "publish changes" . When CMS page is published I see all blog posts insted of posts related to category that I chose in plugin settings.

Best regards,
Artem Litvinov

**Comment by yakky** [comment]
@rt-em this is a bug in version 0.6.3
You can test djangocms-blog==0.7.0b1 which shold fix the issue

**Comment by yakky** [comment]
Fixed in #212
