### ISSUE TITLE
Option to customize urlpatterns

### ISSUE THREAD

**Issue by Nekmo** [nephila/djangocms-blog#221]
I think it would be interesting if PERMALINK_URLS could overwrite the default urls urlpatterns.

For example, if I define "posts-archive" in permalinks URLS, it may overwrite the default post-archive urlpattern.

**Comment by yakky** [comment]
This is already supported. Just define your own BLOG_PERMALINKS and BLOG_PERMALINKS_URLS in settings.py (see https://github.com/nephila/djangocms-blog#attaching-blog-to-the-home-page for an example)

**Comment by Nekmo** [comment]
Thanks.
