### ISSUE TITLE
TypeError: $(...).autoSuggest is not a function

### ISSUE THREAD

**Issue by jesusjl** [nephila/djangocms-blog#222]
When i try to create a post no CKEDITOR and javascript error TypeError: $(...).autoSuggest is not a function when using django 1.6.11 , django-cms==3.1.2 and djangocms-blog==0.6.0 . I have tried with different versions but no luck. Also typeError: u is null in ckeditor.js

Probably a jquery confict with other apps ? Please help

**Comment by jesusjl** [comment]
Fixed, building a new project from scratch and cleaning and installing apps one by one in my development project helped.

**Comment by yakky** [comment]
Sounds like a static files deployment issue. glad you solved

**Comment by jesusjl** [comment]
Thank you yakky
