### ISSUE TITLE
Why not CMS Plugins shown in the text editor?

### ISSUE THREAD

**Issue by Nekmo** [nephila/djangocms-blog#225]
I have a newly installed my environment and plugins button is not displayed. In other plugins as "Text" button shown.

![report](https://cloud.githubusercontent.com/assets/740106/14223919/92885f20-f88a-11e5-890e-f74f5c799a74.png)

**Comment by Nekmo** [comment]
I have enabled plugins:

![report2](https://cloud.githubusercontent.com/assets/740106/14223938/68cc22c4-f88b-11e5-83dc-cf1335a88710.png)

**Comment by yakky** [comment]
Abstract field is just a normal rich-text area, it cannot contains plugins. It's just an area for the overview content. When you create the article, you'll be directed to the blog post detail view which will allow you to add plugins (and plugins in the text plugin) to the placeholder, which is for the main content area.

**Comment by Nekmo** [comment]
OK, I understand :) What I really need is to include images in my posts. I could do it from the structure view, but it seems excessive. Why do I need to do this to include images?

I've been looking and ckeditor can include images as base64. I do not want this because it slows down the loading of the page. I saw that Nephila is doing a module to include Filer in CKEditor:

https://github.com/nephila/django-ckeditor-filebrowser-filer

But it is not yet ripe. Is there any other solution?

**Comment by yakky** [comment]
I need to release an updated version of https://github.com/nephila/django-ckeditor-filebrowser-filer actually, I might be able to do this during the weekend.
Though, the best and more flexible way to add images and have complete control over the text of your blog post is using plugins in structure mode.
Eventually you can use default plugins to have a temporary test automatically added to your blog post whenever you create a post: you can thus just double click on the auto-added plugin and edit it, add images or whatever, straight from the content mode: see https://github.com/nephila/djangocms-blog/issues/191#issuecomment-177834750 for how to configure it

**Comment by Nekmo** [comment]
Cool :D I understand that this is something temporary, but it would be possible to edit the text from the article creation window?

Maybe it is a problem that the article (and pk) is not yet available when creating a new article. It could perhaps temporarily created when the article has a title?

**Comment by yakky** [comment]
This is not doable in the admin exactly for the non-existing pk reason. This is a limitation of the django CMS API thus the blog can't do much.
What we can do is to extend the wizard to include a textarea that will be translated into a text plugin, but it won't be possible to add images there, until the post has been created.

**Comment by Nekmo** [comment]
I know it's not pretty, but the article could be created when the user leaves the title input (using Javascript) and load the TextPlugin by Ajax at the time... but it's nasty :/

Thank you for your help and for responding so quickly. 

You have solved my doubt and you can close the report.

**Comment by yakky** [comment]
Thanks for the discussion and input
