### ISSUE TITLE
Menu not following options

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#230]
I am configuring the blog page to not show any children using the following option:

![image](https://cloud.githubusercontent.com/assets/1115667/14442926/933fc868-003c-11e6-8344-748f97a53b8e.png)

However, I am still seeing categories as children of the "Blog" page. No matter what I select in the app config above, the output does not change.

**Comment by yakky** [comment]
@petrklus whichi version are you using?

**Comment by yakky** [comment]
@petrklus it's most likely django CMS menu caching in action. What if you clear the cache (or let it expire?)

**Comment by yakky** [comment]
@petrklus could you confirm that above PR fix your issue?
It's actually quite easy to clear the menu cache if that field is changed.

**Comment by petrklus** [comment]
Sorry for the delay in replying - you are right, it was caching issue. Working as intended now!

**Comment by yakky** [comment]
version 0.8 will be released with automatic cache clearing, thanks for reporting
