### ISSUE TITLE
"Permission denied" when editing other placeholder items

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#240]
I can edit sidebar/other placeholder contents on the main page of the blog as expected. However, when I try to do the same from, for example, a post view, I get the following error:

![image](https://cloud.githubusercontent.com/assets/1115667/14950265/bc5a0974-1050-11e6-94b3-6bfdabfce40f.png)

Is there something odd with my setup or is this expected behaviour? If it's the latter, could the error message be amended? I suspect this will be quite confusing for our users.

**Comment by yakky** [comment]
@petrklus for placeholder outside the main blog content you must use static placeholders, as normal placeholders are not supported in apphooked page by django CMS

**Comment by petrklus** [comment]
Could you please elaborate how this should be used? At the moment, I've got a sidebar placeholder on the main blog page - which I can edit through the main blog page and they work across board. The only issue I am having is that it's not obvious for editors that they need to go back to the main blog page to do the edits.

Is the above wrong setup? Should I be using static placeholders for the sidebar? If so, how do I ensure that they are there only for blog (I am using same sidebar placeholder on other content pages).

**Comment by yakky** [comment]
yes, just use static_placeholders for sidebar. it works on the main blog page because it happends to be a cms page too, but it won't work on the internal view because they are not cms pages see an example here https://gist.github.com/yakky/56a937a1c8d1d8c74f1b43c51c771008

**Comment by petrklus** [comment]
thank you @yakky !

**Comment by yakky** [comment]
Closing this
