### ISSUE TITLE
CMS plugins for blog text

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#244]
I (and our users) very much prefer using the abstract + text for specifying blog posts. Is there any way to make the text editor match the default Django CMS one, including the CMS plugins? Would this be something on the radar for the future implementation?

**Comment by yakky** [comment]
Due to restrictions in django CMS plugins are only available in plugins added to the placeholderfield. This is not going yo change soon (if ever)
Other than that with 'match the default cms text editor, you mean in terms of interface configuration (buttons, rows etc)?

**Comment by petrklus** [comment]
I am mainly after the YouTube and link plugins to allow linking to content pages + insertion of videos.

**Comment by petrklus** [comment]
One more question @yakky  - I know it sounds "hacky" but really the main reason I am asking is that it's a bit tricky to explain to casual users that they need to save the blog post and then go to its page to edit the full post - would there be a way to automatically put in a text plugin into the placeholder and render that in the blog post view?

**Comment by yakky** [comment]
@petrklus it's not hacky at all, and actually the supported solution: see https://github.com/nephila/djangocms-blog/issues/191#issuecomment-177834750
It's a supported feature provided by django CMS (see ``default_plugins`` at paragraph http://django-cms.readthedocs.io/en/latest/reference/configuration.html#cms-placeholder-conf for reference )

**Comment by yakky** [comment]
@petrklus closing this. Thanks for contributing
