### ISSUE TITLE
Pagination settings are confusing

### ISSUE THREAD

**Issue by frnhr** [nephila/djangocms-blog#245]
I'm creating my first app with djangocms-blog and might be missing something, but I'm finding the pagination settings strange. Here is why.

Number of posts per page on the main post listing is configured by the app instance. That is perfectly fine. But the other post listings (category, tag, archive, etc.) should follow the same principle. Currently, thet are only configured via `settings.py`.

It seems to me that usually the designs of the main listing and other listings are more-or-less similar, so perhaps they should use the same config (i.e. the app instance). Or alternatively, perhaps we should add another config field to the app instance, so that there are two pagination numbers:

 * posts per page on main page
 * posts per page on other listings (category, post, archive, etc.)

We can obviously also have a separate field for each listing. Would that be an overkill?

I can prepare a pull request if this is something that would be accepted. If so, which option?

**Comment by frnhr** [comment]
P.S.
The help_text on the existing field on app instance says 

> When paginating list views, how many articles per page?

It seems like it was intended for all listings, not just the main page.

**Comment by yakky** [comment]
@frnhr thanks for reporting this. It's not confusing, it's just a bug :)
I'd say we can just use the same setting, and just move ``get_paginate_by`` from ``PostListView`` to ``BaseBlogView`` and remove the ``paginate_by`` attribute from the other classes.
What do you think?

**Comment by frnhr** [comment]
I thought exactly the same.

Also noticed that a few more attributes could also be moved from `PostListView` to `BaseBlogView`, such as `model`, `base_template_name`, `context_object_name` and also `context['TRUNCWORDS_COUNT']` from `get_context_data()`. But that's just cosmetics.

**Comment by yakky** [comment]
@frnhr a nice cosmetic cleanup anyway

**Comment by yakky** [comment]
@frnhr are you still up for a PR? :gift:

**Comment by frnhr** [comment]
@yakky sure, coming to a repository near you...

**Comment by yakky** [comment]
@frnhr awesome!

**Comment by frnhr** [comment]
The PR is ready. It seemed like a good idea to add a base class for the list views, since detail view doesn't need the pagination stuff.

**Comment by yakky** [comment]
Agree

**Comment by yakky** [comment]
Fixed in #246 
Fix released in 0.8.0b8
