### ISSUE TITLE
Question: best way to add custom fields to Post model?

### ISSUE THREAD

**Issue by frnhr** [nephila/djangocms-blog#247]
What is the best way to set something like a "post type" for individual posts? For example, if I would like some posts to render (very) differently. Templates can be overridden easily, but I don't see a (good) way of adding fields to post model.

**Comment by yakky** [comment]
There is pluggable way to add fields.
But you can create a model with a OneToOne field to the post and override the admin adding the inline to handle it

**Comment by frnhr** [comment]
Ah, inlines! Why didn't i think of that! I sometimes forget that the whole CMS is actually just the admin... Anyways, thanks!
