### ISSUE TITLE
Improve "published" field visibitility

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#248]
Based on user feedback, we are looking at improving visibility / ease of use of the publish checkbox. At the moment, it seems to be slotted into the post editor.

I think it may not be a bad idea to add a shorthand to it into the blog menu, to easily publish posts without fishing for the checkbox.

**Comment by yakky** [comment]
Actually there should be the publish button in the toolbar just like the "publish page" one (https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/cms_toolbar.py#L37)
I'll investigate this

**Comment by yakky** [comment]
@petrklus indeed, it's there. If you go on an unpublished article, you will se a "Publish article now" button that will publish the article you're on

**Comment by petrklus** [comment]
@yakky was this added recently? I am on 0.6.3 and cannot see a button like this.

**Comment by yakky** [comment]
Yes, it's been added in 0.7
It looks like this
![button](https://cloud.githubusercontent.com/assets/714711/15042566/5fc08c34-12c5-11e6-9eea-b8a882c0abaf.png)

**Comment by petrklus** [comment]
@yakky sweet! Will update. To double-check - is it a drop-in replacement?

**Comment by yakky** [comment]
@petrklus yes, it's completely compatible

**Comment by petrklus** [comment]
@yakky one more question - when is the 0.8 going to be officially released?

**Comment by yakky** [comment]
Mid next week. 0.8b8 is likely identical to the final release, minus some translation updates I will pull just before the release
