### ISSUE TITLE
Migration 0014 breaks things

### ISSUE THREAD

**Issue by yunmanger1** [nephila/djangocms-blog#251]
https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/migrations/0014_auto_20160215_1331.py#L24

This implies that all plugins that are not bound to some app_config will be assigned to an arbitrary BlogConfig. In my case I have several pages bound to BlogApp on different sites. After migration plugins from one site were bound to app config used on another site.

**Comment by yakky** [comment]
That migration applies the only available strategy to mass migrate to the apphook based setup.
Any other strategy will involve a lot more work after upgrading the blog.
After applying the migrations you have to create dedicated apphooks and you can easily assign the plugins and posts accordingly to the site /appconfig they belong:

        config1 = BlogConfig.objects.get(namespace='apphook_site_1')
        config2 = BlogConfig.objects.get(namespace='apphook_site_2')
        configs = {
            1: config1,
            2: config2,
        }
        for model in (BlogCategory, GenericBlogPlugin, LatestPostsPlugin, AuthorEntriesPlugin):
            for item in model.objects.filter(app_config__isnull=True):
                if item.page:
                      item.app_config = configs[item.page.site_id]
                      item.save()

if item.page does not exists (e.g.: plugin is in a pleholderfield) you have to figure out yourself how to apply the correct apphookconfig

**Comment by yakky** [comment]
This will be closed in one week as no longer reproducible

**Comment by yakky** [comment]
Closing as per above
