### ISSUE TITLE
'all_languages_column' error after updating from 0.6.x to 0.7

### ISSUE THREAD

**Issue by estoeckli** [nephila/djangocms-blog#253]
Hi,

I've just updated from 0.6.x to 0.7 and always received the following error:

`  File "/venv/lib/python2.7/site-packages/djangocms_blog/admin.py", line 248, in <module>
    admin.site.register(Post, PostAdmin)
  File "/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 106, in validate
    validator.validate(cls, model)
  File "/venv/lib/python2.7/site-packages/django/contrib/admin/validation.py", line 25, in validate
    getattr(self, m)(cls, model)
  File "/venv/lib/python2.7/site-packages/django/contrib/admin/validation.py", line 251, in validate_list_display
    % (cls.__name__, idx, field, cls.__name__, model._meta.object_name))

ImproperlyConfigured: PostAdmin.list_display[4], u'all_languages_column' is not a callable or an attribute of 'PostAdmin' or found in the model 'Post'.
`

After debugging the error I was able to fix it by updating django-parler from 1.2.x to 1.6.3.
This might be useful to mention somewhere in the docs.

**Comment by yakky** [comment]
@estoeckli that's strange, as version 0.7 has a versioned dependency on ``parler>1.5`` (https://github.com/nephila/djangocms-blog/blob/master/setup.py#L30) which should ensure the proper parler version is installed when upgrading

**Comment by yakky** [comment]
This will be closed in one week as no longer reproducible

**Comment by yakky** [comment]
Closing as per above
