### ISSUE TITLE
How to edit the content

### ISSUE THREAD

**Issue by Luindil** [nephila/djangocms-blog#258]
Hei there,

i am trying to use the djangocms-blog. But have come to fundamental difficulties. When creating a new post i can edit the title and the abstract, however, there is no field for the content/blog_content/blog_text.

Why is this? Did I forget something during installation?

**Comment by Luindil** [comment]
i just realized that the blog is working like normal pages and i just can add anything like text field, images etc. sorry for my lack of understanding...

**Comment by yakky** [comment]
@Luindil if you think this must be further clarified, do not hesitate to provide feedback

**Comment by lggwettmann** [comment]
Oh that would be good to explain or put up some links in the documentation.. I have the same issue and confusion.

**Comment by fsbraun** [comment]
@lggwettmann Have you checked if you have a placeholder "post_content" if you open structure mode. There you can drop a text plugin (or any other) and add content. See image below. 

<img width="1080" alt="Bildschirmfoto 2019-05-11 um 07 43 07" src="https://user-images.githubusercontent.com/16904477/57565594-fb631300-73c0-11e9-88b0-ca082d42f098.png">

Does that clarify?

**Comment by lggwettmann** [comment]
Hey @fsbraun ,

thanks so much for the fast answer. After a while I figured out it should have something to do with templating and placeholders, but still not how to solve it.

I did not have such a placeholder. I created it myself in my django-cms main template, but all the content/plugins I drop in this placeholder gets shown on all blog pages..?

Also I wondered how to change the base.html-template where djangocms-blog extends off. My basic templates are named differently and would be nice just to set the name somewhere instead of having to create a base.html just for djangocms-blog.

**Comment by fsbraun** [comment]
@lggwettmann 

The djangocms-blog templates live in a template folder named ``djangocms_blog``. The placeholder for the blog detail view lives in ``post_detail.html``. Does your ``djangocms_blog/post_detail.html`` template contain the following lines?

        {% if post.app_config.use_placeholder %}
            <div class="blog-content">{% render_placeholder post.content %}</div>
        {% else %}
            <div class="blog-content">{% render_model post "post_text" "post_text" %}</div>
        {% endif %}

This should render the placeholder. I did start with the provided templates but I created copies in my project's file tree and step by step adapted the templates for my needs. Nevertheless the above core never changed.

**Comment by lggwettmann** [comment]
Thanks for the answer, @fsbraun. I highly appreciate it. 

I deleted my custom base.html and did not use any custom templates for djangocms_blog. I configured a base.html (defined in CMS_TEMPLATES) with this content:
```
{% load cms_tags sekizai_tags %}
<html>
    <head>
        <title>{% page_attribute "page_title" %}</title>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% placeholder "content" %}
        {% render_block "js" %}
    </body>
</html>
```
And all content plugins dropped into the post_content placeholder appeared on all blog pages. I deleted the base.html and implemented the above placeholders into my projects main template 'layout.html', and defined it in CMS_TEMPLATES ... and magically content dropped in the post_content placeholders only appears on the respective blog pages. I must have either something missed/done wrong - or there is a bug.

Really weird and super confusing. Thanks for your hints and fast help.

**Comment by fsbraun** [comment]
@lggwettmann Please check the documentation on how the blog templates work: https://djangocms-blog.readthedocs.io/en/latest/features.html#templates 

Your ``base.html`` should contain a block called ``content``, e.g., 

    {% load cms_tags sekizai_tags %}
    <html>
        <head>
            <title>{% page_attribute "page_title" %}</title>
            {% render_block "css" %}
        </head>
        <body>
            {% cms_toolbar %}
            {% block "content" %} {# <--- important #} 
                {% placeholder "content" %}
            {% endblock "content" %}
        {% render_block "js" %}
      </body>
    </html>
  
The ``content`` block is replaced in djangocms-blog's ``djangocms_blog/base.html`` which in turn is the base for all djangocms-blog's templates. This will remove the placeholder from your blog pages and replace them by the blog content.

**Comment by lggwettmann** [comment]
Oh THAT is the important part? I read through the documentation multiple times, but it's a very confusing one. And then there are placeholders and I thought these are the important ones for Django CMS. So I didn't pay attention to the blocks. My normal layout.html does have a content-block by coincident...

Thanks for your help on that @fsbraun - Super helpful and thanks for your patience with a newbie.
