### ISSUE TITLE
Upgrading to 0.7.0 broke blog thumbnails options

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#260]
I had added a Thumbnail Option in the Django Admin interface in 0.6.3,( for Cmsplugin_Filer_Image) and on my blog posts, i had my image set with it as the thumbnail option. When I upgraded to 0.7.0, my thumbnails disappeared, when I looked at the post editor, the drop down selectors for the thumbnail options are now empty. (MAIN IMAGE THUMBNAIL, MAIN IMAGE FULL). Before the upgrade, they showed a list of Thumbnail Option models.

I tried adding a new thumbnail option, but it doesn't show up in the dropdown either

The thumbnail images don't render. If I edit the post and then save it again, the thumbnail then shows, it uses the default 120x120 (or whatever its set to the in settings), since there is no other option in the dropdown.

**Comment by bxm156** [comment]
When I tried to delete the thumbnail option, I found that i couldn't. I see in the error log, that it won't let me delete it because its being referenced by posts in the db as a key.

While that is somewhat expected, it begs the question, why doesn't it show in the dropdown.



Also, when trying to delete it, it just shows an empty Admin interface page, it doesn't actually give an error, I had to look at the logs to find it. It would be nice to bubble that up to the user

```
IntegrityError: update or delete on table "cmsplugin_filer_image_thumbnailoption" violates foreign key constraint "D5f70eada6e688daae6be1de2e35fbab" on table "djangocms_blog_post" DETAIL: Key (id)=(2) is still referenced from table "djangocms_blog_post". 
```

**Comment by yakky** [comment]
@bxm156 which filer / cmsplugin_filer version was installed prior and after upgrade?

**Comment by bxm156** [comment]
Before & After:
cmsplugin-filer==1.0.1
django-filer==1.1.1

**Comment by bxm156** [comment]
I see tables for both filer_thumbnailoption and cmsplugin_filer_image_thumbnailoption.

cmsplugin_filer_image_thumbnailoption has the rows
filer_thumbnailoption is empty

**Comment by bxm156** [comment]
So I discovered the Filer thumbnailOption model in the Admin interface. I added a new option, and it shows in the drop down. I click the save button ,and django says it saved the change succcessfully, however the option doesn't get set. I see this in the logs

"IntegrityError: insert or update on table "djangocms_blog_post" violates foreign key constraint "D8801706e0cb92694308cd45314b19c9" DETAIL: Key (main_image_thumbnail_id)=(1) is not present in table "cmsplugin_filer_image_thumbnailoption"."

**Comment by bxm156** [comment]
I just realized my build process bumped django-filer to 1.2.0, I think it was pulling it based on other packages, and thus it wasn't explicitly pinned.

**Comment by bxm156** [comment]
I just realized my build process bumped django-filer to 1.2.0, I think it was pulling that version based on other packages dependencies, I hadn't explicitly pinned it. .That would explain why the new table shows up. And the djangocms-blog code is importing the new model. 

I think the culprit is the cmsplugin_filer setup.py as of v1.0.1. 
https://github.com/divio/cmsplugin-filer/blob/d977cbc61a00189801719745c20961cef0b5adb2/setup.py
 "django-filer >= 1.0.0",


I'm not sure how easily it is to go backwards in migration, so I guess i will have to wait for the new cmsplugin version to be released which will support 1.2.0, and perform those new migrations i see

**Comment by yakky** [comment]
@bxm156 yeah, cmsplugin filer compatible with the filer thumbnailoption is still not available on pypi. that said, the post should handle this gracefully and use the new thumnailoptions
Let me do a quick check, I can eventually push a quick fix for 0.7 branch

**Comment by yakky** [comment]
@bxm156 the best option is to downgrade to filer 1.1
You can first revert the migrations: ``python manage.py filer 0002`` and then downgrade to filer 1.1

**Comment by yakky** [comment]
#262 should fix the issue for 0.8

**Comment by yakky** [comment]
@bxm156 current beta should handle the migration, but I'm trying to figure out a more step-by-step procedure

**Comment by yakky** [comment]
@bxm156 version 0.8.5 should work correctly across all combination of filer / cmsplugin-filer

**Comment by yakky** [comment]
This will be closed in one week as no longer reproducible

**Comment by bxm156** [comment]
thanks for the help! i was able to upgrade to the latest cmsplugin filer, 1.1.0 and ran the migrations, it worked

**Comment by yakky** [comment]
@bxm156 thanks for the feedback.
