### ISSUE TITLE
New German locale?

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#264]
I could volunteer an update of the German locale ("de"). Whom can I send the django.po file?

**Comment by yakky** [comment]
@fsbraun that would be great! The best way is to join the transifex https://www.transifex.com/nephila/djangocms-blog/dashboard/ and contribute the translation from there for a better integration with language updates

**Comment by yakky** [comment]
@fsbraun thanks for joining! I'll pull update translations before release

**Comment by fsbraun** [comment]
Thanks! Appreciate it! Fabian
