### ISSUE TITLE
django-cms 3.3.0 break compatibility?

### ISSUE THREAD

**Issue by jsma** [nephila/djangocms-blog#265]
I upgraded a site from django-cms==3.2.5 to v3.3.0 and am running the develop branch of djangocms_blog a6ef74cfdd7c80e5aebd5c558f7d32ba080c931c. After the upgrade, when I tried to add a plugin to the 'Post_Content' placeholder it gave the following error:

    File "../env/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
      149.                     response = self.process_exception_by_middleware(e, request)

    File "../env/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
      147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

    File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      149.                     response = view_func(request, *args, **kwargs)

    File "../env/lib/python3.4/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
      57.         response = view_func(request, *args, **kwargs)

    File "../env/lib/python3.4/site-packages/django/contrib/admin/sites.py" in inner
      244.             return view(request, *args, **kwargs)

    File "../env/lib/python3.4/site-packages/django/views/decorators/clickjacking.py" in wrapped_view
      39.         resp = view_func(*args, **kwargs)

    File "../env/lib/python3.4/site-packages/cms/admin/placeholderadmin.py" in add_plugin
      261.         response = plugin_admin.add_view(request)

    File "../env/lib/python3.4/site-packages/djangocms_text_ckeditor/cms_plugins.py" in add_view
      64.                 request, form_url, extra_context

    File "../env/lib/python3.4/site-packages/cms/plugin_base.py" in add_view
      355.                 request, form_url, extra_context)

    File "../env/lib/python3.4/site-packages/django/contrib/admin/options.py" in add_view
      1437.         return self.changeform_view(request, None, form_url, extra_context)

    File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapper
      67.             return bound_func(*args, **kwargs)

    File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
      149.                     response = view_func(request, *args, **kwargs)

    File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in bound_func
      63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

    File "/usr/lib/python3.4/contextlib.py" in inner
      30.                 return func(*args, **kwds)

    File "../env/lib/python3.4/site-packages/django/contrib/admin/options.py" in changeform_view
      1367.         ModelForm = self.get_form(request, obj)

    File "../env/lib/python3.4/site-packages/djangocms_text_ckeditor/cms_plugins.py" in get_form
      85.                 self.placeholder.slot,

    Exception Type: AttributeError at /admin/djangocms_blog/post/add-plugin/
    Exception Value: 'NoneType' object has no attribute 'slot'

Additionally, when I tried to downgrade back to 3.2.5, I attempted to undo the migration applied by 3.3.0 (0015) to get the database back to the correct 3.2.5 state. However, this triggered uninstalling all djangocms_blog migrations, which means it deleted all the blog data as well (fortunately there was only a single test post). Is this due to using `'__latest__'` as a dependency in the initial migration?

Aside from the data loss, once I downgraded to 3.2.5 and re-ran the blog migrations, editing the placeholder worked as expected.

**Comment by yakky** [comment]
@jsma have you updated to djangocms-text-ckeditor 3.0 also?

**Comment by yakky** [comment]
Have you updated the text editor as well?

On 27 May 2016 09:34:51 CEST, John-Scott Atlakson <notifications@github.com> wrote:
>I upgraded a site from django-cms==3.2.5 to v3.3.0 and am running the
>develop branch of djangocms_blog
>a6ef74cfdd7c80e5aebd5c558f7d32ba080c931c. After the upgrade, when I
>tried to add a plugin to the 'Post_Content' placeholder it gave the
>following error:
>
>File "../env/lib/python3.4/site-packages/django/core/handlers/base.py"
>in get_response
>149.                     response =
>self.process_exception_by_middleware(e, request)
>
>File "../env/lib/python3.4/site-packages/django/core/handlers/base.py"
>in get_response
>147.                     response = wrapped_callback(request,
>*callback_args, **callback_kwargs)
>
>File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in
>_wrapped_view
>149.                     response = view_func(request, *args, **kwargs)
>
>File
>"../env/lib/python3.4/site-packages/django/views/decorators/cache.py"
>in _wrapped_view_func
>      57.         response = view_func(request, *args, **kwargs)
>
>File "../env/lib/python3.4/site-packages/django/contrib/admin/sites.py"
>in inner
>      244.             return view(request, *args, **kwargs)
>
>File
>"../env/lib/python3.4/site-packages/django/views/decorators/clickjacking.py"
>in wrapped_view
>      39.         resp = view_func(*args, **kwargs)
>
>File "../env/lib/python3.4/site-packages/cms/admin/placeholderadmin.py"
>in add_plugin
>      261.         response = plugin_admin.add_view(request)
>
>File
>"../env/lib/python3.4/site-packages/djangocms_text_ckeditor/cms_plugins.py"
>in add_view
>      64.                 request, form_url, extra_context
>
>File "../env/lib/python3.4/site-packages/cms/plugin_base.py" in
>add_view
>      355.                 request, form_url, extra_context)
>
>File
>"../env/lib/python3.4/site-packages/django/contrib/admin/options.py" in
>add_view
>1437.         return self.changeform_view(request, None, form_url,
>extra_context)
>
>File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in
>_wrapper
>      67.             return bound_func(*args, **kwargs)
>
>File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in
>_wrapped_view
>149.                     response = view_func(request, *args, **kwargs)
>
>File "../env/lib/python3.4/site-packages/django/utils/decorators.py" in
>bound_func
>63.                 return func.__get__(self, type(self))(*args2,
>**kwargs2)
>
>    File "/usr/lib/python3.4/contextlib.py" in inner
>      30.                 return func(*args, **kwds)
>
>File
>"../env/lib/python3.4/site-packages/django/contrib/admin/options.py" in
>changeform_view
>      1367.         ModelForm = self.get_form(request, obj)
>
>File
>"../env/lib/python3.4/site-packages/djangocms_text_ckeditor/cms_plugins.py"
>in get_form
>      85.                 self.placeholder.slot,
>
>Exception Type: AttributeError at
>/admin/djangocms_blog/post/add-plugin/
>    Exception Value: 'NoneType' object has no attribute 'slot'
>
>Additionally, when I tried to downgrade back to 3.2.5, I attempted to
>undo the migration applied by 3.3.0 (0015) to get the database back to
>the correct 3.2.5 state. However, this triggered uninstalling all
>djangocms_blog migrations, which means it deleted all the blog data as
>well (fortunately there was only a single test post). Is this due to
>using '__latest__' as a dependency in the initial migration?
>
>Aside from the data loss, once I downgraded to 3.2.5 and re-ran the
>blog migrations, editing the placeholder worked as expected.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nephila/djangocms-blog/issues/265

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by jsma** [comment]
Ah, didn't notice the new release. With django-cms==3.3.0 and djangocms-text-ckeditor==3.0.0, the problem of adding a plugin is solved.

Any thoughts on the reverse migration behavior?

Thanks!

**Comment by yakky** [comment]
@jsma I agree with your remarks. I opened #266 to fix that
