### ISSUE TITLE
Displaying content

### ISSUE THREAD

**Issue by Darex1991** [nephila/djangocms-blog#270]
Hi I have problem.
Why I'm don't see article content?
Ie. I'm on http://localhost:8001/pl/2016/06/04/213 path and I'm only see title, date and author
![screen shot 2016-06-04 at 15 01 34](https://cloud.githubusercontent.com/assets/5881611/15799719/93fe7558-2a65-11e6-8882-1cc019b7c205.png)

![screen shot 2016-06-04 at 15 01 47](https://cloud.githubusercontent.com/assets/5881611/15799720/97333f7e-2a65-11e6-8cb5-91851132a24c.png)

but on blog page I see truncated that article..

**Comment by yakky** [comment]
Unless you set ``BLOG_USE_PLACEHOLDER=False`` the content must be added through django CMS plugins in the placeholder via the django CMS frontend editor

**Comment by Darex1991** [comment]
@yakky what else I should add?
