### ISSUE TITLE
No module named south.db on django 1.9.6

### ISSUE THREAD

**Issue by jhonvidal** [nephila/djangocms-blog#273]
Help me, 

my requirement is : 

`cmsplugin-contact-plus==1.2.7
dj-database-url==0.4.1
Django==1.9.6
django-admin-jqueryui==1.8.22
django-classy-tags==0.7.2
django-cms==3.2.5
django-filer==1.2.0
django-formtools==1.0
django-inline-ordering==1.0.2
django-mptt==0.8.4
django-polymorphic==0.8.1
django-recaptcha==1.0.5
django-reversion==1.10.2
django-sekizai==0.9.0
Django-Select2==4.3.2
django-simple-math-captcha==1.0.7
django-taggit==0.19.1
django-treebeard==4.0.1
djangocms-admin-style==1.2.2
djangocms-column==1.6.0
djangocms-file==1.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.2.1
djangocms-installer==0.8.9
djangocms-link==1.7.2
djangocms-picture==0.2.0
djangocms-portfolio==0.6
djangocms-style==1.7.0
djangocms-teaser==0.2.0
djangocms-text-ckeditor==2.9.3
djangocms-video==1.0.0
easy-thumbnails==2.3
html5lib==0.9999999
jsonfield==1.0.3
Pillow==3.2.0
psycopg2==2.6.1
pytz==2016.4
six==1.10.0
tzlocal==1.2.2
Unidecode==0.4.19
`

$ python manage.py migrate

result it is: 

```
/cmsplugin_filer_image/migrations/0003_auto__add_thumbnailoption__add_field_filerimage_thumbnail_option.py", line 3, in <module>
    from south.db import db
...
Django==1.9.6
django-cms==3.2.5
...

```
./

**Comment by yakky** [comment]
@jhonvidal which version of cmsplugin-filer package is installed? you probably have to configure the ``MIGRATION_MODULES`` setting as documented https://github.com/divio/cmsplugin-filer/blob/d977cbc61a00189801719745c20961cef0b5adb2/README.rst#installation

**Comment by jhonvidal** [comment]
django-filer==1.2.0

**Comment by yakky** [comment]
@jhonvidal how about ``cmsplugin-filer``? Have you set up ``MIGRATION_MODULES`` as stated in linked documentation?

**Comment by jhonvidal** [comment]
I'll test, thanks

**Comment by yakky** [comment]
@jhonvidal did you managed to get it working?

**Comment by yakky** [comment]
This will be closed in one week as no longer reproducible

**Comment by yakky** [comment]
Closing as per above
