### ISSUE TITLE
You do not have permission to add a plugin.  O RLY?

### ISSUE THREAD

**Issue by ursomniac** [nephila/djangocms-blog#274]
I get this intermittently.

I'm logged into the admin, the account is a super user.  There's no back-end code that would in any way limit access to the plugin.  It seems to just be "Django CMS has decided this is the case and there's no way around it..."

SOMETIMES if I: 1)  log out of the admin, 2) clear my browser cache, 3) restart the server, and 4) reboot the entire machine, the problem MIGHT go away.   Otherwise it persists.

This is REALLY affecting a production site (i.e, "the real world").   It's not the only Django-CMS-related "permissions weirdness" we've encountered but it's the one dominating getting work done at present.

Using: Django 1.8.13 with Dango-cms  3.2.5.

What's the workaround?

**Comment by yakky** [comment]
Do you experience this issue on ``placeholder`` in the blog templates or in any placeholder?

**Comment by yakky** [comment]
I see you opened this divio/django-cms#5400
Closing this, please add further comments if you have more information
