### ISSUE TITLE
Ability to invalidate cache on page publishing

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#276]
In our use-case, we use django's template cache blocks.

Would there be a merit of adding a config variable that would invalidate specific cache keys after post is changed / new content is added?

Is there any way to "hook" post-publish method and run custom code?

**Comment by yakky** [comment]
You can use signals like https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L456 to invalidate the cache

**Comment by petrklus** [comment]
thank yoiu @yakky !
