### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by leesolway** [nephila/djangocms-blog#278]
Django: 1.8.11
DjangoCMS: 3.3

Feature documentation and models indicate the ability to mark a blog post against 1 or multiple sites, however i can not find where this is possible within the interface. 

I am using the standard user model and have added the get_sites method as shown below:

def get_sites(self):
    return Site.objects.all()

auth.models.User.add_to_class('get_sites', get_sites)

**Comment by yakky** [comment]
I'll improve multisite documentation.
The basic multisite can be enabled by just setting ``BLOG_MULTISITE=True`` in the settings.
With this setting all the users enabled to handle the blog can handle all the posts in every site

If you want to restrict users on single sites, having a custom user is needed.

Sorry if the documentation is not clear enough on this

**Comment by yakky** [comment]
@leesolway would you check if #279 makes the multisite behavior more clear?

**Comment by leesolway** [comment]
That fixed it.. 
Yes the docs make more sense now.. 

I hadn't checked that setting because in the global settings doc it states:
BLOG_MULTISITE: Add support for multisite setup; (default: True)

It must be defaulted to False :).

**Comment by yakky** [comment]
@leesolway uhm, that's weird. The default is ``True`` already, and I checked an existing website that uses multisite without permissions and the sites selection widget is available. It's weird that you had to enable it
