### ISSUE TITLE
Confusing with social media

### ISSUE THREAD

**Issue by Darex1991** [nephila/djangocms-blog#280]
Hi, I have some problem with social media. Please check it and answer me [Link](http://stackoverflow.com/questions/37888187/djangocms-blog-how-to-include-social-media-ie-facebook).

**Comment by Darex1991** [comment]
@yakky please check also [Link](http://stackoverflow.com/questions/37889631/count-comments-of-djangocms-comments-in-djangocms-blog) ;)
I just want to display comments count on listed posts
![screen shot 2016-06-18 at 20 02 38](https://cloud.githubusercontent.com/assets/5881611/16172787/b6430c98-358f-11e6-98b8-c6fb20977b15.png)

**Comment by yakky** [comment]
See my comments on stackoverflow. Closing here, will follow up there

**Comment by Darex1991** [comment]
👍
