### ISSUE TITLE
cmsplugin-filer 1.1.1 causes migration issues

### ISSUE THREAD

**Issue by leesolway** [nephila/djangocms-blog#282]
Upgrading cmsplugin-filer to 1.1.1 breaks migration dependencies for djangocms-blog.

django.db.migrations.graph.NodeNotFoundError: Migration djangocms_blog.0007_auto_20150719_0933 dependencies reference nonexistent parent node (u'cmsplugin_filer_image', u'0003_mv_thumbnail_option_to_filer_20160119_1720')

**Comment by yakky** [comment]
@leesolway which djangocms_blog version have you installed? It's strange as that migration is included in cmsplugin_filer 1.1.1 (https://github.com/divio/cmsplugin-filer/blob/41a2ced0d76bc192d4222db7541a3f516235ec0b/cmsplugin_filer_image/migrations/0003_mv_thumbnail_option_to_filer_20160119_1720.py). It wasn't in 1.1

**Comment by leesolway** [comment]
0.8.4 for the blog (updated from 0.8.3).. If i downgrade cmsplugin_filer it works fine again.

**Comment by yakky** [comment]
I'll investigate soon. thanks for the report

**Comment by yakky** [comment]
@leesolway wait: did you removed cmsplugin_filer migrations for ``MIGRATION_MODULES`` in settings?

**Comment by leesolway** [comment]
Now i feel a silly. I totally missed that. 
That seems to be working fine now. (cmsplugin-filer migrations are now breaking for me, but that is a different issue). 

Thanks @yakky

**Comment by yakky** [comment]
@leesolway good, let's see what we can do to fix the cmsplugin-filer issue :)

**Comment by leesolway** [comment]
Applying cmsplugin_filer_image.0004_auto_20160120_0950...Traceback (most recent call last):
django.db.utils.IntegrityError: (1217, 'Cannot delete or update a parent row: a foreign key constraint fails')

**Comment by yakky** [comment]
@leesolway maybe it's better to move this to cmsplugin-filer repo? Do you mind to open the issue there?

**Comment by leesolway** [comment]
@yakky Will do. I'm in the django-cms IRC channel aswell, if that is helpful.

**Comment by yakky** [comment]
@leesolway yeah, probably better. Joining
