### ISSUE TITLE
Multisite - Category and Tag plugins

### ISSUE THREAD

**Issue by leesolway** [nephila/djangocms-blog#285]
The category and tag plugins should filter results based on the currently active site (if sites are defined against a post) as well as the current filter on the app config. 

This change would prevent tags and categories showing that do not have results for the active site.

**Comment by yakky** [comment]
This is linked to https://github.com/divio/django-cms/pull/5458

**Comment by leesolway** [comment]
Out of interest @yakky why would this be linked? 

I thought making an app hook not unique on a site per site basis would cause the issue mentioned above as well..

**Comment by yakky** [comment]
The ratio of apphooks config is to completely separate blog posts belonging to different apphooks. If apphok configs can be shared across multiple sites, then you can see the same posts in multiple sites and tags and categories will also show the posts across multiple sites.
To cover the other case, it's possible to extend the default plugins and views to ignore apphooks, though, and then share the tags and categories.

**Comment by yakky** [comment]
Maybe we can add documentation on how to override the apphooks config in plugins and views

**Comment by leesolway** [comment]
I can see scenarios where plugins want to filter by AppHook and Site. I see this as the default 
behaviour without any negative side effects.

Example:

**Article 1**
Category: News
Site: Site1, Site2
AppHook: AppHook1

**Article 2**
Categories: Blog
Site: Site1
AppHook: AppHook1

Now the front end.. 

**Site 1: **
Category Plugin
Apphook: AppHook1
Displays: News, Blog correctly

**Site 2: **
Category Plugin
Apphook: AppHook1
Displays: News, Blog incorrectly

There is no need to display Blog on site two, as there are no articles marked for this site.
The categories link would not find any posts, making it redundant.

**Comment by yakky** [comment]
@leesolway now I get it! How about a flag to select whether to display tags and categories in blog only if any post is associated with it in the current site?

**Comment by leesolway** [comment]
Sounds good to me :)

**Comment by yakky** [comment]
@leesolway would you give #287 a spin? It's based on upcoming version 0.9 it will work without breaks in Django 1.8 / django CMS 3.2

**Comment by leesolway** [comment]
@yakky This hasn't worked. Both Tags and Categories are showing from Site1, even though Site2 has no articles.

**Comment by yakky** [comment]
This is what I get on the main blog view of two sites adding the categories plugin on the left creating the article as above

![site1](https://cloud.githubusercontent.com/assets/714711/16397255/9581e07a-3cc3-11e6-8e79-5f641d4aa1b8.png)
![site2](https://cloud.githubusercontent.com/assets/714711/16397256/95839c94-3cc3-11e6-9284-00ef11041ec2.png)

**Comment by leesolway** [comment]
Re-tested on a clean install, looks good.

**Comment by yakky** [comment]
@leesolway awesome, thanks. It looks like I should release 0.9b1 soon :)
