### ISSUE TITLE
can't create category

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#288]
After a fresh installation you can't easy create a first blog entry, because there are no categgory and you can't easy create one:

![unbenannt](https://cloud.githubusercontent.com/assets/71315/16410796/747d16c2-3d24-11e6-8eff-d7c5ac0ff405.PNG)

You have to know how to go into the admin and create a category... The normal django "plus button feature" is not there... Maybe #125 will fix this?!?

**Comment by yakky** [comment]
@jedie it's actually how the form wizard is built. From the normal admin change form you can create categories directly. I'm not entirely sure we can add a button to create the category in the django CMS wizard. Will investigate

**Comment by jedie** [comment]
Think the best solution is, that django cms will change this.

Maybe a easy solution: Create and preselect a default category like "misc".

**Comment by protoroto** [comment]
@yakky @jedie I think this can be closed, the wizard has changed a lot so I guess this is not a problem anymore.
