### ISSUE TITLE
migration problems...

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#289]
While CI run i get a migration error, related to djangocms-blog and cmsplugin_filer_image:
```
$ pip freeze
...
cmsplugin-filer==1.1.1
Django==1.8.13
django-cms==3.3.0
django-filer==1.2.2
djangocms-blog==0.8.5
...
Creating test database for alias 'default'...

Traceback (most recent call last):
...
django.db.migrations.graph.NodeNotFoundError: Migration djangocms_blog.0007_auto_20150719_0933 dependencies reference nonexistent parent node ('cmsplugin_filer_image', '0003_mv_thumbnail_option_to_filer_20160119_1720')
```
Full CI output: https://travis-ci.org/jedie/PyLucid/jobs/140795585

Any idea, why this happen?!?

**Comment by yakky** [comment]
@jedie did you removed cmsplugin filer custom migration path from ``MIGRATION_MODULES``?

**Comment by jedie** [comment]
Yes, that was the problem and fixed with: https://github.com/jedie/PyLucid/commit/6aeb88a0802e090e7c332ca4b928e24421ea40b5

Thanks!
