### ISSUE TITLE
Wrong variable name for BLOG_PERMALINK_URLS in the documentation

### ISSUE THREAD

**Issue by avoine** [nephila/djangocms-blog#291]
The documentation at:

https://djangocms-blog.readthedocs.io/en/latest/features.html#attaching-blog-to-the-home-page

the example is saying BLOG_PERMALINKS_URLS but the code at:

https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/settings.py#L89

is saying BLOG_PERMALINK_URLS (without the S)

**Comment by avoine** [comment]
Also BLOG_PERMALINK should be BLOG_AVAILABLE_PERMALINK_STYLES

**Comment by yakky** [comment]
Thanks @avoine !
Fixed now in 0eb61c3 and 70f3ef7
I will make the internal names clearer in a later fix

**Comment by avoine** [comment]
don't forget BLOG_AVAILABLE_PERMALINK_STYLES

**Comment by yakky** [comment]
Sorry, wrong commit ids : 8a479a and 7c4b3a7
