### ISSUE TITLE
No attribute 'safe_translation_getter' 

### ISSUE THREAD

**Issue by fguimara** [nephila/djangocms-blog#296]
I am getting a 'NoneType' object has no attribute 'safe_translation_getter' that I can not trace the reason.

http://www.stage.twistsystems.com/pt-br/blog/

Any advice?

**Comment by yakky** [comment]
@fguimara is the post associated with any category?
If not, you have to choose the permalink without any category, otherwise the URL cannot be built correctly

**Comment by fguimara** [comment]
Sure!! Thank you very much... But as a side note, maybe, there should be a way of blocking publishing a post with no category when the category is a permanent link item. This would be more user friendly =)

**Comment by yakky** [comment]
@fguimara thanks for the update. I opened an issue to track this.
