### ISSUE TITLE
Set category as requested or not depending on the urlconf

### ISSUE THREAD

**Issue by yakky** [nephila/djangocms-blog#297]
When setting `BLOG_PERMALINKS_URLS='category` you have to make sure all the posts have the category set; we can enforce this in the admin form
This is a good issue for a first time contribution

In https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/forms.py#L119 set the `categories` field as required if `self.app_config.url_patterns == 'category'`

See #296  for background

**Comment by flevour** [comment]
@yakky is this still applicable?

**Comment by davideferre** [comment]
Tried to solving it in pull request #468

**Comment by yakky** [comment]
@flevour yes, still applicable.
#468 fix this. it needs minor changes before merging but that's the solution

**Comment by yakky** [comment]
Fixed by #480 which will be released in 0.9.10
Thanks you all for reporting this
