### ISSUE TITLE
call "autosetup" explicit and use it for other SITE_ID

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#299]
There is no way to call "autosetup" with a other SITE_ID than the current site from the settings, isn't it?

I would like to create a default blog page, if not exist for all existing sites.

EDIT: Missing feature in https://github.com/nephila/djangocms-apphook-setup ?

**Comment by yakky** [comment]
Yes, it's definitely a apphook-setup issue: it currently ignores the SITE_ID completly. It must be extended to add some kind of support
Could you open the issue there to track the process to include support for this?

**Comment by yakky** [comment]
Close here in favor of nephila/djangocms-apphook-setup#2
