### ISSUE TITLE
What is the best way to embed a youtube video in a blog post

### ISSUE THREAD

**Issue by fguimara** [nephila/djangocms-blog#306]
I've tried to add in the source mode, however it understands it as plan text.

**Comment by fsbraun** [comment]
I've had the same issue with the blog and django cms in general. I assume you are using ckeditor. Youtube videos typically use the `iframe` tags which if entered in ckeditor's source mode are converted to plain text.

To allow iframes in ckeditor, add the following line to your `setup.py`:

    TEXT_ADDITIONAL_TAGS = ('iframe',)

Hope it works for you.

**Comment by yakky** [comment]
@fsbraun @fguimara have a look at plugins like aldryn-video or djangocms-video
It's usually a much simpler way to embed videos

**Comment by fguimara** [comment]
@fsbraun it worked fine. 
Could not find a way aldryn-video could help to add videos in a post though.

**Comment by yakky** [comment]
@fguimara both aldryn-video and  djangocms-video are just plugins you can add to the post content
