### ISSUE TITLE
Typos in local french .po files

### ISSUE THREAD

**Issue by jlevesque** [nephila/djangocms-blog#308]
line 43 - 44
`msgid` "blog config"
msgstr "Catégorie du blog"`

The msgstr should be "Configuration du blog"

line 185 - 186
`msgid "Blog menu"
msgstr "Catégorie du blog"`

The msgstr should be "Menu du blog"

It is confusing because in the admin there is two sections call Blog Category (catégories du blog) right next to each other. But one is the Category and the other is the Config.

It's a minor issue, but it is confusing 
cheers

**Comment by yakky** [comment]
@jlevesque thanks for the remarks. If you are willing to contribute, translations can be updated easily via transifex interface https://www.transifex.com/nephila/djangocms-blog (french is currently at 94%, just 7 strings away from complete coverage!)

**Comment by yakky** [comment]
Fixed in 3b1e2de
