### ISSUE TITLE
Instant Article Facebook

### ISSUE THREAD

**Issue by fguimara** [nephila/djangocms-blog#314]
This is another question:

I could see the instant article feed from my blog when accessing /blog/feed/fb/  (http://www.twistsystems.com/pt-br/blog/feed/fb/) 

However, I can't tell how to publish in Facebook as a Instant Article. Is it possible to do it? In a way the FB post appear with the lightning  symbol?

Thanks

**Comment by yakky** [comment]
You must setup instant articles in your facebook page and add the feed as the "live feed" and let facebook load the articles from the feed. You can follow FB documentation for complete guide on how to set it up https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed

**Comment by fguimara** [comment]
Thanks!!! Pretty straight foward! this could be written on the docs! I could not find the step-by-step...
