### ISSUE TITLE
Site permission bugs

### ISSUE THREAD

**Issue by jankopacek** [nephila/djangocms-blog#315]
If no site selected on article, user with get_sites method cannot edit it, but it is shown on all sites.
Allowed sites are cached as a class propery, so on single thread server (django server) one user is switching allowed sites to another one, if I understand that properly.

**Comment by yakky** [comment]
Fixed by #318

**Comment by yakky** [comment]
@jankopacek thanks for reporting this. It will be fixed in next 0.8.x version (due soon, actually)
