### ISSUE TITLE
Add GIFs as thumbnail image

### ISSUE THREAD

**Issue by herczogzoltan** [nephila/djangocms-blog#337]
I tried to add a _gif_ instead an image to the thumbnail image section and it converted it back to a _png_ . Anyone else tried to do this too?

**Comment by yakky** [comment]
@herczogzoltan this is likely to depend on this easy-thumbnail option https://easy-thumbnails.readthedocs.io/en/2.1/ref/settings/#easy_thumbnails.conf.Settings.THUMBNAIL_PRESERVE_EXTENSIONS

**Comment by yakky** [comment]
@herczogzoltan does the above link fix your issue?

**Comment by yakky** [comment]
@herczogzoltan closing this. Feel free to add further comments if it's not solved by the above link
