### ISSUE TITLE
Post does not work with language_chooser template tag

### ISSUE THREAD

**Issue by razisayyed** [nephila/djangocms-blog#339]
django cms language_chooser template tag always return current language.

for an example I have blog post that is translated for languages en and ar

I use language_chooser template tag to get translation links while I am in english version of the website:
two links are generated from template tag:
1. en: url points to en version of the post
2. ar: url points to **en** version of the post

I think the problem is with the first two lines of get_absolute_url function which always returns current language:

```
    def get_absolute_url(self, lang=None):
        if not lang or lang not in self.get_available_languages():
            lang = self.get_current_language()
            ...
```

If you comment the above two lines, language_chooser where returns correct url for each language.

**Comment by yakky** [comment]
@razisayyed thanks for reporting. This will be fixed in upcomin 0.8.10

**Comment by yakky** [comment]
0.8.10 released

**Comment by razisayyed** [comment]
@yakky can you please apply this fix to develop branch.

Thanks in advance.
