### ISSUE TITLE
missing migration with aldryn-apphooks-config==0.3.1

### ISSUE THREAD

**Issue by electroniceagle** [nephila/djangocms-blog#345]
The just-released aldrin-apphooks-config 0.3.1 added translations to their abstract models.
https://github.com/aldryn/aldryn-apphooks-config/commit/1bd6167a79b9dd10da96f5f60e9ccc848fbf238e

This causes a missing migration on BlogConfig.

```
Migrations for 'djangocms_blog':
  0022_auto_20170302_1651.py:
    - Alter field namespace on blogconfig
    - Alter field type on blogconfig
```

**Comment by yakky** [comment]
Fixed by #348 and 7de807e7419cbf1503a834c22c54c5e764ed654b

Thanks @electroniceagle for reporting this and proposing the fix
