### ISSUE TITLE
Bug with URL without language prefix

### ISSUE THREAD

**Issue by liminspace** [nephila/djangocms-blog#352]
Hi!
When I use `solid_i18n` in django 1.8 or `prefix_default_language=False` (https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#django.conf.urls.i18n.i18n_patterns) in django 1.10 I see some bug.
For example, I have two languages: EN and UK. EN is primary.
I open `/uk/blog/` and see posts. It's OK.
But, when I open `/blog/` -- I see text "No article found.". But when I refresh the page again, I see EN posts.

django-cms==3.4.2
djangocms-blog==0.8.12

**Comment by yakky** [comment]
Thanks for reporting
Do you see this happening in normal django CMS pages too?

**Comment by yakky** [comment]
@liminspace I can't reproduce this with latest Django 1.10 and django CMS version.
I'll close this. Feel free to comment / reopen this if it's still not fixed for you
