### ISSUE TITLE
Article's content is missing in detail view

### ISSUE THREAD

**Issue by vladtyum** [nephila/djangocms-blog#354]
Hey guys.
The question could be very stupid, but since it's too simple to be shown in docs, and i'm way too far from understanding CMS machinery , I'd like to ask for you help.
It shouldn't take much of your time, and could be helpful for newcomers

> Python3.4
> Django 1.8
> djangocms-installer (0.9.6)
> django-cms (3.4.2)
> djangocms-blog (0.8.11)
 
My steps:
1. installed test project, 
2. installed djangocms-blog
3. put installed apps from docs to settings
4. made migrations , migrated
5.created homepage, category, article

## Issue:
**the content of article is not show in DetailView,** 

Thing that makes me confused is that it's showing up in Category List, or in Blog List
Disappears only in DetailView. And only content does.

I'm about to go into Apphooks, but since content is shown in CategoryList and BlogList, it makes me feel that integrating job is done already

The same time log about missing `aldryn_apphooks_config.js` makes me hesitating

### From log
`[21/Mar/2017 16:43:44]"GET /static/js/aldryn_apphooks_config/aldryn_apphooks_config.js HTTP/1.1" 404 1880`

Thanks a lot in advance

**Comment by yakky** [comment]
@vladtyum If I understand correctly your issue, I think that you are missing adding plugins in the blog post. The abstract field in the post form it's not the content, but only the lead that's shown in the list view. In the detail view you have to add plugins by switching to structure mode. See this django CMS primer http://django-cms.readthedocs.io/en/release-3.4.x/user/tutorial/structure-content-modes.html

WRT missing ``aldryn_apphooks_config.js``, have you added ``aldryn_apphooks_config`` to the ``INSTALLED_APPS``?

**Comment by vladtyum** [comment]
@yakky First of all, thank you for reply
As that usually happens, just some silly misunderstanding.
Everything works fine actually, as it supposed to.  I've missed `"ABSTRACT:"` field with Post placeholder. 
I thought that `"ABSTRACT"` field is exactly post's body. Just found that there were similar issue https://github.com/nephila/djangocms-blog/issues/52
Now it's becoming clear. Thanks again.

_Maybe i'll make some sense  to note in docs that "ABSTRACT" in Post fields is not the body of the Post._

**Comment by yakky** [comment]
@vladtyum thanks for your suggestion. this is actually something we can better describe how to add content to the posts
