### ISSUE TITLE
Per app instance default for image sizes (preview and full size)

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#357]
**Issue:**
It turns out that I have inconsistently set image sizes for preview and full size images within the posts of one app instance. Editors have to set them by hand and it turns out they do it inconsistently.

**Feature suggestion:**
I suggest to offer a preset for image size on a per app instance base (so, if there are different blogs on a site they can be preset individually). For every new post that is created using either the wizard or add post these presets are copied and for the most cases will not have to be changed by content editors.

This means creating default fields for ``main_image_full`` and ``main_image_thumbnail`` in the ``BlogConfigForm`` I guess.

**Comment by yakky** [comment]
Yeah, this would be nice
This will require the new fields above and setting the defaults in the ``__init__`` of the model form https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/forms.py#L54

**Comment by fsbraun** [comment]
Will give it a shot.

**Comment by yakky** [comment]
Fixed by #392 
Thanks @fsbraun
