### ISSUE TITLE
Blog namespace 500 error when visiting sitemap.xml

### ISSUE THREAD

**Issue by mliudev** [nephila/djangocms-blog#368]
An internal server error bug occurs when visiting the sitemap.xml page. This bug occurs if there are no published articles for a blog app config. I've setup a repo demonstrating the bug and steps to reproduce [here](https://github.com/mliudev/sitemap-bug/).

requirements.txt:

```
Django==1.11.1
django-cms==3.4.3
djangocms-blog==0.8.12
```

**Comment by yakky** [comment]
@mliudev thanks for the example website!

**Comment by yakky** [comment]
@mliudev You have a blog post in the "blog / blog" apphook configuration but no published pages using that apphook configuraion.
As sistemap currently go through all the published posts, when it tries to get the absolute url for the post in "blog" apphook config, it fails
A solution is to move the blog post, or unpublish it
Mayb we can just catch the exception in the blog sitemap code to avoid returning a nasty 500 error in su case

**Comment by mliudev** [comment]
I see, so the problem is that there are published blog posts that are associated with unpublished app configs. Catching the exception and then continuing to parse the rest of the blog articles is a good idea. There are use cases where I would want to test what a blog page would look like without publishing it. This shouldn't break sitemap.xml. @yakky What do you think?

**Comment by mliudev** [comment]
@yakky Created the PR but I'm not sure if this is the best way to do this. The problem is how to check if an app config is not published. I couldn't figure out a good way to do this so I'm just filtering out posts from `items()` by checking if they have a valid url. If you can think of a better way to do this, point me in the right direction and I'll refactor the PR.

**Comment by yakky** [comment]
@mliudev I think that checking if the URL can be reversed or not is a valid approach
I wonder if we can somehow cache the valid results and reuse here https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/sitemaps/__init__.py#L24 to reverse the url only once

**Comment by mliudev** [comment]
@yakky Made the change you suggested. See if it's what you had in mind.
