### ISSUE TITLE
Duplicating Items Shown In the Menu of the Translated Blog Category

### ISSUE THREAD

**Issue by jaythecaesarean** [nephila/djangocms-blog#374]
This issue shows up on multilingual site (in my case Thai and English).
Steps for bug duplication:
1. Create a multi-lingual site (i.e. at least 2 languages)
2. Create a blog category and make sure that you also created its translation/s
3. View the site. Check if there are blog menus. In my case, the English page has correct (no duplicating) submenus but on the Thai page, the 'blog category' submenus are shown twice.

For reference: 
Thai:      https://ibb.co/mavT5v
English: https://ibb.co/kf8Rsa

Requirements:
`Django=1.10`
`djangocms-blog=0.8.12`

**Comment by yakky** [comment]
@jaythecaesarean thanks for reporting.
issue confirmed.
Checking possible fixes

**Comment by yakky** [comment]
Fixed in #376 released with 0.8.13
Thanks @jaythecaesarean for reporting!
