### ISSUE TITLE
Use easy_thumbnails_tags instead

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#377]
If you're willing to require easy_thumbnails 2.4.1 or higher, it now includes a fix to enable the thumbail tag to be loaded via ```{% load easy_thumbnails_tags %}``` instead of ```{% load thumbnails %}```. This fixes a namespace conflict where other 3rd party libraries have defined their own templatetag called "thumbnails". sorl-thumbnail is an example of such library.

For example, one of my third party apps required solr-thumbnail, which caused django-cms blog's ```{% load thumbnails %}``` to load the solr one, instead of easy_thumbnails, resulting in errors.

**Comment by yakky** [comment]
Thanks for the heads up! Probably we can fit this into 0.9 release

**Comment by bxm156** [comment]
For search-ability

This issue would manifest itself  as 
```
TemplateSyntaxError: Invalid block tag on line 22: 'endif', expected 'empty' or 'endthumbnail'. Did you forget to register or load this tag?
```

The error results because the solr-thumbnail tag is loaded instead of easy_thumbnails.
