### ISSUE TITLE
Clarification on contributing

### ISSUE THREAD

**Issue by bxm156** [nephila/djangocms-blog#379]
One question I had about contributing. Which branch should I base my changes on? I guess by default I always do master, but when I was working on this project, I realized it looked like new changes should be done from "develop". Might be worth clarifying this in the CONTRIBUTING docs.

**Comment by yakky** [comment]
@bxm156 thanks for the heads up
Indeed:

* new features and bugfixes goes to develop
* critical bugfixes for 0.8 releases goes to release/0.8.x
* master is just a snapshot of the latest stable release

**Comment by yakky** [comment]
Fixed in #383 
Thanks @bxm156 for reporting!
