### ISSUE TITLE
Question (Social Media)

### ISSUE THREAD

**Issue by javadevelopcom** [nephila/djangocms-blog#380]
Is it possible to post blog messages to Social media (Twitter, LinkedIn, Facebook)?

**Comment by yakky** [comment]
@javadevelopcom do you mean post them automatically when published using the social networks API?
There is no such thing.
As long as you know the API you can hook into the Django signals to post articles to SN

**Comment by fsbraun** [comment]
To allow readers to share articles on Facebook, Twitter, LinkedIn or just mail them, I simply added share buttons to my ``post_detail.html`` template just before ``</article>``. I myself typically only share individual thoughts on an article (gives more interactions) and do that manually.

For the share buttons I chose to use https://github.com/heiseonline/shariff which makes it easy to configure and just requires a simple ``<div>`` to be added (see documentation of shariff). I wrapped the shariff files in a simple template tag, so the ``<div>`` becomes ``{% shariff %}``:

    from django.conf import settings
    from django import template

    register = template.Library()

    @register.inclusion_tag('djangocms_blog/shariff.html', takes_context=True)
    def shariff(context, title=None, services=None, orientation=None):
        context['orientation'] = orientation if orientation else 'horizontal'
        context['services'] = escape(services if services else 
                                    settings.SHARIFF['services'])  # MUST be configured in settings.py
        if title:
            context['short_message'] = settings.SHARIFF.get('prefix', '') + title +\
                          settings.SHARIFF.get('postfix', '') 
        if 'mail-url' in settings.SHARIFF:
            context['mail_url'] = settings.SHARIFF['mail-url']
        return(context)

And in ``templates/djangocms_blog/shariff.html`` I have

    {% load static sekizai_tags %}
    {% addtoblock 'js' %}<script src="{% static 'js/shariff.min.js' %}"></script>{% endaddtoblock %} 
    {% addtoblock 'css' %}<link href="{% static 'css/shariff.min.css' %}" rel="stylesheet">{% endaddtoblock %}
    <div class="shariff" data-services="{{services}}" data-orientation="{{orientation}}"{% if mail_url %} data-mail-url="{{mail_url}}"{% endif %}{% if short_message %} data-title="{{short_message}}"{% endif %}></div>

**Comment by yakky** [comment]
@fsbraun nice solution :)

**Comment by yakky** [comment]
@fsbraun I'd like to add this to the documentation. Thanks for sharing

**Comment by fsbraun** [comment]
Sure. Will you do this? Or are you asking me to do it?

**Comment by yakky** [comment]
@fsbraun if you have time, that would be great. but no pressure. I can handle this low-priority
