### ISSUE TITLE
Question: Post specific Facebook OG tags?

### ISSUE THREAD

**Issue by chromakey** [nephila/djangocms-blog#387]
Hi Everyone,
Thanks for all of your hard work on this great library. 

I've been looking through the documentation and clicking through the menu bar and I can't seem to find a place to set post specific facebook OG tags.  I see it at the "page" and "site" levels, but not at the post level.  Is this currently supported and, if so, could someone point me in the right direction?  Thanks so much.

**Comment by yakky** [comment]
Hi, OG tags are generated automatically from the post fields by using django-meta (http://django-meta.readthedocs.io/en/latest/) (see https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L204 for the detailed matching between tags values and model fields)
By using settings ytou can further configure the OG properties (http://djangocms-blog.readthedocs.io/en/latest/settings.html)

**Comment by yakky** [comment]
@chromakey  if you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications

**Comment by yakky** [comment]
@chromakey I'll close this. If you need further information on this topic head to our gitter room https://gitter.im/nephila/applications. We'll be happy to discuss this
