### ISSUE TITLE
Post .get_absolute_url requires at least one category set

### ISSUE THREAD

**Issue by cluster-master** [nephila/djangocms-blog#390]
in case of no categories were added to Post (as .categories blank=True)
that post .get_absolute_url method will fail if also
`'<category>' `is in BLOG_PERMALINK_URLS settings

so, probably need to check if post.categories.first() is not None
before using it that way:

```
djangocms_blog/models.py:257
if '<category>' in urlconf:
    kwargs['category'] = category.safe_translation_getter('slug', language_code=lang, any_language=True)  # NOQA
```

**Comment by yakky** [comment]
You can set a url pattern that does not require a category (see http://djangocms-blog.readthedocs.io/en/latest/features.html#configurable-permalinks)
We can improve documentation to help set this up correctly

**Comment by yakky** [comment]
@cluster-master did the above suggestion solved your use case?

**Comment by yakky** [comment]
if you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications
