### ISSUE TITLE
Question: Convert to placeholder?

### ISSUE THREAD

**Issue by Natureshadow** [nephila/djangocms-blog#391]
Hi,

we have started using djangocms-blog with a lot of posts, and now we want to use the placeholder feature instead of the plain text article (because we want to add multiple pictures to posts).

Is there a good way to switch to the placeholder system and migrating all existing articles?

I could probably hack that together in SQL, but maybe there's another, already tested, way.

Or, in other words, why is the ckeditor in blog articles so limited, while everywhere else I can add CMS plugins within ckeditor?

**Comment by yakky** [comment]
@Natureshadow You can easily use the django CMS API `add_plugin` feature http://django-cms.readthedocs.io/en/release-3.4.x/reference/api_references.html#cms.api.add_plugin to cycle through all the plugins, get the text, add a text plugin, remove the original text (this is not required, though) and switch to "placeholder mode"
Something like (not tested, just from the top of my head)
```
for post in Post.objects.language().all(): 
    add_plugin(post.content, 'TextPlugin', language=post.get_current_language(), body=post.post_text)
    post.post_text = '' # optional
    post.save() # optional
```

**Comment by Natureshadow** [comment]
@yakky Wow, works perfectly! Thanks a lot!

**Comment by yakky** [comment]
You are welcome!
