### ISSUE TITLE
Question: option for more author info

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#394]
It would be nice to have author pages containing some background information about the author and a picture.

**Comment by yakky** [comment]
You can easily achieve this by using a profile model or a custom user model for your project.
Custom user models are fully supported and allows you add any kind of information you need to the authors (see https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#specifying-a-custom-user-model for documentation)

**Comment by yakky** [comment]
if you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications

**Comment by yakky** [comment]
@kynsi  I'll close this. If you need further information on this topic head to our gitter room https://gitter.im/nephila/applications. We'll be happy to discuss this
