### ISSUE TITLE
Problem accessing config values

### ISSUE THREAD

**Issue by aikipooh** [nephila/djangocms-blog#395]
I've just installed djangocms-blog, following the installation steps, but I've exceptions of the same nature all around. I'm not sure which module to blame, but hope here you have some ideas:)

>   File "/home/pooh/work/venv/lib64/python3.5/site-packages/aldryn_apphooks_config/models.py", line 54, in __getattr__
    return getattr(self.app_data.config, item)
  File "/home/pooh/work/venv/lib64/python3.5/site-packages/app_data/containers.py", line 159, in __getattr__
    return self.__getitem__(name)
  File "/home/pooh/work/venv/lib64/python3.5/site-packages/app_data/containers.py", line 146, in __getitem__
    self._attr_cache[name] = field.clean(self._data.get(name, field.initial))
  File "/home/pooh/work/venv/lib64/python3.5/site-packages/django/forms/fields.py", line 161, in clean
    self.validate(value)
  File "/home/pooh/work/venv/lib64/python3.5/site-packages/django/forms/fields.py", line 823, in validate
    params={'value': value},
django.core.exceptions.ValidationError: ["Select a valid choice. ['Blog'] is not one of the available choices."]

I've poked around, indeed, the values from the config are read as lists, not strings. I've tried modifying the respective places to use the string value from the list, and it works.
In the DB it's like this:
> |  1 | djangocms_blog.cms_appconfig.BlogConfig | Blog      | {"config": {"use_abstract": null, "og_type": ["Article"], "send_knock_update": null, "paginate_by": "10", "default_published": null, "og_author_url": "get_author_url", "object_type": ["Article"], "gplus_author": "get_author_gplus", "url_patterns": ["short_date"], "sitemap_changefreq": ["monthly"], "og_author": "get_author_name", "gplus_type": ["Blog"], "use_placeholder": null, "og_app_id": null, "set_author": null, "sitemap_priority": "0.5", "template_prefix": null, "twitter_author": "get_author_twitter", "send_knock_create": null, "og_profile_id": null, "og_publisher": null, "twitter_type": ["summary"], "twitter_site": null, "menu_structure": ["complete"]}} |

Here I'm not sure what is the reason to store arrays instead of values, and therefore what's the best approach to fix it, can you please help?

django-1.11.6
django-cms (3.4.5)
djangocms-blog (0.9b10) — from git

**Comment by kynsi** [comment]
Have you tried with django 1.10.8?

**Comment by aikipooh** [comment]
Yes, the same:(

**Comment by yakky** [comment]
@aikipooh which version of django-appdata is installed?
Could you post your `INSTALLED_APPS` setting?
Have you added django CMS blog application to a CMS page and published it?

**Comment by aikipooh** [comment]
@yakky, I've all this dismantled already, so cannot say anything. Using zinnia now.

**Comment by yakky** [comment]
@aikipooh thanks for the feedback!
