### ISSUE TITLE
Q: How to make RSS feeds work

### ISSUE THREAD

**Issue by Natureshadow** [nephila/djangocms-blog#396]
I am trying to make RSS feeds for categories and tags work.

My setup:

I have Django-CMS 3.4.5 with multisite and multilanguage.

In my urls.py, I have:

```
url(r'^blog/', include('djangocms_blog.urls', namespace='djangocms_blog')),
```

My site has an apphook config, two categories (Neuigkeiten and Ankündigungen in the German language).

I am trying to access `/blog/feed`, which throws an error because it somehow gets an empty namespace, and I do not find any hints on how to construct URLs for a single category or even a tag.

Also, can't I somehow get the `<link rel="alternative" …` headers into my home page and the pages containing the blog app hooks?

**Comment by yakky** [comment]
For this application to work properly, you have to use the apphooks feature of django CMS: i.e.: attach the blog application to a django CMS page (http://django-cms.readthedocs.io/en/release-3.4.x/user/reference/page_admin.html#advanced-settings, http://django-cms.readthedocs.io/en/release-3.4.x/topics/apphooks.html) as djangocms-blog uses the informated enabled by the apphook to configure its context

**Comment by yakky** [comment]
@Natureshadow if you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications

**Comment by yakky** [comment]
Thanks @Natureshadow for popping into our gitter room. Happy to have helped you fixing this. Closing this issue
