### ISSUE TITLE
Support for tags?

### ISSUE THREAD

**Issue by Logmytech** [nephila/djangocms-blog#401]
Is there support for tags like Zinnia and wordpress do?

Or can I use a seperate plugin for that?

**Comment by yakky** [comment]
@Logmytech tags are fully supported: you can assign tags to posts by opening the `info` tab in the blog post changeform, and you have a full set of django CMS plugins and views to put the list of tags in your pages and let users see per-tag lists of posts

**Comment by yakky** [comment]
If you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications

**Comment by yakky** [comment]
@Logmytech  I'll close this. If you need further information on this topic head to our gitter room https://gitter.im/nephila/applications. We'll be happy to discuss this
