### ISSUE TITLE
Import existing content?

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#406]
Is it somehow possible to import existing content into a blog? I'm migrating articles from an existing custom-built cms to djangocms-blog but need to transfer 1400 articles. I've kind of figured out how to do it on a database level but that's a bit tricky.

**Comment by yakky** [comment]
It's definitely possible
Have a look at https://gist.github.com/yakky/11336204 as an example

**Comment by kynsi** [comment]
Thanks! That looks promising.

**Comment by yakky** [comment]
Feel free to pop into https://gitter.im/nephila/applications if you need more clarifications.
We will try to document the import process better in #409 
Closing this
