### ISSUE TITLE
Can't install on mysql?

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#417]
After a fresh install "python manage.py" migrate crashes when using mysql:

```
Applying djangocms_blog.0032_auto_20180109_0023...Traceback (most recent call last):
...
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

```
No problems in sqlite.

django 1.10.8, django-cms 3.4.5, djangocms-blog 0.9.0rc1, mysql 5.7.13 osx

**Comment by yakky** [comment]
Are you using utf8mb4 encoding?

**Comment by kynsi** [comment]
Yes, tried utf8, utf8mb4, utf16

**Comment by kynsi** [comment]
Just tried with latin1 and that worked!

**Comment by yakky** [comment]
@kynsi linked PR should fix the issue
You can test this with:
```
pip uninstall djangocms-blog && pip install https://github.com/nephila/djangocms-blog/archive/hotfix/slug_length.zip
```

**Comment by kynsi** [comment]
Yes, it works! Thanks.

**Comment by yakky** [comment]
Thanks @kynsi merged!
