### ISSUE TITLE
Notify the user if the slug is already taken

### ISSUE THREAD

**Issue by fmarco** [nephila/djangocms-blog#421]
See issue #415 and comments on PR #418.

If a user creates a post giving an already taken slug, the app should give some notification about the fact that the final one is created starting from the provided one by the user.

**Comment by pupattan** [comment]
Please fix this issue

**Comment by yakky** [comment]
@pupattan not sure when I will have the bandwidth to handle this, but it's definitely something that should be improved

**Comment by protoroto** [comment]
@yakky This should be closed, issue is resolved for both wizard and admin form.
