### ISSUE TITLE
Question: reuse placeholder from parent page in posts?

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#425]
I have a regular django-cms page where I've added a latest-articles plugin. It only shows articles of a certain category. Underneath this list I have a placeholder, for instance an advertorial. 
I want this same placeholder/advertorial to show up beneath each post that is selected in the plugin. Is this possible? Djangocms has an "inherit" feature for placeholders but this doesn't work.

**Comment by yakky** [comment]
@kynsi If I understand correctly what you want to achieve, have a look at static placeholders (https://docs.django-cms.org/en/release-3.4.x/how_to/templates.html#static-placeholder)
If you need further help, feel free to join the [gitter root](https://gitter.im/nephila/applications)

**Comment by kynsi** [comment]
No, I meant using placeholders from certain pages only, but I've managed to get it working using [show_placeholder](http://docs.django-cms.org/en/release-3.4.x/reference/templatetags.html#show-placeholder)

**Comment by yakky** [comment]
Thanks for reporting the solution
