### ISSUE TITLE
Request: plugin for selectable posts

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#428]
The blog is working out nicely but it would be nice to have a list plugin where you can define the number of posts and manually choose a post for each position. So a bit like the latest posts plugin but not filled based on publish-date but manually.

**Comment by yakky** [comment]
This is something I was just thinking about in the past weeks. I lack time to implement this, but I think that a sorted-m2m enabled plugin that allow to choose posts would be a really nice idea to add

**Comment by kynsi** [comment]
Yeah, that would be great! I'm afraid I lack the skills to write this, but I'll give it a go.

**Comment by protoroto** [comment]
@yakky Should we create a `BlogFeaturedPlugin` with a sorted-m2m ? I think it would be useful.
