### ISSUE TITLE
cmsplugin-filer is deprecated addons

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#431]
**cmsplugin-filer** is in setup.py `install_requires`

But it's a deprecated addons, see: http://docs.django-cms.org/en/latest/topics/commonly_used_plugins.html#deprecated-addons

And can result in problems like:

- https://github.com/divio/django-cms/issues/6198#issuecomment-352729551

What's about a migration to a core addon?

**Comment by yakky** [comment]
It's been left in 0.9 just to ease the migration to filer ThumbnailOption.
Requirement for external django CMS plugin will be removed in 1.0 (which is due soon, and will drop really old compatibilities)

**Comment by jedie** [comment]
get a 404

**Comment by wfehr** [comment]
Created the gist new, made a little mistake, should work now.

**Comment by jedie** [comment]
Think all deprecated cmsplugin should include the "own" migration!

**Comment by yakky** [comment]
FYI: djangocms-blog included cmsplugin-filer only for the purpose of thumbnail option. The migration from cmspluginfiler-image `ThumbnailOption` to filer `ThumbnailOption` has been completed in the 0.8.x version. We kept cmsplugin-filer-image dependency in 0.9 to ease the migration from early 0.8.x version directly to 0.9 (basically to keep the migrations historical models consistent)
In 1.0 will be dropped, but **no** further migration will be needed. We will just remove the compatibility code which is already no longer used in 0.9 anyway

**Comment by yakky** [comment]
Linked PR drops cmsplugin-filer, documentation is updated to document the migration path
