### ISSUE TITLE
missing migrations

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#432]
```
+ ./manage.py makemigrations --dry-run
Migrations for 'djangocms_blog':
  .../site-packages/djangocms_blog/migrations/0033_auto_20180226_1218.py
    - Alter field meta_description on blogcategorytranslation

```

**Comment by yakky** [comment]
Ouch :man_facepalming: 
PR opened
I will likely release a patch version to fix this

**Comment by yakky** [comment]
Fixed in 0.9.2, released today
Thanks @jedie for reporting this

**Comment by jedie** [comment]
btw. in one of my projects i add a test for it and check the output of "makemigrations --dry-run" ;)

**Comment by yakky** [comment]
Yes, that would be the right thing to do
PR welcome, if you would like to share the test :)
