### ISSUE TITLE
Wizard generates error in Django 1.11

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#435]
If I create a new post with the wizard I get the following error when saving:

`AttributeError at /cms_wizard/create/
This QueryDict instance is immutable`

django = 1.11.11
djangocms = 3.5.1
djangocms-blog = 0.9.2

**Comment by yakky** [comment]
@kynsi which version of django-appdata and aldryn-apphooks config have you installed?

**Comment by kynsi** [comment]
django-appdata==0.2.0
aldryn-apphooks-config==0.3.3

**Comment by yakky** [comment]
Does this branch of aldryn-apphooks-config fixes your issues https://github.com/aldryn/aldryn-apphooks-config/archive/feature/django11.zip ?

**Comment by kynsi** [comment]
Unfortunately not. I looked in the debug-info and found this error:

`Error in formatting: AttributeError: 'WizardStep2Form' object has no attribute '_errors'`

**Comment by yakky** [comment]
:thinking: I will try to reproduce the issue
They way to trigger this is just to create a new post from the wizard, right?

**Comment by kynsi** [comment]
Yes, exactly.

**Comment by yakky** [comment]
Ok, I will try to get back to you soon

**Comment by kynsi** [comment]
Thanks. Let me know if you need any more information. I'll try a fresh testrun tomorrow.

**Comment by kynsi** [comment]
I just did fresh install in a new env (lxml is missing from the dependencies btw) and I get the same error.

**Comment by yakky** [comment]
@kynsi issue confirmed. A fix is on the way
Thanks for reporting this

**Comment by yakky** [comment]
@kynsi could you test the linked PR?
I'll be also adding explicit lxml dependency in #436

**Comment by kynsi** [comment]
Tested and works! Thanks!

**Comment by yakky** [comment]
@kynsi awesome. 0.9.3 is going to be released soon, then

**Comment by yakky** [comment]
@kynsi aldryn-apphooks-config 0.4.0rc1 has been released

**Comment by yakky** [comment]
Fixed by #437
