### ISSUE TITLE
Cannot create new  blog article

### ISSUE THREAD

**Issue by vutrongvu** [nephila/djangocms-blog#439]
When I create new blog article, Django cms have a error:
Django.template.loaders.filesystem.Loader: /app/microsoft_startups/templates/sortedm2m/sorted_checkbox_select_multiple_widget.html (Source does not exist)

infomation version:
Djnago: 1.10.1
Django-cms: 3.5+
Django-cms-blog: 0.9.2

**Comment by yakky** [comment]
Is sortedm2m into INSTALLED_APPS? Apparently there is an issue in building the docs, and they are outdated on readthedocs

**Comment by yakky** [comment]
@vutrongvu documentation updated http://djangocms-blog.readthedocs.io/en/release-0.9.x/installation.html

**Comment by yakky** [comment]
Thanks for reporting
