### ISSUE TITLE
Referenced  jQuery path doesn't exist in Django 1.9+

### ISSUE THREAD

**Issue by stefanw** [nephila/djangocms-blog#445]
The path `admin/js/jquery.js` referenced [in the CMS wizard](https://github.com/nephila/djangocms-blog/blob/7c31fc364d924b64824b28f6d0b2a1640b2e4982/djangocms_blog/cms_wizards.py#L49) doesn't exist anymore since Django 1.9 (and Django 1.8 is officially EOL since 1st of April 2018). This leads to a 404 (or a 500 when using ManifestStaticFileStorage).

The path in Django 1.9+ is `admin/js/vendor/jquery/jquery.js`. But possibly including a copy of jQuery in this repo might also be a solution.

**Comment by yakky** [comment]
For for reporting this. I think we should still rely on django own jquery, to avoid shipping multiple copies of jquery in a single project.
Setting the path according to the detected Django version is the best fix.

**Comment by yakky** [comment]
Thanks @stefanw  for reporting this
Fixed by #447 
It will be released in the next 0.9 release
