### ISSUE TITLE
HTMLField CKeditor settings

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#446]
Hello!

Is there any way to provide CKEditor settings to the HTML field for abstract?

**Comment by yakky** [comment]
It needs a small PR (see https://github.com/divio/djangocms-text-ckeditor/#customizing-htmlfield-editor for reference)
I will happily review a PR to add this

**Comment by petrklus** [comment]
ok @yakky - before I fork and create this as an option, is there any preference on how to initialise variables that are not found in settings?

Then I would imagine it would just go here: https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L230

**Comment by yakky** [comment]
@petrklus exactly. You don't need to provide defaults. It will fallback to the default one if a setting with the given name is not found. I'd call the setting something like `BLOG_ABSTRACT_CKEDITOR`. Maybe we can add this to the `post_text` field?
As for documentation, just a brief note in the global setting pointing to the djangocms-text-ckeditor documentation is fine, I think

**Comment by petrklus** [comment]
@yakky done at https://github.com/nephila/djangocms-blog/pull/448 - let me know your thoughts!

**Comment by petrklus** [comment]
Updated as requested @yakky https://github.com/nephila/djangocms-blog/pull/448

**Comment by yakky** [comment]
Fixed by #449
