### ISSUE TITLE
Posts list is empty.

### ISSUE THREAD

**Issue by dismine** [nephila/djangocms-blog#453]
Hi,

Sorry for newbie question, i am new to django cms, but i cannot properly configure a blog. I have two posts, i see them in menu. But blog home page and category page show me only "No article found.". Where is my mistake.

**Comment by dismine** [comment]
Because autodiscovery of url for apphook doesn't work in my case i define it manually like this:
`url(r'^blog/', include('djangocms_blog.urls')),`
This makes almost all work except of the posts list.

Tracing the issue lead me to `class BaseBlogView`, checking queryset result show that it is empty.

```
class BaseBlogView(AppConfigMixin, ViewUrlMixin):
...
    def get_queryset(self):
        language = get_language()
        queryset = self.model._default_manager.namespace(
           self.namespace
        ).active_translations(
           language_code=language
        )
        if not getattr(self.request, 'toolbar', False) or not self.request.toolbar.edit_mode:
            queryset = queryset.published()
        setattr(self.request, get_setting('CURRENT_NAMESPACE'), self.config)
        return self.optimize(queryset.on_site())
```

This is happening because namespace member is also empty. Switching code to 

```
 queryset = self.model._default_manager.active_translations(
     language_code=language
 )
```
Resolves the issue for me.

But i wonder which namespace **djangocms-blog** expects from me. I tried this:
`url(r'^blog/', include('djangocms_blog.urls', namespace='djangocms_blog')),`
The namespace member is not empty now, but request still returns empty result.

**Comment by yakky** [comment]
Sorry, I thought I have answered before to this
djangocms-blog is only supported when attaching it using apphooks
There are too many things that can go wrong otherwise
What's the problem with using apphooks?

**Comment by dismine** [comment]
> What's the problem with using apphooks?

Maybe you could help me, because in my case none of applications work with apphook fully. I mean i always forced to put a url manually.

**Comment by yakky** [comment]
@dismine what's the issue with apphooks exactly? does the runserver starts? 
What are the django CMS / Django / aldryn-apphooks-config versions?

**Comment by dismine** [comment]
@yakky thank you for your patience! I just have rechecked and all magically now fully work without need for manually defining urls or removing the namespace. I close this issue for now.

**Comment by yakky** [comment]
@dismine :tada: Great!
Feel free to add further comments if you encounter further issues

**Comment by dismine** [comment]
Can i use this place for dumb newbie questions too? :)

**Comment by yakky** [comment]
Use our gitter chat https://gitter.im/nephila/applications for questions :)
