### ISSUE TITLE
Pre-generate thumbnails to improve performance

### ISSUE THREAD

**Issue by danra** [nephila/djangocms-blog#459]
Currently, thumbnails are generated at run-time as needed using the `thumbnail` tag. Each time this tag is used, first the app must check if the thumbnail already exists on the media storage, and if not, generate it. When the media storage is remote such as on S3, this can take a lot of time.

It would be much more efficient to instead use the `thumbnail_url` tag which assumes the thumbnail already exists and just writes the appropriate url in the HTML. This just means the thumbnail should be pre-generated whenever the `thumbnail_options` for an image are modified.

There could be a switch to enable both the current dynamic and the pre-generating behavior, but since I don't see any advantage for the dynamic approach in the context of this package, I suggest just changing the behavior to always pre-genrate the thumbnails.

**Comment by danra** [comment]
It looks like I was wrong - for non-local storage, both the source and thumbnail generation time are queried in the database instead of querying the modification time of the file in the storage. (I'm still seeing this taking a significant time on page load with just a few thumbnails, but it's probably not due to remote storage access.)

**Comment by yakky** [comment]
@danra djangocms-blog uses `easy_thumbnails` for thumbnail generation, which caches the thumbnails status in the database and support async thumnails generation. If it's your use case, you can change the template to reflex this and have a look at `east_thumbnails` async pregeneration https://easy-thumbnails.readthedocs.io/en/stable/usage/#asynchronous-pregeneration
