### ISSUE TITLE
How to add "related posts" to template?

### ISSUE THREAD

**Issue by whyronimus** [nephila/djangocms-blog#460]
I have several posts which are related to each other, but I can't figure out how to actually display them. I'd like to let them show up beyond the blog post content, something like "you may find this interesting" and a list of the related posts. Is that possible or does it me require to write an extra plugin?

**Comment by whyronimus** [comment]
Never mind, found solution here. https://github.com/nephila/djangocms-blog/pull/360#issuecomment-359182127 (sorry, first post)

**Comment by yakky** [comment]
Thanks for pointing out that no doc /examples exist for this
Fixing with #471

**Comment by yakky** [comment]
I hope the upgraded documentation will help future needs
Thanks for reporting this
