### ISSUE TITLE
request.build_absolute_uri returns "http" URI despite https request for Posts

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#461]
I use django's ``request.build_absolute_uri``to add, e.g., the canonical URL to a page's head. That seems to work fine except for Post detail pages where I get a "http" URL. 

Other pages of djangocms-blog are not affected.

Thanks for any thoughts!

**Comment by fsbraun** [comment]
Sorry for wasting your time. I found the issue: Just an embarrassing template inheritance on my side.

**Comment by yakky** [comment]
@fsbraun no worries :)
And thanks for reporting the fix!
