### ISSUE TITLE
Video blog with djangocms-blog?

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#464]
I would like to add my video blog to my site using djangocms-blog. I imagine having the ability to add a YouTube link to the blog entry and automatically create links for the preview (e.g., if no blog image is selected).

Any thoughts on this? Alternative solutions?

Could potentially contribute to implement this.

**Comment by yakky** [comment]
@fsbraun how about using a standard djangocms-video plugin for this?
It might strech the blog purposes a bit too much, but I'm open to discuss ideas

**Comment by fsbraun** [comment]
@yakky Thank's for discussing! I am thinking of a way to then include a video still as image for the blog entry, potentially having the capability to start the video from the blog post list/lightbox above the blog post list.

Using a video plugin would require to check the blog content for such a plugin (and potentially there are more than one). My thinking is to include a video url just like the image in the blog post model: Would be available both in the the post list and the post detail views. 

Also, it might be technically possible to have a placeholder field in the blog post model and drop plugins there. But it seems to me that this would be very different from the current approach towards blog post images. Finally, I would need to think on how to create a light box.

**Comment by yakky** [comment]
@fsbraun how about a generic "linked content URL"? The template will then be able to handle in any way: it can be a video URL for a video blog, an audio streaming for a podcast or whatever
My concern here is to add very specific use cases to a generic applications

**Comment by fsbraun** [comment]
@yakky I like the idea (and also understand the concern)! Linked content URL could also be an image ... Will be happy to give it a shot!

**Comment by yakky** [comment]
@fsbraun awesome :smiley:

**Comment by whyronimus** [comment]
Is this feature available yet? It would be a "very nice to have".

**Comment by yakky** [comment]
Fixed by #490
