### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'safe_translation_getter'

### ISSUE THREAD

**Issue by wfehr** [nephila/djangocms-blog#465]
When **creating a post without any categories** applied (or existent) I am getting an AttributeError:
`'NoneType' object has no attribute 'safe_translation_getter'`

End of trace:

> Internal Server Error: /admin/r/65/61/
> Traceback (most recent call last):
> [...]
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
>     return view(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/contenttypes/views.py", line 31, in shortcut
>     absurl = get_absolute_url()
>   File "/usr/local/lib/python3.6/site-packages/djangocms_blog/models.py", line 352, in get_absolute_url
>     kwargs['category'] = category.safe_translation_getter(
> AttributeError: 'NoneType' object has no attribute 'safe_translation_getter'

Are you able to recreate this?

**Edit**:
Environment:
- django==1.11.12
- django-cms==3.5.2
- djangocms-blog==0.9.5

**Comment by wfehr** [comment]
Also tested it with djangocms-blog==0.9.7, same problem (just to be sure it isn't fixed with the last release).

**Comment by yakky** [comment]
@wfehr is this related to #297 ? what's the "Permalink structure:" of the apphook config?

**Comment by wfehr** [comment]
@yakky the structure is 'category', so yes, I think the mentioned issue is the problem of this one.

**Comment by yakky** [comment]
Fixed by #480 which will be released in 0.9.10
Thanks you all for reporting this
