### ISSUE TITLE
Unable to re-use a slug in a different app config

### ISSUE THREAD

**Issue by petrklus** [nephila/djangocms-blog#466]
Steps to reproduce:
1. Create two separate app configs in the system
2. Add post with a slug "test" in the app config 1
3. Add post with a slug "test" in the app config 2

An error message is then shown, which means there are two issues - first of all, the system does not allow the same slug to be re-used, also, the error message is shown twice:

![image](https://user-images.githubusercontent.com/1115667/47048201-fbd45c00-d199-11e8-95f0-e9db17132d3c.png)

Any tips what to do with this?

**Comment by petrklus** [comment]
@yakky any tips on the above, is that expected behaviour? I would understand the inability to re-use slugs, the double-error message should be there though.

**Comment by yakky** [comment]
@petrklus yes, the uniqueness is on purpose (enforced here https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L97)
It's been set before apphooks config were born and there is no sane way to enforce uniqueness between untranslated and translated fields
I agree that the double error message is wrong, looking into it

**Comment by yakky** [comment]
@petrklus it's actually a parler issue, as it runs both the custom uniqueness validation and the django one
I will push a temporary fix here, and will work on a more comprehensive solution on parler

**Comment by yakky** [comment]
@petrklus you have give a try to PR #472 for the quickfix, if you want to doublecheck

**Comment by yakky** [comment]
Fixed in #472
