### ISSUE TITLE
support for django-cms 3.6 with django 2.1

### ISSUE THREAD

**Issue by ceelian** [nephila/djangocms-blog#476]
Is djangocms-blog compatible with django-cms version 3.6 and django 2.1?

Regarding the docs (https://djangocms-blog.readthedocs.io/en/latest/) djangocms-blog supports django-cms version 3.4+ but also only django 1.1. 

We want to use django-cms with django 2.1, is this possible right now or are there any changes to be made to djangocms-blog to be compatible with django 2.1.

Thank you!

**Comment by fsbraun** [comment]
It seems that the required compatibility changes habe been made in Pull Request #475. @yakky is there a timeline for releasing these changes?

**Comment by yakky** [comment]
@ceelian @fsbraun sorry I've been very late at this
I will release 1.0 with django 2.1/django CMS 3.6 within this week
In the meantime I will release 1.0beta1 as per current develop as soon as #479 is merged

**Comment by yakky** [comment]
1.0b1 is out
Thanks for your patience

**Comment by fsbraun** [comment]
@yakky Thanks for your commitment to this project. We appreciate it!

**Comment by ceelian** [comment]
@yakky Thanks a lot!
