### ISSUE TITLE
Is there a most-popular posts plugin or similar?

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#485]
I am adding a sidebar to my post detail views with a static placeholder field. It would be nice to have a plugin that shows the x most popular posts. 

Does djangocms blog keep track on how often a post ist viewed? What other options are there to automatically offer some other posts (i.e., besides related posts)?

**Comment by yakky** [comment]
@fsbraun currenty there is not view counters for blog posts (and thus no plugin)

I have mixed feelings about adding one
