### ISSUE TITLE
Taggit and sortedm2m widgets broken

### ISSUE THREAD

**Issue by fsbraun** [nephila/djangocms-blog#486]
I have no idea if this is a problem of my setup. My taggit and sortedm2m widgets in a Post's admin form are broken. It seems that admin forms load jquery after the widget's css. Anyone has a similar experience?

Thanks, Fabian

**Comment by fsbraun** [comment]
It seems that django admin does load its copy of jquery after taggit_autosuggest and after the sortedm2m widgets. So this seems to be a django admin issue which I frankly haven't figured out. (Might be my misconfiguration or potentially my upgrade to Django 2.1.) Despite the possibility, the issue does not belong here, I'd share the workaround I found. You have to add two files to the project's templates and static files:

``templates/admin/inc/extrahead.html``:

    {% load static %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>

and ``static/admin/js/jquery.init.js``:

    var django = django || {};
    if ( typeof ( django.jQuery ) == 'undefined' )
        django.jQuery = jQuery.noConflict(true);

These load jquery into django's namespace and - unlike the original ``jquery.init.js?`` preserve installed extensions (like those for taggit and sortedm2m) from being overwritten by django's reloading jquery later on the page.

**Comment by yakky** [comment]
I know that django CMS does its trickery do resolve the same issue in plugins

that change in django 2.1 broke a lot of stuff on my side too but I have not came up with a solution cleaner than yours
