### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by aksthelion** [nephila/djangocms-blog#488]
Python 3.7.3
django version 2.2.1

I'm getting this error after running 
python3 manage.py migrate

TypeError: __init__() missing 1 required positional argument: 'on_delete'

How to fix it?

**Comment by fsbraun** [comment]
@aksthelion I believe, since django 2.0, the ``on_delete`` parameter for foreign keys is required (whereas in earlier versions the default was ``models.CASCADE``. This makes migrations created in earlier versions of django throw the error on the required argument.

To fix this, add ``on_delete = models.CASCADE`` in all migrations causing the error.

Good luck!

**Comment by aksthelion** [comment]
It is models.CASCADE. I tried few solutions suggested on stackexchange but none worked.

**Comment by fsbraun** [comment]
I am not sure if your problem is solved. Did ``on_delete=models.CASCADE`` help?

**Comment by aksthelion** [comment]
No it didn't solve. I gave up.

**Comment by antnieszka** [comment]
After adding `on_delete=modelsCASCADE` it throws:

```
lib\site-packages\djangocms_blog\models.py", line 13, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by yakky** [comment]
@aksthelion @antnieszka which version of django CMS blog are you using?

1.0beta1 is compatible with Django 2.0 and up, earlier version are not

**Comment by antnieszka** [comment]
@yakky it might have been 0.9.9. I just installed latest from pypi at the time. I'll check 1.0beta1 in my spare time, thanks!

**Comment by antnieszka** [comment]
1.0beta1 seems to work fine for me. One thing to get this working was to remove `cmsplugin-filer` as stated somewhere in README

**Comment by yakky** [comment]
@antnieszka thanks for the feedback :+1: 
I am closing this
