### ISSUE TITLE
Configure Cache-Control

### ISSUE THREAD

**Issue by SteveGZr** [nephila/djangocms-blog#489]
I'm trying to configure caching in djangocms-blog.
I read through the documentation and through the code, but I couldn't find a way to configure it.

In normal django I use the following decorator for a view.
  
    @method_decorator(cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS),`
                      name='dispatch')`
    class ExampleView():

I can't do this as there are no views. Now I was wondering if there is a way to achieve the same with djangocms-blog?

**Comment by SteveGZr** [comment]
Here is a workaround for those trying to setup cache-control without having own Views:

`urls.py:`

Instead of importing directly from `djangocms_blog.views` import from your own `.views`
 
    from .views import CategoryEntriesView, PostDetailView, PostListView

`views.py:`

Create a `views.py` in which you do something like the following:

    from django.utils.decorators import method_decorator
    from django.views.decorators.cache import cache_control
    from djangocms_blog.views import (
        CategoryEntriesView, PostDetailView, PostListView,
    )

    from app.settings import CACHE_MIDDLEWARE_SECONDS as MAX_AGE
    
    
    @method_decorator(cache_control(max_age=MAX_AGE), name='dispatch')
    class CategoryEntriesView(CategoryEntriesView):
        pass


    @method_decorator(cache_control(max_age=MAX_AGE), name='dispatch')
    class PostDetailView(PostDetailView):
        pass


    @method_decorator(cache_control(max_age=MAX_AGE), name='dispatch')
    class PostListView(PostListView):
        pass

**Comment by yakky** [comment]
Probably it's easier to decorate the shipped views by providing a custom urlconf (https://djangocms-blog.readthedocs.io/en/latest/features.html#provide-a-custom-urlconf) and decorating the views there https://docs.djangoproject.com/en/2.2/topics/class-based-views/intro/#decorating-in-urlconf
