### ISSUE TITLE
Django-parler 2.0 causes a migration isue.

### ISSUE THREAD

**Issue by BenMemberg** [nephila/djangocms-blog#494]
I upgraded django-parler to version 2.0 and it caused djangocms-blog to require a new migration. Reversing the django-parler version back to 1.9.2 solves this issue. 
Here is the auto-generated migration file:
[djangocms-blog_auto_migration.log](https://github.com/nephila/djangocms-blog/files/3443978/djangocms-blog_auto_migration.log)

Operating System: Ubuntu 18.04
Related Package versions: django==1.11.22, django-cms==3.4.6, djangocms-blog==0.9.10, django-parler==2.0

**Comment by yakky** [comment]
thanks for the heads up
I will check this and if any 1.9 / 2.0 compatible solution exists

**Comment by yakky** [comment]
Fixed by #496 
I will release 0.9.11 soon

**Comment by yakky** [comment]
@BenMemberg added the extra migration for djangocms-blog 1.0
