### ISSUE TITLE
Feature Request: Optional Multilingual

### ISSUE THREAD

**Issue by leesolway** [nephila/djangocms-blog#50]
Would it be possible to make the multilingual setup optional? 
Would it be accepted as a feature, if you didn't have time to implement?

**Comment by jedie** [comment]
btw. why the use of django-parler?!?

I'm a little confuse: djangocms has his **CMS_LANGUAGES** and django-parler his own **PARLER_LANGUAGES** and there is the normal django **LANGUAGES**

That a little redundant ;)

**Comment by yakky** [comment]
django CMS multilingual system is not reusable outside the CMS, while parler is a great tool to handle multilingual content, and it's very flexible, and in fact with a really nice integration path with django CMS.
Django by itself does not have any support for multilingual model, hence the need to external application to handle that

**Comment by jedie** [comment]
What's about a ```settings.py``` example with e.g. "de" and "en" as languages?!?

My current example: https://gist.github.com/jedie/00737f2778dd161d4252
maybe a little to mutch?!?

**Comment by yakky** [comment]
I'm pretty sure you must use a site id for parler when using django CMS (which uses Django sites).
It's a bit redundant, and actually it'd be pretty easy to write a wrapper that converts `CMS_LANGUAGES` to `PARLER_LANGUAGES` automatically (and even derive both for `LANGUAGES` if no special handling is needed)

**Comment by yakky** [comment]
Closing this, as now ``PARLER_LANGUAGES`` can be derived from ``CMS_LANGUAGES``
