### ISSUE TITLE
No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by marcingarbarczykapz** [nephila/djangocms-blog#514]
I have problem with install your app.
Error 1: 

> class FilerImage(CMSPlugin):
  File "C:\Users\Marcin\Envs\djangocmsdev\lib\site-packages\cmsplugin_filer_image\models.py", line 50, in FilerImage
    help_text=_('overrides width, height, crop and upscale with values from the selected thumbnail option'))   
TypeError: __init__() missing 1 required positional argument: 'on_delete'

After remove 'cmsplugin_filer_image' from installed apps:

> site-packages\djangocms_blog\models.py", line 13, in <module>    
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

Installed apps:

> INSTALLED_APPS = [
>     'djangocms_admin_style',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.admin',
>     'django.contrib.sites',
>     'django.contrib.sitemaps',
>     'django.contrib.staticfiles',
>     'django.contrib.messages',
>     'cms',
>     'menus',
>     'sekizai',
>     'treebeard',
>     'djangocms_text_ckeditor',
>     'filer',
>     'easy_thumbnails',
>     'djangocms_column',
>     'djangocms_file',
>     'djangocms_link',
>     'djangocms_picture',
>     'djangocms_style',
>     'djangocms_snippet',
>     'djangocms_googlemap',
>     'djangocms_video',
>     'djangocmsdev',
>     'aldryn_apphooks_config',
>     'cmsplugin_filer_image',
>     'parler',
>     'taggit',
>     'taggit_autosuggest',
>     'meta',
>     'sortedm2m',
>     'djangocms_blog',
> ]

Packages:
> aldryn-apphooks-config==0.5.2
> cmsplugin-filer==1.1.3   
> dj-database-url==0.5.0   
> Django==2.1
> django-appconf==1.0.3    
> django-appdata==0.2.1    
> django-classy-tags==0.9.0
> django-cms==3.6.0        
> django-filer==1.5.0
> django-formtools==2.1
> django-js-asset==1.2.2
> django-meta==1.5.2
> django-meta-mixin==0.3.0
> django-mptt==0.10.0
> django-parler==1.9.2
> django-polymorphic==2.0.3
> django-sekizai==1.0.0
> django-sortedm2m==2.0.0
> django-taggit==0.23.0
> django-taggit-autosuggest==0.3.8
> django-taggit-templatetags==0.2.5
> django-templatetag-sugar==1.0
> django-treebeard==4.3
> djangocms-admin-style==1.4.0
> djangocms-apphook-setup==0.3.0
> djangocms-attributes-field==1.1.0
> djangocms-blog==0.9.11
> djangocms-blogit==0.5.1
> djangocms-column==1.9.0
> djangocms-file==2.3.0
> djangocms-googlemap==1.3.0
> djangocms-installer==1.1.1
> djangocms-link==2.5.0
> djangocms-picture==2.1.3
> djangocms-snippet==2.1.0
> djangocms-style==2.2.0
> djangocms-text-ckeditor==3.7.0
> djangocms-video==2.1.1
> easy-thumbnails==2.6
> html5lib==1.0.1
> Pillow==6.2.0
> pytz==2019.3
> six==1.12.0
> sqlparse==0.3.0
> tzlocal==2.0.0
> Unidecode==1.0.23
> webencodings==0.5.1

Python 3.6.5

**Comment by pinksharpii** [comment]
I had this issue last night. I forced pip install version 1.0.0rc1 (the most current in github). It's a beta release but it's functional.

**Comment by marcingarbarczykapz** [comment]
@pinksharpii thank you for answer, but now I have another problem.

> BlogConfig matching query does not exist.

When I removed line

> {% show_menu 0 100 100 100 %}

Page works. I tried clear cache menu, restart server.

**Comment by yakky** [comment]
@marcingarbarczykapz 
Apparently taggit-autosuggest views are not added to the global urlconf 
Have you checked with the installation steps https://djangocms-blog.readthedocs.io/en/latest/installation.html#minimal-configuration ?

Some automatic initializations are done when first installing djangocms-blog and if they fails for whatever reason (like django version issues) the state might be inconsistent. Reinstalling django cms blog is usually the best option
