### ISSUE TITLE
Add new langauge to my blog

### ISSUE THREAD

**Issue by marcingarbarczykapz** [nephila/djangocms-blog#516]
Sorry for this basic question. I recently created a translation in my language for the blog (https://transifex.com). Can I use it by adding them to my project or do I have to wait for merge to master?

**Comment by yakky** [comment]
@marcingarbarczykapz first of all, thanks for the contribution!
I'm not sure you can pull those locally, but I can easily merge this in the repo

(actually it's to cut 1.0 release)

**Comment by marcingarbarczykapz** [comment]
Would be nice mate
