### ISSUE TITLE
Project Appears to Rely on Now-Defunct and Unsupported Libraries

### ISSUE THREAD

**Issue by artforlife** [nephila/djangocms-blog#518]
In particular, I have just tried to do a manual installation of DjangoCMS and DjangoCMS-Blog. The first part succeeded. However, the second part seems to run into some issues with `'cmsplugin_filer_image'`

> TypeError: __init__() missing 1 required positional argument: 'on_delete'

The plugins are no longer supported.
https://github.com/divio/cmsplugin-filer

My dependencies are as follows:

```
aldryn-apphooks-config     0.5.3              
certifi                    2019.9.11          
cmsplugin-filer            1.1.3              
Django                     2.1.14             
django-appconf             1.0.3              
django-appdata             0.2.2              
django-classy-tags         0.9.0              
django-cms                 3.7.0              
django-filer               1.5.0              
django-formtools           2.1                
django-js-asset            1.2.2              
django-meta                1.5.2              
django-meta-mixin          0.3.0              
django-mptt                0.10.0             
django-parler              1.9.2              
django-polymorphic         2.0.3              
django-sekizai             1.0.0              
django-sortedm2m           2.0.0              
django-taggit              0.23.0             
django-taggit-autosuggest  0.3.8              
django-taggit-templatetags 0.2.5              
django-templatetag-sugar   1.0                
django-treebeard           4.3                
djangocms-admin-style      1.4.0              
djangocms-apphook-setup    0.3.0              
djangocms-attributes-field 1.1.0              
djangocms-blog             0.9.11             
djangocms-column           1.9.0              
djangocms-file             2.3.0              
djangocms-googlemap        1.3.0              
djangocms-link             2.5.0              
djangocms-picture          2.3.0              
djangocms-snippet          2.2.0              
djangocms-style            2.2.0              
djangocms-text-ckeditor    3.8.0              
djangocms-video            2.1.1              
easy-thumbnails            2.6                
html5lib                   1.0.1              
Pillow                     6.2.1              
pip                        19.3.1             
pytz                       2019.3             
setuptools                 41.6.0.post20191030
six                        1.12.0             
sqlparse                   0.3.0              
Unidecode                  1.0.23             
webencodings               0.5.1              
wheel                      0.33.6      
```

When installed via djangocms-installer, the project seems to work. However, in that case it installs with Django==1.11, which is unacceptable and a separate issue (https://github.com/nephila/djangocms-installer/issues/353) of its own.

**Comment by yakky** [comment]
@artforlife djangocms-blog 0.9 install cmsplugin-filer only to allow upgrading from previous versions  (0.8.x) which used it, and it does not use anymore at runtime

djangocms-blog 1.0 is anyway in release which will drop the dependency entirely

**Comment by yakky** [comment]
@artforlife 1.0.0 has been released (https://pypi.org/project/djangocms-blog/1.0.0/) :tada:

**Comment by artforlife** [comment]
@yakky Thanks for your prompt response! I shall check it out again, based on your input.

Could you tell me if there is a place where I can see how djangocms-blog compares to the Aldryn NewsBlog? Perhaps there is a tutorial that builds out a blog or something similar to that.

I am currently using Aldryn NewsBlog for a project. However, since they have stopped the support, I need to make a decision of either trying to keep ANB up-to-date myself or switch to something like DjangoCMS-Blog altogether.

**Comment by yakky** [comment]
Actually I was not aware of the discontinued support for aldryn-newsblog
I will look into an upgrade path. It shouldn't be too hard as they both share the same foundation logic. 
Django CMS blog has been more focused on SEO flexibility, while aldryn-newsblog was more integrated with aldryn application family and its way to handle templates packages

**Comment by artforlife** [comment]
@yakky Sounds good. Please let me know what you find out. In the meantime, is there a live demo or tutorial for DjangoCMS-Blog?

**Comment by yakky** [comment]
I did not have time to prepare a demo, but I think I should :)

**Comment by artforlife** [comment]
That would be quite useful. Perhaps a tutorial illustrating how to build out a basic blog, similar to the one here:

http://support.divio.com/en/collections/2008550-archive#legacy-guide-how-to-build-a-website-and-blog-with-django-cms

**Comment by yakky** [comment]
I'll open a separate issue.
IDK when I will have some bandwidth for it, but I agree it would definitely help

I opened #521 to track this, thanks for the suggestion

Closing this issue as fixed by 1.0 release

**Comment by KnotaiG** [comment]
You did close this issue but in your current install document you have cmsplugin_filer_image in the INSTALLED_APPS list.

**Comment by yakky** [comment]
@KnotaiG I opened #523 to fix this

**Comment by artforlife** [comment]
Also, I think it is safe to assume that `aldryn_search` is going away as well. I have been trying to get it working with Django==2.1.7, CMS==3.7 to no avail. It currently does not support Django==2.x from my understanding.

**Comment by yakky** [comment]
I will check with the divio people what's their plan with `aldryn_search`. As there is no replacement for it, it would be a bummer if they plan to sunset it

**Comment by corentinbettiol** [comment]
(for people like me that still get to this issue: `aldryn_search 1.1.0` has been released, and is compatible with `django 2` :))
