### ISSUE TITLE
Error v1.0.0: cannot import name 'python_2_unicode_compatible' from 'filer.utils.compatibility'

### ISSUE THREAD

**Issue by swallace21** [nephila/djangocms-blog#522]
Error:
ImportError: cannot import name 'python_2_unicode_compatible' from 'filer.utils.compatibility'

The file that is calling it is from cmsplugin_filer_image/models
I added 'cmsplugin_filer_image' to INSTALLED_APPS per install instructions: 
https://djangocms-blog.readthedocs.io/en/latest/installation.html
Looks like the cmsplugin_filer is deprecated: https://github.com/divio/cmsplugin-filer

This is on a fresh django project.
I am running djangocms_blog 1.0.0

I was able to run it with commenting out: 'cmsplugin_filer_image', in INSTALLED_APPS

Great work and feature set btw! Thank you for putting this together.

**Comment by yakky** [comment]
@swallace21 thanks! Opened a pull request to fix installation docs
