### ISSUE TITLE
BlogConfig matching query does not exist

### ISSUE THREAD

**Issue by ionyshch** [nephila/djangocms-blog#532]
Ubuntu 18-04 in WSL (Windows 10 Pro)
Following manual instructions from [here](https://github.com/nephila/djangocms-blog/blob/develop/docs/installation.rst)

I missed publish web page step.

After stopping and starting server with `python manage.py runserver`
have non-working app.

> Environment:
> 
> 
> Request Method: GET
> Request URL: http://localhost:8000/en/
> 
> Django Version: 2.2.9
> Python Version: 3.6.8
> Installed Applications:
> ['djangocms_admin_style',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.admin',
>  'django.contrib.sites',
>  'django.contrib.sitemaps',
>  'django.contrib.staticfiles',
>  'django.contrib.messages',
>  'cms',
>  'menus',
>  'sekizai',
>  'treebeard',
>  'djangocms_text_ckeditor',
>  'filer',
>  'easy_thumbnails',
>  'djangocms_bootstrap4',
>  'djangocms_bootstrap4.contrib.bootstrap4_alerts',
>  'djangocms_bootstrap4.contrib.bootstrap4_badge',
>  'djangocms_bootstrap4.contrib.bootstrap4_card',
>  'djangocms_bootstrap4.contrib.bootstrap4_carousel',
>  'djangocms_bootstrap4.contrib.bootstrap4_collapse',
>  'djangocms_bootstrap4.contrib.bootstrap4_content',
>  'djangocms_bootstrap4.contrib.bootstrap4_grid',
>  'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
>  'djangocms_bootstrap4.contrib.bootstrap4_link',
>  'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
>  'djangocms_bootstrap4.contrib.bootstrap4_media',
>  'djangocms_bootstrap4.contrib.bootstrap4_picture',
>  'djangocms_bootstrap4.contrib.bootstrap4_tabs',
>  'djangocms_bootstrap4.contrib.bootstrap4_utilities',
>  'djangocms_file',
>  'djangocms_icon',
>  'djangocms_link',
>  'djangocms_picture',
>  'djangocms_style',
>  'djangocms_snippet',
>  'djangocms_googlemap',
>  'djangocms_video',
>  'aldryn_apphooks_config',
>  'aldryn_search',
>  'parler',
>  'taggit',
>  'taggit_autosuggest',
>  'meta',
>  'sortedm2m',
>  'djangocms_blog',
>  'mysite']
> Installed Middleware:
> ['cms.middleware.utils.ApphookReloadMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'cms.middleware.user.CurrentUserMiddleware',
>  'cms.middleware.page.CurrentPageMiddleware',
>  'cms.middleware.toolbar.ToolbarMiddleware',
>  'cms.middleware.language.LanguageCookieMiddleware']
> 
> 
> Template error:
> In template /home/ivan/trying-django-cms/first-project/mysite/mysite/templates/base.html, error at line 35
>    BlogConfig matching query does not exist.
>    25 :                 float: left;
>    26 :                 width: 20%;
>    27 :             }
>    28 :         </style>
>    29 :         {% render_block "css" %}
>    30 :     </head>
>    31 :     <body>
>    32 :         {% cms_toolbar %}
>    33 :         <div class="container">
>    34 :             <ul class="nav">
>    35 :                  {% show_menu 0 100 100 100 %} 
>    36 :             </ul>
>    37 :             {% block content %}{% endblock content %}
>    38 :         </div>
>    39 :         {% render_block "js" %}
>    40 :     </body>
>    41 : </html>
>    42 : 
> 
> Traceback:
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   34.             response = get_response(request)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   145.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   143.                 response = response.render()
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/response.py" in render
>   106.             self.content = self.rendered_content
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/response.py" in rendered_content
>   83.         content = template.render(context, self._request)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/backends/django.py" in render
>   61.             return self.template.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render
>   171.                     return self._render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in _render
>   163.         return self.nodelist.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render
>   937.                 bit = node.render_annotated(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   904.             return self.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/loader_tags.py" in render
>   150.             return compiled_parent._render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in _render
>   163.         return self.nodelist.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render
>   937.                 bit = node.render_annotated(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   904.             return self.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/classytags/core.py" in render
>   153.         return self.render_tag(context, **kwargs)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/sekizai/templatetags/sekizai_tags.py" in render_tag
>   89.         rendered_contents = nodelist.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render
>   937.                 bit = node.render_annotated(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   904.             return self.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/classytags/core.py" in render
>   153.         return self.render_tag(context, **kwargs)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/cms/templatetags/cms_tags.py" in render_tag
>   447.             return toolbar.render_with_structure(context, nodelist)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/cms/toolbar/toolbar.py" in render_with_structure
>   477.         rendered_contents = nodelist.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render
>   937.                 bit = node.render_annotated(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   904.             return self.render(context)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/classytags/core.py" in render
>   153.         return self.render_tag(context, **kwargs)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/classytags/helpers.py" in render_tag
>   88.                 flatten_context(self.get_context(context, **kwargs))
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/menus/templatetags/menu_tags.py" in get_context
>   144.             nodes = menu_renderer.get_nodes(namespace, root_id)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/utils/functional.py" in __wrapper__
>   152.                 return getattr(res, method_name)(*args, **kw)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/menus/menu_pool.py" in get_nodes
>   226.         nodes = self._build_nodes()
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/menus/menu_pool.py" in _build_nodes
>   177.                 nodes = menu.get_nodes(self.request)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/djangocms_blog/cms_menus.py" in get_nodes
>   51.                     namespace=self.instance.application_namespace
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
>   82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
> 
> File "/home/ivan/trying-django-cms/env/lib/python3.6/site-packages/django/db/models/query.py" in get
>   408.                 self.model._meta.object_name
> 
> Exception Type: DoesNotExist at /en/
> Exception Value: BlogConfig matching query does not exist.

**Comment by yakky** [comment]
@ionyshch on which page you added the blog apphook?

**Comment by ionyshch** [comment]
I created a new page titled “blog” and in advanced settings added blog application

**Comment by yakky** [comment]
@ionyshch so you have something like this, right? Have you published the CMS page after adding the blog apphook?

![image](https://user-images.githubusercontent.com/714711/71324236-ac479980-24dc-11ea-8510-95af5129c1b4.png)

**Comment by ionyshch** [comment]
I'm not sure about "Attached menu" and if I entered anything there.
Now I can't check as app is broken.

**Comment by yakky** [comment]
@ionyshch could you check by removing the apphook and adding it back again?

Run `python manage.py cms uninstall apphooks BlogApp` and add it again to check if it works

**Comment by ionyshch** [comment]
Thanks @yakky 
I removed apphook with command provided. Then published blog page and added blog application to it and chose "Blog menu" - both in advanced page settings. Now it fails with the same error and removing apphook doesn't help.

**Comment by yakky** [comment]
@ionyshch would you jump into gitter (https://gitter.im/nephila/applications) later?
anyway you can run these two queries on the database to make a low level check:

``` SQL
select namespace from djangocms_blog_blogconfig;
select distinct application_namespace from cms_page;
```

You should get something like

```
sqlite> select namespace from djangocms_blog_blogconfig;
Blog
sqlite> select distinct application_namespace from cms_page;

Blog
sqlite> 
```

Have you created the blog configuration yourself or it's been autocreated by djangocms blog at startup?

**Comment by ionyshch** [comment]
@yakky my initial expectations that miserably failed were that using django cms and plugins for it is user friendly i.e. it will just work. Reality turned out to include dozens of manual steps about that I'm not sure what I did what didn't e.g. what "create blog configuration" means.

I'm still don't know how to use autocreate feature: what are preconditions and how do I know it worked or didn't work.

I created blog configuration manually I guess (if it means performing manually steps described in Minimum Configuration section). If recommended (and easier way) is to use autocreate, then it should be before manual configuration and referred to as "recommended" way.

First query returns nothing (0 rows), second query returns as two rows: NULL and djangocms_blog.

**Comment by yakky** [comment]
When the project is run with django cms blog installed, it should autoconfigure itself, creating a blog page with the correct apphook and configuration setup
For some reason this does not happen on your setup.
We are working to make installation almost automatic and improve setup documentation (see #521 )
How did you installed django-cms? Have you used djangocms installer (as documented here https://django-cms.readthedocs.io/en/latest/introduction/01-install.html#use-the-django-cms-installer)?

**Comment by yakky** [comment]
I have writted a basic extension to djangocms installer to install and configure djangocms during the project creation process: 

```
pip install https://github.com/nephila/djangocms-installer/archive/feature/addons.zip
djangocms -a blog mysite
cd mysite
python manage.py runserver
```
This is currently untested and undocumented, by any feedback would be invaluable

**Comment by CWeasel** [comment]
Hey Yakky,

Seeing the silence on the above matter, I think the previous guy left the project.
However, i have the same issue as described above.
Unlike the advice you gave him, I commented out the menu tag and changed the "attached menu" to "Blog Menu".
From that point I attached the menu in my master template once more and it displayed correctly.

I do however have an issue with a new thing...
After I create an article and try to display it I get the following error: 
`

Request Method: | GET
-- | --
http://127.0.0.1:8000/en/blog/
2.2.9
NoReverseMatch
'Blog' is not a registered namespace
F:\Projects\DjangoCMS\Sites\venv\lib\site-packages\django\urls\base.py in reverse, line 86
F:\Projects\DjangoCMS\Sites\venv\Scripts\python.exe
3.7.3
`
I can send over the entire error if you please.
Now, when I have tried your extension above. The site sets up and runs correctly.
But when I have a DjangoCMS site already in place an add the Djangocms-blog, then it seems like it misses parts during the installation.
I have tried on separate occasions and sadly both led to the same result.
Attaching a blog to an existing site seems to fail.

If there is anything I can do to help, let me know.

**Comment by yakky** [comment]
@CWeasel thanks for your detailed information. Could you share your settings.py?
What if you set `BLOG_AUTO_SETUP = False`?
I will try to follow the setup instruction with a fresh mind, but I am puzzled by the failure, but I tend to think that autosetup is the culprit
Anyway we are reviewing the setup instruction to catch such errors

**Comment by CWeasel** [comment]
Hey Yakky, 
I would believe the same about the "autosetup".
Below the setting file:

```
import os  # isort:skip
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for weaselworks project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Diz-be-secret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition





ROOT_URLCONF = 'weaselworks.urls'



WSGI_APPLICATION = 'weaselworks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Brussels'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'weaselworks', 'static'),
)
SITE_ID = 1


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'weaselworks', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]


MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'weaselworks',
]
INSTALLED_APPS.extend([
    'djangocms_resume'
])

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
    ('es', gettext('es')),
)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'es',
            'name': gettext('es'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}

CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('cv-page.html', 'Example Resume Page'),
    ('cv-base.html', 'Interactive Resume Page')
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
```

I'll take a look at the BLOG_AUTO_SETUP = false.

**Comment by g3rb3n** [comment]
Same problem here with:
Django==2.2.10
django-cms==3.7.1
djangocms-blog==1.0.0

sqlite> select namespace from djangocms_blog_blogconfig;
Blog
sqlite> select distinct application_namespace from cms_page;
blog
Blog

It failed on the template tag show_menu 0 100 0 0.
self.instance.application_namespace on line 51 of cms_menus.py gave 'blog'. Changing it to 'Blog' with `self.instance.application_namespace = 'Blog' seems to solve the problem.

I removed the blog page and recreated it with Blog in the Application instance name setting. This seems to work correctly.

Changing this value in advanced settings does not seem to work. Before it always gave errors, now I have entered 'Blog' it does not give errors but also it always stays 'Blog'.

Database now has:
sqlite> select namespace from djangocms_blog_blogconfig;
Blog
sqlite> select distinct application_namespace from cms_page;
Blog

Hope this is of any help.

**Comment by jsandovalc** [comment]
Hi.
I seem to be having the same problem. I tested all the suggestions here, and nothing seems to work.

@g3rb3n you mean I should change the djangocms-blog code first and set that variable to 'Blog'?.

Thanks for any help.

**Comment by yakky** [comment]
> sqlite> select namespace from djangocms_blog_blogconfig;
> Blog
> sqlite> select distinct application_namespace from cms_page;
> blog
> Blog
> 
> It failed on the template tag show_menu 0 100 0 0.
> self.instance.application_namespace on line 51 of cms_menus.py gave 'blog'. Changing it to 'Blog' with `self.instance.application_namespace = 'Blog'` seems to solve the problem.
> 
> I removed the blog page and recreated it with Blog in the Application instance name setting. This seems to work correctly.
> 
> Changing this value in advanced settings does not seem to work. Before it always gave errors, now I have entered 'Blog' it does not give errors but also it always stays 'Blog'.
> 
> Database now has:
> sqlite> select namespace from djangocms_blog_blogconfig;
> Blog
> sqlite> select distinct application_namespace from cms_page;
> Blog

Thanks for posting this.
This is definely something in autosetup doing the wrong thing.

I will check how to reproduce and fix this

**Comment by g3rb3n** [comment]
Encountered this bug once more
```
sqlite> select namespace from djangocms_blog_blogconfig;
Blog
Heros
sqlite> select distinct application_namespace from cms_page;

Blog
djangocms_blog
```

If I try to add namespace Heros to a page I receive an error 
> Please correct the error below. 
But there are no errors below.

If I try to add Blog / Blog to a page I received an error 
> Please correct the error below.
With below
> An application instanance with this name already exists

What is the intended behavior?
Should one be able to attach an existing application instance?
Should a new application instance be created?

**Comment by g3rb3n** [comment]
There is a hidden form field: application_configs

This is causing trouble. The error is on this field, but since the parent html element is hidden, the error is not visible.

**Comment by g3rb3n** [comment]
Steps to reproduce
* Create page 'Blog'
* Create page 'News'
* Edit page advanced 'Blog' select application Blog and fill in namespace 'Blog' and press Save
* Edit page advance 'News' select application Blog and fill in namespace 'Blog' and press Save
* Now a page with form message 'Please correct the error below.' and application_namespace message 'An application instance using this configuration already exists.' should appear.
* Fill in namespace 'News' and press Save
* Now a page with form message 'Please correct the error below.' and application_config message 'An application instance using this configuration already exists.' is hidden in the form.

**Comment by yakky** [comment]
@g3rb3n awesome, thanks for the detailed steps, I will check this ASAP

**Comment by g3rb3n** [comment]
@yakky I have a test case for this. 

I have some question:
What is the intended behavior?
Should one be able to attach an existing application instance?
Should a new application instance be created?

```
        if "app_config" in self.fields:
            # Don't allow app_configs to be added here. The correct way to add an
            # apphook-config is to create an apphook on a cms Page.
            self.fields["app_config"].widget.can_add_related = False
```
I think that answers the last question as 'No'

Why don't we just show the select instead of a text field?

**Comment by g3rb3n** [comment]
```
        self.assertEqual(BlogConfig.objects.count(), 2)

        page = create_page('Blog', 'blog.html', 'en')
        self.add_blog_config(page, 'Blog', 1)
        response = self.add_blog_config(page, 'Blog', 1)
        content = force_str(response.content)
        self.assertNotRegex(content, r'Please correct the error below.')
        self.assertEqual(BlogConfig.objects.count(), 2)
```
Some how this passes, while it should not...
The page is modified and a non existing application namespace is specified. This causes all the other trouble mentioned above.

**Comment by g3rb3n** [comment]
See https://github.com/g3rb3n/djangocms-blog/tree/bugfix/issue-532

**Comment by g3rb3n** [comment]
@yakky One other thing. What to do when things fail? Now thing fail hard. What do you think about including logging to report errors to the console? Maybe we can provide some default output or some cleaner error handling to the front end too?

**Comment by yakky** [comment]
> if "app_config" in self.fields:

You can't create new configs before attaching them to a django CMS, as the reverse (aka the blog post absolute url) will fail

**Comment by yakky** [comment]
> @yakky I have a test case for this.
> 
> I have some question:
> What is the intended behavior?
> Should one be able to attach an existing application instance?
> Should a new application instance be created?
> 
> ```
>         if "app_config" in self.fields:
>             # Don't allow app_configs to be added here. The correct way to add an
>             # apphook-config is to create an apphook on a cms Page.
>             self.fields["app_config"].widget.can_add_related = False
> ```
> 
> I think that answers the last question as 'No'
> 
> Why don't we just show the select instead of a text field?

You can't create new configs before attaching them to a django CMS, as the reverse (aka the blog post absolute url) will fail
appconfig selection in djangocms-blog is a select, you do see a text field instead?

**Comment by g3rb3n** [comment]
Seems to be a combination of this code and firefox.
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/widgets/forms.apphookselect.js

Executing the following in the console, fixes the problem:
```
var apphooks_configuration = window.apphooks_configuration || {};
var appHooks = $('#application_urls, #id_application_urls');
var selected = appHooks.find('option:selected');
var appNsRow = $('.form-row.application_namespace, .form-row.field-application_namespace');
var appNs = appNsRow.find('#application_namespace, #id_application_namespace');
var appCfgsRow = $('.form-row.application_configs, .form-row.field-application_configs');
var appCfgs = appCfgsRow.find('#application_configs, #id_application_configs');
var appCfgsAdd = appCfgsRow.find('#add_application_configs');
var original_ns = appNs.val();
var opt = $(appHooks).find('option:selected');

if ($(appCfgs).length > 0 && apphooks_configuration[opt.val()]) {
    appCfgs.html('');
    console.log(apphooks_configuration[opt.val()].length)
    for (var i = 0; i < apphooks_configuration[opt.val()].length; i++) {
        var selectedCfgs = '';

        if (apphooks_configuration[opt.val()][i][0] === window.apphooks_configuration_value) {
            selectedCfgs = 'selected="selected"';
        }
        appCfgs.append(
            '<option ' + selectedCfgs + ' value="' + apphooks_configuration[opt.val()][i][0] + '">' +
                apphooks_configuration[opt.val()][i][1] +
            '</option>'
        );
    }
    appCfgsAdd.attr('href', window.apphooks_configuration_url[opt.val()] +
        // Here we check if we are on django>=1.8 by checking if the method introduced in that version
        // exists, and if it does - we add `_popup` ourselves, because otherwise the popup with
        // apphook creation form will not be dismissed correctly
        (window.showRelatedObjectPopup ? '?_popup=1' : ''));
    appCfgsRow.removeClass('hidden');
    appNsRow.addClass('hidden');
} else {
    appCfgsRow.addClass('hidden');
    if (opt.data('namespace')) {
        appNsRow.removeClass('hidden');
    } else {
        appNsRow.addClass('hidden');
    }
}
```

**Comment by g3rb3n** [comment]
@yakky Yes, I usually saw just a text field. Sometimes it became a select box...

**Comment by yakky** [comment]
But you mean in the Django CMS page advanced setting? Application name model field is a string as it holds the Django namespace for the urlconf, this it must be a text field. The custom select widget maps the application config namespace in it
On the Django CMS side there is no check that the appconfig namespace exists, because there is no sanity check due to the way Django namespaces work

**Comment by g3rb3n** [comment]
Indeed on /en/admin/cms/page/1/advanced-settings/

There is some complex logic in the UI. There is a select#application_configs and a input#application_namespace. On some conditions one of the two is hidden. 

If I have not edited the advanced settings and select Blog as app, then I get:
* firefox: input#application_namespace
* chromium: select#application_configs

Besides this I can mess up the database with firefox by entering a typo in the input#application_namespace field. This is what happened the first time, entered 'blog' instead of 'Blog'. After this the menu templatetag throws errors.

So I think we have two issues here.
* django-cms UI code that behaves different on firefox and chromium
* djangocms-blog that makes a complete site fail if a page is connected to a blog namespace and if someone is using firefox and makes a typo, or if a BlogConfig is deleted

I have a fix for the second issue. I will push and do a pr!

**Comment by yakky** [comment]
I can reproduce the first one
I opened https://github.com/divio/django-cms/issues/6853 on django CMS

**Comment by yakky** [comment]
And a fix is ready https://github.com/divio/django-cms/pull/6854

**Comment by g3rb3n** [comment]
Cool. I did not notice it was actually the first line that failed.
