### ISSUE TITLE
Installing with djangocms-blog[search] fails for django >= 2

### ISSUE THREAD

**Issue by taut-and-yare** [nephila/djangocms-blog#537]
`pip install djangocms-blog[search]` fails for django >= 2 due to a requirement from aldryn-search (currently v1.0.1) : `Django>=1.8,<2.0` 
https://github.com/divio/aldryn-search/blob/1.0.1/setup.py

**Comment by yakky** [comment]
@taut-and-yare as aldryn-search  is required to make search work, there is no solution until a django 2 compatible release is issued for aldryn-search. It's one of the reason why it's an optional dependency

**Comment by taut-and-yare** [comment]
@yakky OK - just one thing I noticed: the `Django<2 `requirement is no longer there on the master branch of [aldryn-search](https://github.com/divio/aldryn-search/blob/master/setup.py). However, there's non tagged version of that on their repo.

**Comment by yakky** [comment]
@taut-and-yare yes, they have not released on pypi the current master (which is compatible with django 2+). Until such version does not exist on pypi, we can't do much.
You can try pinging them for a release on https://github.com/divio/aldryn-search/issues/102

**Comment by yakky** [comment]
Fixed by aldryn-search release
