### ISSUE TITLE
Error message for duplicate slug causes confusion

### ISSUE THREAD

**Issue by g3rb3n** [nephila/djangocms-blog#545]
Steps to reproduce.
On blog post create form:
End user enters a title
From the title a slug is derived automatically
User tries to post the form
User receives an error message "Blog article translation with this Language and Slug already exists."

User enters another title
The slug field is not updated
User tries to post the form
User receives same error message "Blog article translation with this Language and Slug already exists."

Expected behavior:
When the slug is not entered manually, recreate the slug based on the newly entered title.

**Comment by yakky** [comment]
@g3rb3n unfortunately this is the default behavior of the django admin `prepopulated_fields`: once is set on first form submit, it's no longer updated automatically  if the title is updated. We can improve the error message and highlight the title and slug fields, and we can possibly move the slug field beneath the title to make easier for the user to change both

**Comment by g3rb3n** [comment]
@yakky Would be nice to stick with the default django admin behavior. DjangoCMS has the slug field directly below the title. In the Post admin form there is some room after subtitle for a slug. I guess the error message would be clear enough if the slug field is visible.

If you agree on this, I can spend some time to make the changes.

**Comment by yakky** [comment]
@g3rb3n I totally agree with you. It would be awesome if you could handle this

**Comment by g3rb3n** [comment]
@yakky On it.

**Comment by yakky** [comment]
@g3rb3n great!

be aware that we merged a PR which completely changed our code style. You will want to sync with develop to be up-to-date with the current codebase

**Comment by yakky** [comment]
Fixed by #567 by moving the field and making easier for the editors to spot the slug field to be edited
