### ISSUE TITLE
Inconsistencies in displaying multilingual URLs when fallback languages are enabled

### ISSUE THREAD

**Issue by jasujm** [nephila/djangocms-blog#546]
I'm using djangocms-blog for a bilingual site (English and Finnish). In the site's settings, I have defined that either language can be used as the other's fallback (http://docs.django-cms.org/en/latest/topics/multiple_languages.html). This causes some inconsistent behavior when displaying URLs of posts that only exist in one language in different contexts.

- A post only exists in English and I'm in a Finnish page containing apphook post list / latest posts plugin. The URL in the link is for the "Finnish version" of the post. When the link is followed, the site is showing the English content of the post as a fallback, but the URL, menus, etc. are in Finnish.

- I'm visiting the post in any language. The URL in the language chooser for the "Finnish language" version of the post is always the English language URL. This is my personal preference, as I consider the English URL as canonical in case I haven't translated the post to Finnish.

My expectation is: if a post only exists in one language, show the canonical URL (the URL of the English version in the above example) in every context. I solved this for my site by modifying the get_absolute_url() method of the `BlogPost` and `BlogCategory` models to also query the fallback language in case the current language doesn't yield a result. This way any link to the post is always in the same language as the content, regardless of the language of the page the link it appears in.

The (botched, largely untested) patch I wrote can be found here: https://github.com/jasujm/djangocms-blog/commit/cfa4c678dbf8b8baa35d307dd203e21acbbfe703

I'd like to have an opinion on how fallback languages should be handled in post listings and other contexts. To recap: The main options are

1. Page in language A is displaying a link to a post that only exists in language B. The URL points to a page "in language A". The page URL, menus, etc. are in language A, but the post content is in language B.

2. Page in language A is displaying a link to a post that only exists in language B. The URL is always to a page in language B. When followed, the page URL, menus in addition to the content of the post are in language B.

The patch I linked above essentially implements the second option. I'd be happy to clean up, properly test and contribute the patch if that's the preferred way.

**Comment by yakky** [comment]
@jasujm thanks for sharing your findings.
I am writing fro the top of my head (I will do further checks shortly), thus take this with a grain of salt.
The fallback mechanism used here is the parler's one, which should behave basically the same as the django CMS' one, but it's not 100% guaranteed. IIRC parler does not have the "redirect on fallback" options django CMS has (http://docs.django-cms.org/en/latest/reference/configuration.html#cms-languages)
Usually keeping the user context (so same URL language, menu etc) is preferred, which is the current blog behavior and option 1 in your list.
In django CMS the option 2 is managed via the `redirect_on_fallback` `CMS_LANGUAGES` option, which is not available on parler

The option to change the `get_absolute_url` is definitely handy and easier than implementing redirect at parler level. I would definitely accept to integrate option 2, as long as it's a configurable option

**Comment by yakky** [comment]
Fixed by #572
