### ISSUE TITLE
'BlogConfigWithAppDataForm' object has no attribute 'label_suffix'

### ISSUE THREAD

**Issue by atlonxp** [nephila/djangocms-blog#554]
I performed a clean installation of django-cms (latest-3.7.2) and later djangocms-blog (1.10). It is weird that the AutoSetup does not perform, so I run it manually. 

When I try to add BlogConfig, here is the error I found while rendering template. Tried to check where is BlogConfigWithAppDataForm. It is no where, unfortunately.

Request Method | GET
--|--
Request URL | http://localhost:8000/en/admin/djangocms_blog/blogconfig/add/
Django Version | 3.0.6
Exception Type | AttributeError
Exception Value | 'BlogConfigWithAppDataForm' object has no attribute 'label_suffix'
Exception Location | /Users/atlonxp/anaconda3/envs/iba-website/lib/python3.7/site-packages/django/contrib/admin/helpers.py in label_tag, line 190
--|--

`
**Error during template rendering**
In template /Users/atlonxp/anaconda3/envs/iba-website/lib/python3.7/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 15
`

At line 15, the statement is `{{ field.label_tag }}` but error said `'BlogConfigWithAppDataForm' object has no attribute 'label_suffix'`

so weird!. 

![Screen Shot 2020-05-07 at 11 20 10 PM](https://user-images.githubusercontent.com/38250872/81350192-4d647480-90b9-11ea-96a2-f9443f3a25ba.png)
Does anyone has this problem before?

**Comment by yakky** [comment]
@atlonxp thanks for reporting this
I will check the error and will provide feedback soon

**Comment by atlonxp** [comment]
@yakky can you please recommend which configuration is best at the moment?

**Comment by atlonxp** [comment]
I have just tested again. In this time, I have cleared browsing data on browsers e.g. Safari, Chrome, etc. 

The AutoSetup runs properly this time. It seems this is Django cache problem that is not clear even performing a clean installation. So, I have added dummy cache this time. I will let you know if this problem still exists.

**Comment by yakky** [comment]
@atlonxp I traced the `AttributeError` down to this PR https://github.com/ella/django-appdata/pull/23 (which I opened myself :D ) which is awaiting review
I will add a note on the readme regarding django 3 support, for now

**Comment by atlonxp** [comment]
@yakky migrate to Django 2.2.12, it works smoothly BlogConfig can be done manually.

**Comment by atlonxp** [comment]
With django 2.2.12 and djangocms-blog (latest), it seems work fine no error at all.

After I tried many scenarios, I found that 
+ sometimes AutoSetup does not run automatically
+ blog menu e.g. "Add new article" is missing at the creating page/sub page/create article

When I roll back to django 3.0.6
* blog menu is back
- same reported issues are back

**Comment by pupattan** [comment]
Any expected date to get ella/django-appdata#23  merged ?

**Comment by yakky** [comment]
Hopefully we will release django-appdata 0.3.0 today

**Comment by yakky** [comment]
> With django 2.2.12 and djangocms-blog (latest), it seems work fine no error at all.
> 
> After I tried many scenarios, I found that
> 
>     * sometimes AutoSetup does not run automatically
> 
>     * Advanced menu is missing while creating pages, but this can be done by creating page then change settings later in the advanced panel.
> 
>     * blog menu e.g. "Add new article" is missing at the creating page/sub page/create article
> 

Could you please open a separate issue for the menu errors?

**Comment by atlonxp** [comment]
Sure

**Comment by yakky** [comment]
thanks, closing this as solved by the release of django-appdata and aldryn-apphooks-config
