### ISSUE TITLE
aldryn_apphooks_config >>> python_2_unicode_compatible // Python 2 dependency prevents djangocms migration

### ISSUE THREAD

**Issue by cfd-manager** [nephila/djangocms-blog#556]
It looks like `aldryn_apphooks_config` tries to use `python_2_unicode_compatible` which was removed in python3. Any workaround? Otherwise it won't let me migrate the djangocms-blog changes..

Related SO thread:
https://stackoverflow.com/questions/61700135/importerror-after-installing-djangocms-blog-cannot-import-name-python-2-unicod/61700218?noredirect=1#comment109138079_61700218

> C:\Users\Jonas\Desktop\CFD\CFD>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aldryn_apphooks_config\models.py", line 5, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\encoding.py)

Thanks!

**Comment by yakky** [comment]
@cfd-manager thanks for reporting. the issue have been fixed in aldryn-apphooks-config 0.6 https://github.com/divio/aldryn-apphooks-config/pull/74

**Comment by yakky** [comment]
could you confirm that this is solved ?

**Comment by cfd-manager** [comment]
hmhm not sure (i'm not that experienced in coding). It seems that it installed django 2.2.12 when upgrading to aldryn 0.6, so this won't work with Django? Also i reinstalled djangocms-blog. Will try to do some more debugging tomorrow.

> C:\Users\Jonas\Desktop\CFD\CFD>pip3 install djangocms-blog
Collecting djangocms-blog
  Using cached djangocms_blog-1.1.0-py2.py3-none-any.whl (204 kB)
Requirement already satisfied: django-taggit-autosuggest in c:\users\jonas\appdata\local\programs\python\python
38-32\lib\site-packages (from djangocms-blog) (0.3.8)
Requirement already satisfied: djangocms-text-ckeditor>=3.5 in c:\users\jonas\appdata\local\programs\python\pyt
hon38-32\lib\site-packages (from djangocms-blog) (3.9.0)
Requirement already satisfied: django-filer>=1.4 in c:\users\jonas\appdata\local\programs\python\python38-32\li
b\site-packages (from djangocms-blog) (1.7.1)
Requirement already satisfied: django-cms>=3.5 in c:\users\jonas\appdata\local\programs\python\python38-32\lib\
site-packages (from djangocms-blog) (3.7.2)
Requirement already satisfied: djangocms-apphook-setup in c:\users\jonas\appdata\local\programs\python\python38
-32\lib\site-packages (from djangocms-blog) (0.4.1)
Requirement already satisfied: easy-thumbnails<2.8,>=2.4.1 in c:\users\jonas\appdata\local\programs\python\pyth
on38-32\lib\site-packages (from djangocms-blog) (2.7)
Requirement already satisfied: django-meta>=1.4 in c:\users\jonas\appdata\local\programs\python\python38-32\lib
\site-packages (from djangocms-blog) (1.6.1)
Requirement already satisfied: django-taggit<1.3,>=0.20 in c:\users\jonas\appdata\local\programs\python\python3
8-32\lib\site-packages (from djangocms-blog) (1.2.0)
Requirement already satisfied: django-parler>=2.0 in c:\users\jonas\appdata\local\programs\python\python38-32\l
ib\site-packages (from djangocms-blog) (2.0.1)
Requirement already satisfied: pytz in c:\users\jonas\appdata\local\programs\python\python38-32\lib\site-packag
es (from djangocms-blog) (2019.3)
Requirement already satisfied: aldryn-apphooks-config>=0.5 in c:\users\jonas\appdata\local\programs\python\pyth
on38-32\lib\site-packages (from djangocms-blog) (0.5.3)
Requirement already satisfied: django-sortedm2m in c:\users\jonas\appdata\local\programs\python\python38-32\lib
\site-packages (from djangocms-blog) (3.0.0)
Requirement already satisfied: lxml in c:\users\jonas\appdata\local\programs\python\python38-32\lib\site-packag
es (from djangocms-blog) (4.5.0)
Requirement already satisfied: django-taggit-templatetags in c:\users\jonas\appdata\local\programs\python\pytho
n38-32\lib\site-packages (from djangocms-blog) (0.2.5)
Requirement already satisfied: Pillow in c:\users\jonas\appdata\local\programs\python\python38-32\lib\site-pack
ages (from djangocms-text-ckeditor>=3.5->djangocms-blog) (7.1.2)
Requirement already satisfied: html5lib>=0.999999999 in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from djangocms-text-ckeditor>=3.5->djangocms-blog) (1.0.1)
Requirement already satisfied: six in c:\users\jonas\appdata\local\programs\python\python38-32\lib\site-package
s (from django-filer>=1.4->djangocms-blog) (1.14.0)
Requirement already satisfied: django-polymorphic<2.2,>=0.7 in c:\users\jonas\appdata\local\programs\python\pyt
hon38-32\lib\site-packages (from django-filer>=1.4->djangocms-blog) (2.1.2)
Requirement already satisfied: django-mptt<1.0,>=0.6 in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from django-filer>=1.4->djangocms-blog) (0.11.0)
Requirement already satisfied: Unidecode<1.2,>=0.04 in c:\users\jonas\appdata\local\programs\python\python38-32
\lib\site-packages (from django-filer>=1.4->djangocms-blog) (1.1.1)
Requirement already satisfied: django<4.0,>=1.11 in c:\users\jonas\appdata\local\programs\python\python38-32\li
b\site-packages (from django-filer>=1.4->djangocms-blog) (3.0.6)
Requirement already satisfied: django-sekizai>=0.7 in c:\users\jonas\appdata\local\programs\python\python38-32\
lib\site-packages (from django-cms>=3.5->djangocms-blog) (1.1.0)
Requirement already satisfied: djangocms-admin-style>=1.2 in c:\users\jonas\appdata\local\programs\python\pytho
n38-32\lib\site-packages (from django-cms>=3.5->djangocms-blog) (1.5.0)
Requirement already satisfied: django-classy-tags>=0.7.2 in c:\users\jonas\appdata\local\programs\python\python
38-32\lib\site-packages (from django-cms>=3.5->djangocms-blog) (1.0.0)
Requirement already satisfied: django-treebeard>=4.3 in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from django-cms>=3.5->djangocms-blog) (4.3.1)
Requirement already satisfied: django-formtools>=2.1 in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from django-cms>=3.5->djangocms-blog) (2.2)
Requirement already satisfied: django-appdata>=0.2.0 in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from aldryn-apphooks-config>=0.5->djangocms-blog) (0.2.2)
Requirement already satisfied: django-templatetag-sugar>=0.1 in c:\users\jonas\appdata\local\programs\python\py
thon38-32\lib\site-packages (from django-taggit-templatetags->djangocms-blog) (1.0)
Requirement already satisfied: webencodings in c:\users\jonas\appdata\local\programs\python\python38-32\lib\sit
e-packages (from html5lib>=0.999999999->djangocms-text-ckeditor>=3.5->djangocms-blog) (0.5.1)
Requirement already satisfied: django-js-asset in c:\users\jonas\appdata\local\programs\python\python38-32\lib\
site-packages (from django-mptt<1.0,>=0.6->django-filer>=1.4->djangocms-blog) (1.2.2)
Requirement already satisfied: asgiref~=3.2 in c:\users\jonas\appdata\local\programs\python\python38-32\lib\sit
e-packages (from django<4.0,>=1.11->django-filer>=1.4->djangocms-blog) (3.2.3)
Requirement already satisfied: sqlparse>=0.2.2 in c:\users\jonas\appdata\local\programs\python\python38-32\lib\
site-packages (from django<4.0,>=1.11->django-filer>=1.4->djangocms-blog) (0.3.0)
Installing collected packages: djangocms-blog
Successfully installed djangocms-blog-1.1.0

C:\Users\Jonas\Desktop\CFD\CFD>py manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__ini
t__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__ini
t__.py", line 377, in execute
    django.setup()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\__init__.py", line 24
, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\apps\registry.py", li
ne 114, in populate
    app_config.import_models()
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\apps\config.py", line
 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in impor
t_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aldryn_apphooks_config\model
s.py", line 5, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (C:\Users\Jonas\AppD
ata\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\encoding.py)

C:\Users\Jonas\Desktop\CFD\CFD>pip install aldryn_apphooks_config --upgrade
Collecting aldryn_apphooks_config
  Downloading aldryn_apphooks_config-0.6.0-py2.py3-none-any.whl (33 kB)
Requirement already satisfied, skipping upgrade: django-appdata>=0.2.0 in c:\users\jonas\appdata\local\programs
\python\python38-32\lib\site-packages (from aldryn_apphooks_config) (0.2.2)
Requirement already satisfied, skipping upgrade: django-cms>=3.5 in c:\users\jonas\appdata\local\programs\pytho
n\python38-32\lib\site-packages (from aldryn_apphooks_config) (3.7.2)
Collecting Django<3.0,>=1.8
  Using cached Django-2.2.12-py3-none-any.whl (7.5 MB)
Requirement already satisfied, skipping upgrade: django-formtools>=2.1 in c:\users\jonas\appdata\local\programs
\python\python38-32\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (2.2)
Requirement already satisfied, skipping upgrade: django-classy-tags>=0.7.2 in c:\users\jonas\appdata\local\prog
rams\python\python38-32\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (1.0.0)
Requirement already satisfied, skipping upgrade: six in c:\users\jonas\appdata\local\programs\python\python38-3
2\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (1.14.0)
Requirement already satisfied, skipping upgrade: django-sekizai>=0.7 in c:\users\jonas\appdata\local\programs\p
ython\python38-32\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (1.1.0)
Requirement already satisfied, skipping upgrade: django-treebeard>=4.3 in c:\users\jonas\appdata\local\programs
\python\python38-32\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (4.3.1)
Requirement already satisfied, skipping upgrade: djangocms-admin-style>=1.2 in c:\users\jonas\appdata\local\pro
grams\python\python38-32\lib\site-packages (from django-cms>=3.5->aldryn_apphooks_config) (1.5.0)
Requirement already satisfied, skipping upgrade: pytz in c:\users\jonas\appdata\local\programs\python\python38-
32\lib\site-packages (from Django<3.0,>=1.8->django-appdata>=0.2.0->aldryn_apphooks_config) (2019.3)
Requirement already satisfied, skipping upgrade: sqlparse in c:\users\jonas\appdata\local\programs\python\pytho
n38-32\lib\site-packages (from Django<3.0,>=1.8->django-appdata>=0.2.0->aldryn_apphooks_config) (0.3.0)
Installing collected packages: aldryn-apphooks-config, Django
  Attempting uninstall: aldryn-apphooks-config
    Found existing installation: aldryn-apphooks-config 0.5.3
    Uninstalling aldryn-apphooks-config-0.5.3:
      Successfully uninstalled aldryn-apphooks-config-0.5.3
  Attempting uninstall: Django
    Found existing installation: Django 3.0.6
    Uninstalling Django-3.0.6:
      Successfully uninstalled Django-3.0.6
Successfully installed Django-2.2.12 aldryn-apphooks-config-0.6.0

**Comment by cfd-manager** [comment]
Oh it does... just found it ;) Can be closed, thanks!
