### ISSUE TITLE
unable to find option to select app config automatically

### ISSUE THREAD

**Issue by pupattan** [nephila/djangocms-blog#557]
While creating a post user has to select app. config
I dont want the user to select the app config. i want to make it default as its confuses some users.
I dont find any option/configuration to select it automatically and skip this step.
Without app config i am getting this error

> 'NoneType' object has no attribute 'set_author' 

![image](https://user-images.githubusercontent.com/19246595/81490676-af340280-92a2-11ea-9dcb-1db9d19eb3dd.png)

**Comment by yakky** [comment]
@pupattan which version of django CMS / Django are you using?

**Comment by yakky** [comment]
@pupattan this is currently the behavior of aldryn-apphooks-config, not something djangocms-blog can implement itself
This only happens when you have multiple configurations, right?

**Comment by pupattan** [comment]
i am able to fix this with BLOG_ADMIN_POST_FIELDSET_FILTER
Anyway its a great repo, Helped a lot . Thanks for your work :)

**Comment by yakky** [comment]
@pupattan thanks :bow: glad it's helpful
