### ISSUE TITLE
error: Django 3.1a1 is installed but Django<3.1,>=1.11 is required by {'django-appdata'}

### ISSUE THREAD

**Issue by g3rb3n** [nephila/djangocms-blog#563]
While setting a the development environment I get the following error:
error: Django 3.1a1 is installed but Django<3.1,>=1.11 is required by {'django-appdata'}
on:
python setup.py develop

os: Ubuntu 18.04
python: 3.6.9
pip: 20.1

Doing a pip install django==3.0.6 fixes the issue.

**Comment by yakky** [comment]
@g3rb3n how have you installed it?

normally non-release packages are not installed by `pip` so it should not be required to pin packages to exclude alpha releases

**Comment by g3rb3n** [comment]
I followed the procedure in CONTRIBUTING.rst

    $ mkvirtualenv djangocms-blog
    $ cd djangocms-blog/
    $ python setup.py develop

I was quite surprised to encounter the 3.1 alpha release. Finally had to downgrade to 2.2 to get testing up and running.

**Comment by yakky** [comment]
In the updated contribution guide (#568) we recommend using `pip install -e .` which provides more reliable results
