### ISSUE TITLE
Individual test cases do not work when following steps in documentation

### ISSUE THREAD

**Issue by g3rb3n** [nephila/djangocms-blog#565]
`python cms_helper.py test tests.test_views` raises errors.

ModuleNotFoundError: No module named 'app_helper'
fix: `pip install django_app_helper`

ModuleNotFoundError: No module named 'aldryn_search'
fix: `pip install aldryn_search`

ModuleNotFoundError: No module named 'djangocms_video'
fix: `pip install djangocms_video`

ModuleNotFoundError: No module named 'six'
fix: `pip install django==2.2`

Probably `pip install -r requirements-test.txt` needs to be run first

I did expect that `python setup.py develop` would do this.

**Comment by yakky** [comment]
Fixed by #566
