### ISSUE TITLE
Unable to update BlogConfig 

### ISSUE THREAD

**Issue by pupattan** [nephila/djangocms-blog#570]
I am trying to update BlogConfig in program using the following code.
But its not updating. When i am trying from admin menu form its correctly updating

```
app_config= BlogConfig.objects.get(pk=1)
app_config.menu_structure = PERMALINK_TYPE_CATEGORY
app_config.save()
```
app_config.menu_structure still shows "complete"

**Comment by yakky** [comment]
as `BlogConfig` is an appdata model, the attributes are just a "proxy" for the real data stored in the app_data object. You must use `app_config.app_data.config.foo = bar` syntax
See https://github.com/nephila/djangocms-blog/blob/develop/tests/test_menu.py#L144 for a usage example in the tests

**Comment by yakky** [comment]
@pupattan have you been able to change the configuration by following the information in my comment?

**Comment by pupattan** [comment]
Yes. Thank you

**Comment by yakky** [comment]
thanks for the update
