### ISSUE TITLE
Replace deprectated function calls

### ISSUE THREAD

**Issue by g3rb3n** [nephila/djangocms-blog#571]
There are a some deprecation warnings:
* DeprecationWarning: Please use assertRegex instead.
* DeprecationWarning: Please use assertEqual instead.
* RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
* RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str().
* RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().

All new functions are python 3 and django 2.2 compatible.

**Comment by yakky** [comment]
Nice, I still need to get through them.
Some of them are fixed by #568 , but other will probably need some work

**Comment by g3rb3n** [comment]
Most warnings come from dependencies. I branched out of 564 and encountered some in djangocms-blog which I have replaced in feature/issue-571-replace-deprecated-function-calls. I will do a PR soon.
