### ISSUE TITLE
Do not import aldryn_search outside PostIndex in search_indexes.py

### ISSUE THREAD

**Issue by corentinbettiol** [nephila/djangocms-blog#584]
### Description

We're not using `aldryn_search` at all, but we're using `django-haystack` in order to index elements of our websites. We had installed `djangocms_blog`.

Haystack allows to exclude Indexes with its [EXCLUDED_INDEXES](https://django-haystack.readthedocs.io/en/master/settings.html?highlight=EXCLUDED_INDEXES#haystack-connections) paremeter, but it *only* excludes the content of the Index class.

The problem here is that you include `aldryn_search` submodules *outside* the PostIndex, and so when I prevent your `search_indexes.py` from being used by haystack using `"EXCLUDED_INDEXES": ["djangocms_blog.search_indexes.PostIndex"],`, it always try to import `aldryn_search`, even without using your `PostIndex` at all.

https://github.com/nephila/djangocms-blog/blob/99ab6a1be8a930972d9712321a17ac67a2354bab/djangocms_blog/search_indexes.py#L1-L2

### Steps to reproduce

* Do *not* install `aldryn_search`.
* Try to index something on the project using `django-haystack`, but not djangocms_blog (thanks to `"EXCLUDED_INDEXES": ["djangocms_blog.search_indexes.PostIndex"],`).
* Exception:
   ```bash
   File "[...]djangocms_blog/search_indexes.py", line 4, in <module>
      from aldryn_search.helpers import get_plugin_index_data
   ModuleNotFoundError: No module named 'aldryn_search'
   ```

### Expected solution

Move lines `aldryn_search` imports in `search_indexes.py` inside the class:
https://github.com/nephila/djangocms-blog/blob/99ab6a1be8a930972d9712321a17ac67a2354bab/djangocms_blog/search_indexes.py#L11

**Comment by yakky** [comment]
@corentinbettiol unfortunately can't remove `from aldryn_search.utils import get_index_base` from module level import as it provide the base class for `PostIndex`

what we can easily do, is to catch `ImportError` and skip the `PostIndex` definition which will allow you to implement your own without `aldryn_search`

How's that sound to you?

**Comment by corentinbettiol** [comment]
I think that's be great !

Better than mocking the djangocms_blog.search_indexes module, like we actually are doing:

```python
import sys
from types import ModuleType

def mock_module():
    m = ModuleType("djangocms_blog.search_indexes" None)
    m.__file__ = "djangocms_blog.search_indexes" + '.py'
    sys.modules["djangocms_blog.search_indexes"] = m
 ```

**Comment by yakky** [comment]
@corentinbettiol could you please check linked PR?

**Comment by corentinbettiol** [comment]
@yakky I think it's my first review, I don't really know if I did anything wrong.

**Comment by yakky** [comment]
@corentinbettiol definitely nothing wrong!
Thanks for reviewing it, I amended the documentation as suggested
