### ISSUE TITLE
No plugins available to add to blog post page in frontend editing form using USE_PLACEHOLDER = True

### ISSUE THREAD

**Issue by sq9mev** [nephila/djangocms-blog#586]
## Description
No plugins available to add to blog post page in frontend editing form using USE_PLACEHOLDER = True
![djangocms_blog-no-plugins-available](https://user-images.githubusercontent.com/592307/83345618-db243000-a304-11ea-98ad-440f3aea2a04.png)

## Steps to reproduce

- create post and save it
- open right menu containing page structure
- use "+" button to add some plugin in "Media" or "Post_Content" placeholder
- no plugins is available to add while i'd expect to have some plugins available here
- however when some plugin is copied to clipboard 

## Versions

- djangocms_blog-1.1.1
- Django-2.2.9
- django_cms-3.7.2
- Python 3.8.2

## Expected behaviour

I'd expect at least some plugins are available to add.

## Actual behaviour

No plugins available to add.

**Comment by sq9mev** [comment]
Well, it's not djangocms_blog fault… in my templates i use custom tag which replaces spaces with &nbsp; after single letters (in polish language we do not leave a single letter at the end of the line).

Seems like "sierotki" custom tag should be used in more specific context, not covering whole content block in my project's base.html.

Closing as it;s not a bug.

**Comment by yakky** [comment]
@sq9mev thanks for reporting the root cause of the issue

**Comment by sq9mev** [comment]
Just for posterity: there were two problems with "sierotki" templatetag (https://room-303.com/blog/2009/08/12/python-utop-sierotki-w-zupie/):

1. lxml parser wraps output with html > body
2. script tags were processed as well causing strange problems

Here's the solution: https://gist.github.com/sq9mev/dbd9b2cdcb59c0828045eea46a05389f
