### ISSUE TITLE
Allow Content Managers to Select which Template the Plugin will Use

### ISSUE THREAD

**Issue by tacc-wbomar** [nephila/djangocms-blog#595]
## Description

Have "the plugin admin interface will allow content managers to select which template the plugin will use." ([source, bottom of document](https://github.com/nephila/djangocms-blog/blob/ff2d6a9d93bc26b380db9c3783b4c8d68c8a0569/docs/features/templates.rst)) to be a true statement, or document how and where and when the plugin admin interface will allow this.

## Use cases

"content managers to select which template the plugin will use"

## Proposed solution

Make "the plugin admin interface […] allow content managers to select which template the plugin will use." 

## Alternatives

Document how/where/when "the plugin admin interface will allow content managers to select which template the plugin will use".

## Additional information

I could only change the templates used by the blog by manually typing a path into the "TEMPLATE PREFIX:". I could **not** change the templates used by "select[ing] which template the plugin will use" in "the plugin admin interface".

### Admin Interface
<img width="309" alt="djangocms_blog template path in admin interface" src="https://user-images.githubusercontent.com/62723358/85433026-72b62080-b549-11ea-8a7b-3b45a5bd8bf1.png">

The path in this image does load templates from the directory specified (at `…/templates/djangocms_blog/default`).

### `settings.py`
```
BLOG_PLUGIN_TEMPLATE_FOLDERS = (
    ('default', 'Default template'),    # i.e. `templates/djangocms_blog/default/`
    ('vertical', 'Vertical timeline'),  # i.e. `templates/djangocms_blog/vertical/`
)
```

I also, after adding these settings, ran `python3 manage.py makemigrations` and `python3 manage.py migrate`.

### Expectation
A `<select>` dropdown menu form which I could select either "Default template" or "Vertical timeline".

**Comment by yakky** [comment]
`Templates set` and `Plugin Templates` are two different features

`Templates set` applies to all the blog templates (i.e.: it allows to have different templates for posts lists and detail page) and has no dropdown, you have to set the path of the set of templates you want to use for blog posts belonging to that app configuration

`Plugin Templates` is instead a static setting which enable selecting the template style for each plugin

If you set this in your project settings
```diff
diff --git a/project/settings.py b/project/settings.py
index 4053d2d..6bd9afc 100755
--- a/project/settings.py
+++ b/project/settings.py
@@ -64,6 +64,11 @@ 


+    BLOG_PLUGIN_TEMPLATE_FOLDERS = (
+        ('plugins', ('Default template')),    # reads from templates/djangocms_blog/plugins/
+        ('timeline', ('Vertical timeline')),  # reads from templates/djangocms_blog/vertical/
+        ('masonry', ('Masonry style')),       # reads from templates/djangocms_blog/masonry/
+    )



```

you will be shown the dropdown below for plugins allowing a template to be selected

![2020-06-24_06-10](https://user-images.githubusercontent.com/714711/85499550-1c48f080-b5e2-11ea-97b5-dc95bbb0ffde.png)

**Comment by tacc-wbomar** [comment]
Thank you. This means I have, again, not understood how something works. I will revisit my other new issues, and documentation, with this new insight. I'll reply, again, when I have either satisfactorily understood or have more questions.

**Comment by tacc-wbomar** [comment]
My misunderstanding was caused by lack of familiarity with Python vocabulary.

- The `djangocms_blog` is an "**app**". _(I had considered it to be a "plugin" for DjangoCMS)_
    - Thus, templates for _it_ are called "Template sets".
- The `djangocms_blog` Plugins are "**plugins**". _(I had considered it to be a "component" for the `djangocms_blog`)_
    - Thus, templates for _them_ are called "Plugin templates".

I do not feel there is an immediate need for change to documentation.

**Comment by tacc-wbomar** [comment]
@yakky, thanks. I am experience a problem (even after incorporating your information to my understanding).

## Questions

1. Is this investigation appropriate to continue on this issue—i.e. should I create another issue, instead?
2. Which plugins offer this choice of "Plugin template:"?
3. If more than those I see offering it, then please assist me in troubleshooting. (I have tried some myself.)

## Actual Result

After (I believe) resolving my issues, I can see "Plugin template:" (as in your screenshot) only for these plugins:

- Latest Blog Articles
- Latest Blog Articles - Cache

## Expected Result

But, based on `djangocms_blog/models.py` and `djangocms_blog/cms_plugins.py`, I think I should see the "Plugin template:" option for these plugins (I do not):

- Archive
- Author Blog Articles
- Latest Blog Articles
- Latest Blog Articles - Cache
- Categories
- Tags

## Self Research

- [`templates.rst` @ Plugin Templates](https://github.com/nephila/djangocms-blog/blob/ff2d6a9d93bc26b380db9c3783b4c8d68c8a0569/docs/features/templates.rst#plugin-templates)
- [`settings.rst` @ `BLOG_PLUGIN_TEMPLATE_FOLDERS`](https://github.com/nephila/djangocms-blog/blob/ec83f5f670d0d7a026d4abf57ae307ecf94a8f4a/docs/settings.rst)
- [`djangocms_blog/models.py` @ line 482](https://github.com/nephila/djangocms-blog/blob/99ab6a1be8a930972d9712321a17ac67a2354bab/djangocms_blog/models.py#L482)
- [`djangocms_blog/cms_plugins.py`](https://github.com/nephila/djangocms-blog/blob/c5bb3cd2db8c6d30204e54bc5dde74eaf85dfb53/djangocms_blog/cms_plugins.py)

## Setup

### `settings.py`
```
# Configure `djangocms-blog`
BLOG_PLUGIN_TEMPLATE_FOLDERS = (
    ('plugins/default', 'Default template'),    # i.e. `templates/djangocms_blog/plugins/default/`
    ('plugins/vertical', 'Vertical timeline'),  # i.e. `templates/djangocms_blog/plugins/vertical/`
)
```

### Blog Config

For each (I have two functional ones), I have left "Template prefix:" _blank_.

### Directories & Files
```
|____djangocms_blog
| |____.DS_Store
| |____base.html
| |____plugins
| | |____default
| | | |____tags.html
| | | |____authors.html
| | | |____authors_posts.html
| | | |____archive.html
| | | |____categories.html
| | | |____latest_entries.html
| | |____vertical
| | | |____tags.html
| | | |____authors.html
| | | |____authors_posts.html
| | | |____archive.html
| | | |____categories.html
| | | |____latest_entries.html
| |____includes
| | |____blog_meta.html
| | |____blog_item.html
| |____post_list.html
| |____README.md
| |____post_detail.html
| |____post_archive.html
| |____post_instant_article.html
```

**Comment by yakky** [comment]
I think continuing on this issue is fine

all plugins should have a template selection, if `BLOG_PLUGIN_TEMPLATE_FOLDERS` has more than one entry, as in your example

I think I spot where the issue lies: this line (and similar above) https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/cms_plugins.py#L112 should be `exclude = ["template_folder"] if len(get_setting("PLUGIN_TEMPLATE_FOLDERS")) <2 else []`

**Comment by yakky** [comment]
@tacc-wbomar have a look at #605 for improved documentation regarding templates customization and feel free to suggest improvements

**Comment by yakky** [comment]
Missing select should be fixed in #612

**Comment by tacc-wbomar** [comment]
I have tested the feature on my instance, by:

1. installing the repo with the fix branch
2. restarting the server
3. ensuring each plugin loads select dropdown
4. testing that select dropdown (on one plugin) does use the template from the selected plugin templates.

**Comment by yakky** [comment]
thanks a lot for your tests, closing this
