### ISSUE TITLE
Plugin Templates are Expected in `default/` Not `plugins/`

### ISSUE THREAD

**Issue by tacc-wbomar** [nephila/djangocms-blog#596]
## Description

The [documentation](https://djangocms-blog.readthedocs.io/en/latest/features/templates.html#plugin-templates) states:

> Plugin templates live in the `plugins` folder of the folder specified by the **Template prefix**

But, I found them in the `default` folder of the folder specified by the **Template prefix**.

## Steps to reproduce

1. Go through all the basic installation, successfully.
1. Have an automatically set up Blog config.
1. Have an article.
1. Set "Template prefix" to `plugins/djangocms_blog/vertical`
1. Add clone of [`nephila/djangocms-blog`:`/djangocms_blog/templates/djangocms_blog`](https://github.com/nephila/djangocms-blog/tree/1.1.1/djangocms_blog/templates/djangocms_blog) into `/…/templates/plugins/djangocms_blog/` as `vertical/`, i.e.
    - from `nephila/djangocms-blog`:`/djangocms_blog/templates/djangocms_blog`
    - create (your installation):`/…/templates/djangocms_blog/vertical`
1. Add "Tags" plugin to an article.
1. Load article webpage that has tags plugin.

## Versions

- Python: 3
- Django: 1.11.22
- Django CMS: 3.6.0
- Django CMS Blog: 1.1.1 (migrated from already installed 1.0.0)

## Expected behaviour

1. See tags loaded on functional webpage.

## Actual behaviour

1. See error.
    - relevant string
      `django.template.loaders.filesystem.Loader: /code/taccsite_cms/templates/plugins/djangocms_blog/vertical/default/tags.html (Source does not exist)`
    - screenshot: <img width="941" alt="Screen Shot 2020-06-23 at 16 08 05" src="https://user-images.githubusercontent.com/62723358/85463138-ea954280-b56b-11ea-8ed4-c79246c4f680.png">

## Workaround

1. Rename template prefix sub-folder:
    - from `/…/templates/djangocms_blog/vertical/plugins`
    - to `/…/templates/djangocms_blog/vertical/default`
1. Load article webpage that has tags plugin.
1. See tags loaded on functional webpage.

## Additional information

Related ticket: #595

**Comment by yakky** [comment]
If you set `Template prefix` to `plugins/djangocms_blog/vertical` you will have to copy templates inside `templates/plugins/djangocms_blog/vertical` directory, as in `cp -a nephila/djangocms_blog/templates/djangocms_blog/* /path/my/project/templates/plugins/djangocms_blog/vertical`

Have you also set `BLOG_PLUGIN_TEMPLATE_FOLDERS` ?

**Comment by tacc-wbomar** [comment]
Yes, I have set `BLOG_PLUGIN_TEMPLATE_FOLDERS`:

```
# Configure `djangocms-blog`
BLOG_PLUGIN_TEMPLATE_FOLDERS = (
    ('default', 'Default template'),    # i.e. `templates/djangocms_blog/default/`
    ('vertical', 'Vertical timeline'),  # i.e. `templates/djangocms_blog/vertical/`
)
```

This "bug" no longer exists for me (after some changes since its report). I believe it was caused by a mix of the following:
- a misguided configuration of "Template sets"
- a misplacement of templates for "Template sets" and "Plugin templates"

It may or may not be a bug; but, if so, then it is likely an edge case; and, my intent is to set up "Template sets" and "Plugin templates", which I have done (and can continue to do better) thanks to clarification from #595.

**Comment by tacc-wbomar** [comment]
**Postmortem**

The `# i.e. …` comments in my `BLOG_PLUGIN_TEMPLATE_FOLDERS` are **not** accurate. Because I had set "Template prefix" to `plugins/djangocms_blog/vertical` and the "Plugin template" to default, the path to the "Plugin templates" was truly `templates/djangocms_blog/vertical/default/`, as was searched for (and not found) by the code.
