### ISSUE TITLE
Change Misleading Help Text for "Tags"

### ISSUE THREAD

**Issue by tacc-wbomar** [nephila/djangocms-blog#614]
## Disclaimer

I would make a feature request, but I thought that maybe there is a way to solve the problem on my own, for my instance.

## Description

The `taggit_autosuggest` app, used by `djangocms_blog`, expects users to type a comma, instead of hitting Enter key, to enter a tag. This is not intuitive, and the help text **visible to the user**, "A comma-separated list of tags.", is misleading; because, the input field visually creates tokens—the comma-separated list is a field **hidden from the user**.

## Questions & Research

1. How can I change the help text?
    - I searched [`djangocms-blog` for "comma-separated"](https://github.com/nephila/djangocms-blog/search?q=comma-separated&unscoped_q=comma-separated) and found "migrations" files… can I override data for those in my instance? If not, should I make a code change and merge request, instead?
    - I searched some [`django-taggit-autosuggest`](https://bitbucket.org/fabian/django-taggit-autosuggest/src/master/) files, and found none that seemed relevant to the text.

**Comment by yakky** [comment]
That's a tricky one
The string is defined in `django-taggit` https://github.com/jazzband/django-taggit/blob/master/taggit/managers.py#L423, where it's appropriate as there is no autocompletion mechanism. 
But it should be possible to override it in ``djangocms-blog`` by adding the proper `help_text` where `TaggableManager` is added https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/models.py#L273 (and generating a new migration)
Changing it locally in your environment will require monkeypatching the model, but I'm more than willing to improve the text to help users

**Comment by tacc-wbomar** [comment]
I am interested in—but do not have the professional bandwidth for—learning how to monkeypatch this. So, I won't.

I request an improvement of the text. Perhaps, any of these texts:

- You may assign a tag by typing a comma after typing the tag.\
    _Alternatively, you may select from an auto-complete list that will appear as you type._
- You may assign a tag by pressing the comma key after typing the tag.\
    _Alternatively, you may select from an auto-complete list that will appear as you type._
- You may type a comma to assign a tag after typing it.\
    _Alternatively, you may select from an auto-complete list that will appear as you type._
- You may press the comma key to assign a tag after typing it.\
    _Alternatively, you may select from an auto-complete list that will appear as you type._

The "_Alternatively, […] as you type._" might be unnecessary.

English is such a bother.

**Comment by yakky** [comment]
@tacc-wbomar thanks for you input, how about the changes in #626 

I posted some screenshots to make review easier

**Comment by tacc-wbomar** [comment]
Yes, great. And shorter text 👍. I did not know tab would work. Cool! Thank you.

_P.S. A comma may help in grammatically grouping the "logical operators". This is also likely just my personal interpretation problem._
> _A and B or C and D._
> _A and B, or C and D._

**Comment by yakky** [comment]
@tacc-wbomar sure, definitely better, I amended the PR :bow:

**Comment by tacc-wbomar** [comment]
Sweet, thanks for the effort!

And I can review this PR if I need to  learn to monkey patch text changes! (Because, I may find my team/clients to need more guidance than others CMS users.) _I probably would have missed the migration file and the language file change had I tried this._

**Comment by yakky** [comment]
@tacc-wbomar both things are minor and you usually catch them up shortly after, so they are not a big deal usually
It took me a lot of years (too many, in fact!) to remember to check both when doing this kind of changes :joy:
