### ISSUE TITLE
The BLOG_AUTO_… Setting Values Were Not Applied

### ISSUE THREAD

**Issue by tacc-wbomar** [nephila/djangocms-blog#629]
## Description

Setup did not successfully configure auto-setup for blog using `settings.py`'s `BLOG_AUTO_…` values.

## Steps to reproduce

1. Install DjangoCMS with these settings\*:
    ```
    BLOG_AUTO_SETUP: True
    BLOG_AUTO_HOME_TITLE: 'Home Test'
    BLOG_AUTO_BLOG_TITLE: 'News Test'
    BLOG_AUTO_APP_TITLE: 'News Test'
    ```

\* Source of settings: https://djangocms-blog.readthedocs.io/en/release-1.1.x/settings.html#global-settings

## Versions

Python: 3.6
Django: 1.11.22
Django CMS: (I tried two versions)
- 1.1.1
- 1.1.2.dev0 (`1e51a42`) \*

\* `-e git+https://github.com/nephila/djangocms-blog.git@1e51a42fdfe91a26624a9f74c421bfc049d20c97#egg=djangocms-blog`

## Expected behaviour

- The auto-setup …something… should be : '**Home Test**'.
- The auto-setup Blog title (seen in navigation) should be '**News Test**'.
- The auto-setup Blog config / App title should be '**News Test**'.

## Actual behaviour

- The auto-setup …something… is : '**Home**' (I guess).\*
- The auto-setup Blog title (seen in navigation) is '**Blog**'.
- The auto-setup Blog config / App title is '**Blog**'.

\* Where should one see this value be applied?

## Additional information

`settings.py`
```
# Support `djangocms-blog`
META_SITE_PROTOCOL = 'http'
META_USE_SITES = True
META_USE_OG_PROPERTIES=True
META_USE_TWITTER_PROPERTIES=True
META_USE_GOOGLEPLUS_PROPERTIES=True # django-meta 1.x+
# META_USE_SCHEMAORG_PROPERTIES=True  # django-meta 2.x+

# Configure `djangocms-blog`
BLOG_PLUGIN_TEMPLATE_FOLDERS = (
    ('plugins/default', 'Default template'),    # i.e. `templates/djangocms_blog/plugins/default/`
    ('plugins/default-clone', 'Clone of default template'),  # i.e. `templates/djangocms_blog/plugins/default-clone/`
)
BLOG_AUTO_SETUP: True
BLOG_AUTO_HOME_TITLE: 'HomeBob'
BLOG_AUTO_BLOG_TITLE: 'NewsBob'
BLOG_AUTO_APP_TITLE: 'NewsBob'

...

INSTALLED_APPS = [
    ...

    # Support `djangocms-blog`
    # 'filer',              # Already added
    # 'easy_thumbnails',    # Already added
    'aldryn_apphooks_config',
    'parler',
    'taggit',
    'taggit_autosuggest',
    'meta',                 # also supports `djangocms_page_meta`
    'sortedm2m',
    'djangocms_blog',

    'djangocms_page_meta',

    ...
```

**Comment by yakky** [comment]
@tacc-wbomar setting parameters are python variables, so they must be written as

```
BLOG_AUTO_SETUP = True
BLOG_AUTO_HOME_TITLE = 'HomeBob'
BLOG_AUTO_BLOG_TITLE = 'NewsBob'
BLOG_AUTO_APP_TITLE = 'NewsBob'
```

**Comment by tacc-wbomar** [comment]
Oh, I am so sorry…

Big minds miss little things—that's how I defend my silliness.

**Comment by yakky** [comment]
> Oh, I am so sorry…
> 
> Big minds miss little things—that's how I defend my silliness.

No worries, I miss much bigger things every day :)
