### ISSUE TITLE
admin/parler/change_form.html TemplateDoesNotExist

### ISSUE THREAD

**Issue by khaldon** [nephila/djangocms-blog#634]
## Description

`admin/parler/change_form.html` TemplateDoesNotExist

## Steps to reproduce

After install djangocms_blog and migrate it when I am trying to add blog article from admin page it gives me TemplateDoesNotExist
## Versions

```
django-cms>=3.7,<3.8
Django<3.1
```

## Expected behaviour

it should create an article without any error

## Actual behaviour

```
admin/parler/change_form.html
Exception Type: TemplateDoesNotExist
```

**Comment by yakky** [comment]
@khaldon have you added `'parler'` to `INSTALLED_APPS`?
