### ISSUE TITLE
Post Text Field does not show

### ISSUE THREAD

**Issue by lefthandmastery** [nephila/djangocms-blog#636]
## Description
Blog articles wizard does not show a Text field for the blog, only the abstract is displayed. 

.

## Steps to reproduce

From fresh installation of djangocms and djangocms-blog, added the required configuration to run the blog with no errors
## Versions
python = 3.7.3
djangocms-blog = 1.1.1
django = 3.0.1

## Expected behaviour
![aa](https://user-images.githubusercontent.com/2765318/93761427-5a38cd80-fc40-11ea-9cb8-83d2b289922a.JPG)

## Actual behaviour

Not sure why the Text does not show, are there any missing configurations I should do?

![missing](https://user-images.githubusercontent.com/2765318/93761521-82c0c780-fc40-11ea-8e45-a4ac657f031b.JPG)

**Comment by yakky** [comment]
@lefthandmastery check the added note on the documentation https://djangocms-blog.readthedocs.io/en/latest/installation.html#attach-the-blog-to-a-page
