### ISSUE TITLE
URL pattern warning issued upon runserver command

### ISSUE THREAD

**Issue by macciocu** [nephila/djangocms-blog#648]
## Description
runserver command issues URL pattern warning

## Steps to reproduce

`pip install -r requirements.txt`

With requirements.txt contents:

```
django-cms ~= 3.8
djangocms-admin-style >= 1.5,<1.6
django-treebeard >= 4.0,<5.0
djangocms-blog ~= 1.2.0
djangocms-text-ckeditor >= 3.7,<4.0
djangocms-link >= 2.5,<2.7
djangocms-icon >= 1.4,<1.6
djangocms-style >= 2.2,<2.4
djangocms-googlemap >= 1.3,<1.5
djangocms-snippet >= 2.2,<2.4
djangocms-video >= 2.1,<2.4
djangocms-file >= 2.3,<2.5
djangocms-picture >= 2.3,<2.5
djangocms-bootstrap4 >= 1.5,<1.7
easy_thumbnails
django-filer >= 1.3
Django<3.1
html5lib >= 1.0.1
Pillow >= 3.0
six >= 1.15.0,<2.0.0
pytz >= 2020.4,<2021.0
psycopg2-binary >= 2.8.6,<3.0
gunicorn ~= 20.0.4
gevent ~= 20.9.0
greenlet ~= 0.4.17
```
python manage.py runserver 0.0.0.0:8000

Will issue the following warning:

> ?: (2_0.W001) You URL pattern 'publish/<int:pk>/$' [name='djangocms_blog_publish_article'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path()

## Versions

python 3.8
django-cms ~= 3.8
django < 3.1

## Expected behaviour

runserver executes without warnings.

## Actual behaviour

> ?: (2_0.W001) You URL pattern 'publish/<int:pk>/$' [name='djangocms_blog_publish_article'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path()

is issued.

**Comment by yakky** [comment]
@macciocu thanks for raising the issue, I opened a PR to fix that
