### ISSUE TITLE
Multiple blog layouts?

### ISSUE THREAD

**Issue by benjh33** [nephila/djangocms-blog#65]
Hi,

I'm not a django expert by any means, so forgive me if I'm missing something obvious. I've spent the last few days learning the ropes of django cms and chose your blog to go with it. Is there a way to choose different layouts for posts similar to {% CMS TEMPLATES %} for a CMS page?

Thanks,
Ben

**Comment by tparsli** [comment]
I suggest named templates with the possibility to override settings (BLOG_).
LatestPostsPlugin also needs some way to override BLOG_IMAGE_THUMBNAIL_SIZE and BLOG_POSTS_LIST_TRUNCWORDS_COUNT!

If I have time next week I might write some actual code...

**Comment by yakky** [comment]
Settings definition will probably be integrated by using the namespaced apphooks spec in django CMS (https://github.com/divio/django-cms/wiki/spec:-namespaced-apphooks) which should be ready for 3.1

**Comment by jedie** [comment]
I add a apphook blog page. Is it normal that the selected template in the page settings will be ignored?!?

**Comment by yakky** [comment]
This will be fixed by #126

**Comment by yakky** [comment]
Fixed in #147
