### ISSUE TITLE
KeyError at /es/admin/djangocms_blog/blogconfig/1/change/

### ISSUE THREAD

**Issue by jib-72** [nephila/djangocms-blog#651]
## Description

Hi, I m working with Django CMS 3.7 and I just update to the last version Django CMS BLOG 1.2.1 and when I press the button Edit configuration in the toolbar I get this error   /es/admin/djangocms_blog/blogconfig/1/change/
![django_cms_blog_error](https://user-images.githubusercontent.com/74718194/99693691-effba800-2a8b-11eb-8745-84e0482e1434.png)
The cms languages is settings like this 
CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'es',
            'name': gettext('Español'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'en',
            'name': gettext('English'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'ca',
            'name': gettext('Catalá'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },            
    
    ],
    'default': {
        'fallbacks': ['en', 'es', 'ca'],
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}

## Steps to reproduce
Try  to 

## Versions

Environment:
Django CMS BLOG Version: 1.2.1
Django CMS Version: 3.7.5
Django Version: 3.0.9
Python Version: 3.7.5

## Expected behaviour
Press button Edit configuration

## Additional information
thanks  , any help will be apreciate

**Comment by yakky** [comment]
@jib-72 which was the previous version you updated from?
which command have you used to update the packages?
which is the django-appdata version? <- this is likely the issue, make sure to have the latest django-appdata which fix some compatibility issues with django 3.0+

**Comment by jib-72** [comment]
Hi yakky, 
Sorry for the delay in answering. I delete the records in the plugin database and update django-appdata and the new version of django-cms 3.8. It seems to work. Thank you very much for your recommendations.

**Comment by yakky** [comment]
@jib-72 thanks for the update, glad it worked!
