### ISSUE TITLE
NoReverseMatch if slug contains special characters when updating to 1.2.1

### ISSUE THREAD

**Issue by taut-and-yare** [nephila/djangocms-blog#653]
## Description

In a working installation of the blog, I am trying to upgrade from  1.1.1 --> 1.2.1

Post.get_absolute_url  throws a NoReverseMatch error when slug contains special characters (umlauts etc.)

## Steps to reproduce

Add new post containing a "special character" ( e.g. ü )

## Versions

python 3.6, Django 2.2, django-cms 3.7.4, djangocms-blog 1.2.1

## Expected behaviour

Post appears in list and detail pages.

## Actual behaviour

- List view page below ( the error is thrown from a call to get_absolute_url  in a template [here](https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/templates/djangocms_blog/includes/blog_item.html#L5) ) :
<img width="1440" alt="Screen Shot 2020-11-30 at 12 23 33 PM" src="https://user-images.githubusercontent.com/12593057/100604628-111f8c80-3307-11eb-89df-490977006341.png">

- Detail page returns a 404

## Additional information

In the shell:
<img width="961" alt="Screen Shot 2020-11-30 at 12 32 34 PM" src="https://user-images.githubusercontent.com/12593057/100605451-3bbe1500-3308-11eb-8940-45c5c99f1955.png">

Note that in the live site ( where djangocms-blog==1.1.1 ) all works as expected for the [same post ](https://www.ausgestrahlt.de/blog/2020/10/01/atomm%C3%BCll-karte-die-fehler-der-bge/)as above

**Comment by yakky** [comment]
@taut-and-yare this has been fixed in PR #654 kindly provided by @pierreben :bow:
