### ISSUE TITLE
Add the ability to include header images in RSS feed

### ISSUE THREAD

**Issue by g3rb3n** [nephila/djangocms-blog#662]
## Description
Add the ability to include header images in RSS feed. 

## Use cases
A customer that wants visually rich content in a RSS feed.

## Proposed solution
Add an option in global settings or in the app settings.
Add a CDATA section with the image to the RSS item description.

## Alternatives
Build a separate RSS feed.

## Additional information
None

**Comment by yakky** [comment]
Fixed by #729
