### ISSUE TITLE
Edit template

### ISSUE THREAD

**Issue by Immeo** [nephila/djangocms-blog#665]
Hello, please tell me how to redo the DjangoCMS blog template for the desired structure? I understand what needs to be edited post_list.html but there is no description of tags in the official documentation, what should I do? I need to output categories(Using input radio) and be able to choose to display articles of a certain category. Display the image (preview), title, and date. How do I do this? Unfortunately, there is very little about this in the documentation.

**Comment by protoroto** [comment]
Closing this as it is not relevant to DjangoCMS Blog ... Thanks @wesleyboar
