### ISSUE TITLE
How can I change configuration from local project?

### ISSUE THREAD

**Issue by YOBA1112** [nephila/djangocms-blog#669]
So, I'm trying to import djangocms_blog.settings into settings.py of my project to override it with new values, but when I do - I get this error:
`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
`
What's the proper way to change configuration?

**Comment by fsbraun** [comment]
Just a guess: `djangocms_blog.settings` needs not be imported or copied into `settings.py`. Rather use `settings.py` to overwrite standard settings in `djangocms_blog.settings`. 

E.g., if you want to have 25 words before a summary is truncated, add

`BLOG_POSTS_LIST_TRUNCWORDS_COUNT = 25`

to your `settings.py`.

For a list of settings you might want to change (but not have to) , see https://djangocms-blog.readthedocs.io/en/latest/autodoc/settings.html

**Comment by YOBA1112** [comment]
Oh, so I didn't need to import anything, got it, thanks a lot!
