### ISSUE TITLE
Error on installation!

### ISSUE THREAD

**Issue by 00091701** [nephila/djangocms-blog#67]
Some days ago I started I blog test on a dev system. Now I want setup the blog on my productive system and I got this error:

(env)david@dh-main:/tmp/cb5/ProjectSite$ pip install djangocms-blog
Downloading/unpacking djangocms-blog
  Downloading djangocms_blog-0.3.0-py2.py3-none-any.whl (78kB): 78kB downloaded
Downloading/unpacking django-meta-mixin>=0.1.1 (from djangocms-blog)
  Downloading django_meta_mixin-0.1.1-py2.py3-none-any.whl
Downloading/unpacking django-select2-py3 (from djangocms-blog)
  Downloading Django-Select2-Py3-4.2.1.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/tmp/cb5/ProjectSite/env/build/django-select2-py3/setup.py) egg_info for package django-select2-py3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/cb5/ProjectSite/env/build/django-select2-py3/setup.py", line 75
        % (fn, pattern)), file=sys.stderr)
                              ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/cb5/ProjectSite/env/build/django-select2-py3/setup.py", line 75

    % (fn, pattern)), file=sys.stderr)

                          ^

SyntaxError: invalid syntax

I use: python 2.7

**Comment by yakky** [comment]
Hi, it looks like an issue in the wheel file.
I removed it, install from the tarballs looks fine.
Could you test it?

**Comment by 00091701** [comment]
Now the installation works fine!
Thank you for your support!

**Comment by yakky** [comment]
Thank you for reporting!
A fixed wheel will be deployed soon, anyway
