### ISSUE TITLE
Insecure form action

### ISSUE THREAD

**Issue by aleray** [nephila/djangocms-blog#68]
Hi, 

I have just installed djangocms-blog and it works like a charm (thanks). I have one problem though: I'm using http+ssl and when I edit some content I get the following error message on Chromium (Firefox is working):

> `Mixed Content: The page at 'https://example.org/fr/blog/' was loaded over HTTPS, but requested an insecure form action 'http://example.org/fr/admin/djangocms_blog/post/'. This request has been blocked; the content must be served over HTTPS.`

Did I missed something?

Thanks

**Comment by yakky** [comment]
This is weird, actually: all paths should be domain(and protocol)-agnostic
Does the error message points you to any specific line of HTML? Could you try spotting the offending line by using the inspector? A find should reveal where this URL is.

**Comment by yakky** [comment]
@aleray did you manage to understand what happens here?

**Comment by yakky** [comment]
Closing due lack of feedback
