### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by 00091701** [nephila/djangocms-blog#69]
Hi,

I setup a new blog and have a problem with the pagination. I got this 
< a href="?=2" >nächste »< /a >
as Link (the name of the variable does not exists).

**Comment by yakky** [comment]
Can reproduce with default template. WIll update on this soon

**Comment by yakky** [comment]
@00091701 0.3.1 will be released soon with this issue fixed

**Comment by 00091701** [comment]
@yakky Thank you for your support!

**Comment by yakky** [comment]
@00091701 version 0.3.1 released!
