### ISSUE TITLE
Installation dependency issue

### ISSUE THREAD

**Issue by Zundrium** [nephila/djangocms-blog#73]
After installing a django CMS 3 app with the djangocms-installer I installed djangocms-blog using pip. After adding the minimum config and dependencies to the INSTALLED_APPS. 

After running `./manage.py migrate` I received the following error:
`djangocms_blog.0001_initial dependencies reference nonexistent parent node (u'filer', u'0001_initial')"
`

filer is installed and the same goes for the 0001_initial.py file. Any idea what I'm doing wrong?

Thanks in advance :)

**Comment by yakky** [comment]
Have you set filer and related dependencies into ``INSTALLED_APPS``=

**Comment by szczav** [comment]
I had the same issue in Django 1.7. After adding two lines into MIGRATION_MODULES everything works fine:

MIGRATION_MODULES = {
&nbsp;&nbsp;&nbsp;&nbsp; ...
&nbsp;&nbsp;&nbsp;&nbsp; 'filer': 'filer.migrations_django',
&nbsp;&nbsp;&nbsp;&nbsp; 'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
}

**Comment by yakky** [comment]
@szczav yes, the above setting is required for filer to work in 1.7

**Comment by Zundrium** [comment]
Sorry for the late response @yakky, adding those rules does fix the issue. Please add it to the "quick hint" part of the markdown.
