### ISSUE TITLE
fix incorrect dependencies

### ISSUE THREAD

**Issue by wfehr** [nephila/djangocms-blog#763]
blog-version 2.0.4 uses `django-meta.settings.get_setting`: [commit](https://github.com/nephila/djangocms-blog/commit/f382ba37091612ab803220b0af2d8ba4b420d0f2)

This `get_setting`-function was introduced in `django-meta==2.4.0`.
As seen in above commit, the dependency was changed to `django-meta>=2.3.0` which therefore is incorrect.

The dependency should be set to `>=2.4.0` to avoid incorrect installations.

**Comment by protoroto** [comment]
@wfehr You're right, I don't know how I missed that. Will release a new version asap.

**Comment by protoroto** [comment]
@wfehr We've just released 2.0.5 version. This should be fixed now! Thanks for pointing this out!
