### ISSUE TITLE
Creating multiple independent blogs

### ISSUE THREAD

**Issue by motleytech** [nephila/djangocms-blog#77]
I wanted to create a site with multiple independent blog pages and I was hoping the "application instance name" field will allow me to do that.

What does the "Application Instance name" field do?

I guessed that it might allow me to create multiple pages, and associate them with different blogs. Basically, create separate independent blog pages (for example, I could have a blog on physics simulations, and another on origami and I want to keep them completely separate).

However, on creating 2 different pages, both associated with the Blog application, but with different "application instance names", I saw that any blog posts that I create in one show up in the other as well.

Is there a way to create multiple independent blogs with djangocms-blog?

ps: This might be a django cms question rather than a djangocms-blog question, and I apologize in advance if that is the case...

(Edited issue title and text)

**Comment by yakky** [comment]
@motleytech it's actually a django CMS question :)
Currently it's not possible, but 3.1 (3.1 alpha1 is due in a few days, final scheduled for april) will resolve that with full filtering on apphooks instance.
After alpha1 I'll update the blog to use those features

**Comment by motleytech** [comment]
@yakky 
Thanks for the quick answer and the awesome work. I very much look forward to any updates.

**Comment by motleytech** [comment]
@yakky 
Reopening. I will let you close this (just in case you want this around until the cms implements the apphooks). If you feel its redundant and just cluttering up your issues, please feel free to close this again.

**Comment by yakky** [comment]
This will be fixed by #126

**Comment by yakky** [comment]
Fixed in #147

**Comment by motleytech** [comment]
Awesome :+1: 
Thank you @yakky
