### ISSUE TITLE
Missing `force_str`

### ISSUE THREAD

**Issue by adrien-delhorme** [nephila/djangocms-blog#780]
Using the plugin `BlogFeaturedPostsPluginCached` raises an exception:
`TypeError: __str__ returned non-string (type __proxy__)`

Because this method does not call `force_str`:
https://github.com/nephila/djangocms-blog/blob/d95802c1475fc7e06ba121a178bb0e755be9bba9/djangocms_blog/models.py#L608

**Comment by protoroto** [comment]
@adrien-delhorme Thanks for reporting this: will try to fix and release a new version today

**Comment by protoroto** [comment]
@adrien-delhorme We've just released 2.0.6 version: could you please check if now it's working as expected?

**Comment by adrien-delhorme** [comment]
It's working. Thanks!
