### ISSUE TITLE
FeaturedPostsPlugin displays all posts instead of selected posts

### ISSUE THREAD

**Issue by adrien-delhorme** [nephila/djangocms-blog#781]
The plugin `FeaturedPostsPlugin` requires to select some posts to display, and then the `get_posts` method returns all posts of the blog:
https://github.com/nephila/djangocms-blog/blob/d95802c1475fc7e06ba121a178bb0e755be9bba9/djangocms_blog/models.py#L614

**Comment by protoroto** [comment]
@adrien-delhorme Thanks for reporting this: will try to fix and release a new version today

**Comment by protoroto** [comment]
@adrien-delhorme We've just released 2.0.6 version: could you please check if now it's working as expected?

**Comment by adrien-delhorme** [comment]
Perfect, thank you (and happy new year 🥳)
