### ISSUE TITLE
DEMO page or "djangocms-blog users" links?

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#79]
There is no DEMO page, isn't it?

Is there somewhere a list of djangocms-blog users?

**Comment by yakky** [comment]
No currently demo page planned.
While I know a few present and past contributors of djangocms-blog, there is way to track them and no official list, but it'd nice to have one.
I'll try to come up with some ideas how to build one

**Comment by yakky** [comment]
Added a list of known djangocms-blog websites to the README section
