### ISSUE TITLE
placeholder without django admin interface?!?

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#85]
I'm a little confuse...

The is ```BLOG_USE_PLACEHOLDER``` it's ```True``` in my case (and by default)...

But it seems that there is no interface to create/edit content via placeholder.
I see only the translated "abstract" field in admin.

So the detail view has always no content, because ```{% render_placeholder post.content %}``` will always result in no content.

**Comment by jedie** [comment]
Hm.

I see that i cann add/edit placeholder with the djangocms frontend. But not in the admin.

So the workflow is:
* Create a new blog entry in django admin backend
* publish the entry (otherwise it's not on the frontend)
* go in the frontend to the new post
* edit the page via djangocms frontend
* add/change placeholders

Is this right?!?

**Comment by jedie** [comment]
What's about this:

if ````BLOG_USE_PLACEHOLDER==True```:
* remove "publish" from django admin form
* redirect after create in django admin to blog article
* activate the "DRAFT/structure" mode

Maybe auto add always one "TextPlugin" to a new created article?

**Comment by yakky** [comment]
The workflow is dictated by django CMS.
There are plans to implement a more flexible workflow in the CMS itself, but it's beyond the reach of this application

**Comment by yakky** [comment]
Please have a look at above PR

**Comment by jedie** [comment]
OK... But IMHO it is a good idea to help the users now ;)

What's about this:

if ```BLOG_USE_PLACEHOLDER==True```: Auto add one "TextPlugin" ?

Currently it's very circuitous to create a blog article if placeholder are used.

**Comment by yakky** [comment]
This can be configured using ``CMS_PLACEHOLDERCONF`` (http://django-cms.readthedocs.org/en/support-3.0.x/reference/configuration.html#cms-placeholder-conf, see "Default plugins")
The less magic happens in the application the better

**Comment by jedie** [comment]
Thanks!

I add now this:
```
CMS_PLACEHOLDER_CONF = {
    'content': {
        'name' : _('Content'),
        'default_plugins':[
            {
                'plugin_type':'TextPlugin',
                'values':{'body':'<p></p>'},
            },
        ]
    },
    'post_content': {
        'name' : _('Content'),
        'default_plugins':[
            {
                'plugin_type':'TextPlugin',
                'values':{'body':'<p></p>'},
            },
        ]
    },
}
```

Maybe a good idea to add some needfull example settings into README?

btw. i think the "went hurdle" is very high ;)

**Comment by jedie** [comment]
Some more workflow suggestions and questions:

the blog post category is a needed field. But the field is under collapsed "info" tab :(
-> IMHO move the "category" selection above in the default area
-> Maybe select by default "Uncategorized" (which must be created first)?

And IMHO it's a good idea to redirect after blog creation. I added this:
```
    def response_add(self, request, obj, post_url_continue=None):
        super(PostAdmin, self).response_add(request, obj, post_url_continue)
        return HttpResponseRedirect("%s?edit" % obj.get_absolute_url())
```
to PostAdmin() class. But this only work, if the normal django admin backend is used to create a new blog entry... If the djangocms frontend is used, the redirect will not work. Think because of JavaScript "inline" usage...

it's a pity

**Comment by yakky** [comment]
I really dislike automatic redirection, especially from inside the admin to the frontend. A proper solution must be implemented at the cms level so all the application can benefit

**Comment by jedie** [comment]
Yes, redirect from admin backend to frondend is confusing.

But the normal you start a new blog post in the djangocms frontend, isn't it?

**Comment by jedie** [comment]
Sorry, that i ask again... Currently it works in this way:

1. create a new blog entry (You can only add the abstract part here)
2. Go to djangocms frontend to the new blog entry (Important: You must be in Draft mode, otherwise you didn't see it!)
3. You add the real content by add/fill placeholder
4. Now you would like to publish. But how? There is no "publish blog article"
5. You have to go into the backend and edit the blog article again to publish it

The boring things here are:
* You have to go back and forth to create and publish a new article
* It's IMHO confusion that you only see a non-published blog article if you are in Draft mode.

I don't know what the future plans in djangcms are to simplify this in the blog app...
Will be all points address in next releases of djangocms?!?

What's about to display non-published blog entries, for users who hat the permissions to edit blog posts?
