### ISSUE TITLE
Question: How to create a enhanced blog page?!?

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#91]
I'm new to djangocms and try to setup a full features blog page. similar to https://www.django-cms.org/en/blog/ 

Currently i see this solution:

* one page with the blog AppHook
* one normal djangocms page with template='sidebar_left.html':
  * Placeholder with slot="content" contains "BlogLatestEntriesPlugin"
  * Placeholder with slot="sidebar" contains: "BlogArchivePlugin", "BlogAuthorPostsPlugin", "BlogCategoryPlugin" and "BlogTagsPlugin"

The second "sidebar" page, looks similar to https://www.django-cms.org/en/blog/ 
But if i click on a "Read more" i will go to the first Blog-AppHook page and the Archive, Tags etc. are gone (Because they aren't on this page)

I didn't see a solution for this...

**Comment by yakky** [comment]
This is really a django CMS support question, please join #django-cms IRC channel or django-cms-user google group (https://groups.google.com/forum/#!forum/django-cms)
You'd want to have a look at static placeholders: http://django-cms.readthedocs.org/en/support-3.0.x/reference/templatetags.html#static-placeholder

**Comment by jedie** [comment]
thanks, done here: https://groups.google.com/forum/#!topic/django-cms/mzWQOoEqW9s

**Comment by jedie** [comment]
I found a solution and create a new blog article in my old blog: http://www.pylucid.org/en/blog/2015/02/22/setup-a-enhanced-djangocms-blog-page/ ;)

I hope that this address will be served from djangocms-blog in the next future ;)
