### ISSUE TITLE
404 Bug: Display non-published blog for user with edit permissions...

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#96]
As i describe at https://github.com/nephila/djangocms-blog/issues/85#issuecomment-75383872 it is a little confusing that non-published blog post are only visible in DRAFT mode.

Now, i find a boring "bug" with it:

* activate DRAFT mode
* go to detail view of a non-publish blog entry
* switch to LIVE mode

This will result into 404... Because you stay at the same URL and the blog entry is not visible, now.

Also not good: If you are in DRAFT: You can't see if a blog post is published or not.

Solution:

* Don't filter non-published blog entries for user with edit permission.
* Mark non-published entries (e.g.: just add the Text "not published")

I didn't find a easy way to implement this :(

**Comment by yakky** [comment]
We may solve this by adding ``get_object_public_url`` / ``get_object_draft_url`` support (https://github.com/divio/django-cms/blob/develop/cms/toolbar/toolbar.py#L230-L249)

**Comment by yakky** [comment]
@jedie is thi still the cse with latest django CMS 3.1? Having unpublished objects unavailable in live mode is the default semantic for django CMS objects
The CMS should be now able to redirect to a saner location, that a 404, though

**Comment by yakky** [comment]
Fixed in 0.6.0 (https://github.com/nephila/djangocms-blog/blob/develop/djangocms_blog/views.py#L82 ensures the post is visible in draft mode)
