### ISSUE TITLE
{% page_attribute "changed_date" %}

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#98]
I add a ```{% page_attribute "changed_date" %}``` into the base template.

On a blog entry detail page, this date is not the blog date. It seems that this is the AppHook-Page date.

Is that normal?!?

**Comment by yakky** [comment]
Yes: ``{% page_attribute %}`` is for django CMS page data only.
To access the post data you cna use the ``post`` variable in the context

**Comment by jedie** [comment]
Ah, thanks!

I've done this:
```
    {% if post.date_published %}{# djangocms-blog #}
        {{ post.date_published|date:"SHORT_DATE_FORMAT" }}
    {% else %}
        {% page_attribute "changed_date" as date_changed %}{{ date_changed|date:"SHORT_DATE_FORMAT" }}
    {% endif %}
```

;)
